import { readFileSync, writeFileSync } from 'fs';

const filePath = 'data/products.json';
const data = JSON.parse(readFileSync(filePath, 'utf8'));
const existingSlugs = new Set(data.products.map(p => p.slug));

const newProducts = [
  {
    "id": "carolina-herrera-bad-boy",
    "slug": "carolina-herrera-bad-boy",
    "h1": "Carolina Herrera Bad Boy Parfum Homme Algérie",
    "name": "Bad Boy",
    "brand": "Carolina Herrera",
    "brandSlug": "carolina-herrera",
    "category": "parfums-homme",
    "gender": "homme",
    "concentration": "EDT",
    "volume": "100ml",
    "price": 8900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/carolina-herrera-bad-boy.jpg",
    "shortDescription": "Bad Boy de Carolina Herrera est un fougère aromatique audacieux pour l'homme moderne. Une ouverture bergamote-sauge sur un cœur en cuir, boisé et légèrement fumé.",
    "description": "Carolina Herrera Bad Boy est un parfum qui capture l'esprit de la rébellion élégante. Lancé en 2019, il s'impose rapidement comme une référence dans les parfums masculins contemporains grâce à son caractère à la fois sauvage et raffiné. Son flacon emblématique — une massue noire striée d'éclairs dorés — annonce la couleur : ce parfum n'est pas pour les timides.\n\nLa composition olfactive s'ouvre sur une bergamote pétillante et une sauge aromatique qui captent immédiatement l'attention. Le cœur révèle une alliance inédite de cèdre vertueux et de cuir fumé, deux matières qui semblent s'opposer mais se complètent avec une élégance surprenante. Le fond repose sur la chêne coumarine, le vétiver et le tonka, offrant une profondeur chaleureuse et sensuelle qui perdure des heures après l'application.\n\nBad Boy convient parfaitement à l'homme qui assume ses contradictions : sérieux au bureau mais décomplexé le soir, sophistiqué mais pas guindé. Sa longévité remarquable — six à huit heures en moyenne — en fait un choix idéal pour les longues journées algériennes où l'on enchaîne les rendez-vous professionnels et les soirées entre amis.\n\nDisponible chez Maison Numidia avec livraison COD dans les 58 wilayas d'Algérie via Yalidine, vous recevez le flacon original avec son hologramme de certification garantissant son authenticité.",
    "notes": {
      "top": ["Bergamote", "Sauge"],
      "heart": ["Cèdre", "Cuir"],
      "base": ["Chêne coumarine", "Vétiver", "Tonka"]
    },
    "family": "Fougère Aromatique",
    "occasions": ["Bureau", "Soirée", "Sortie nocturne"],
    "seasons": ["Automne", "Hiver"],
    "longevity": 4,
    "sillage": 4,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["carolina-herrera-212-vip-black", "jean-paul-gaultier-bad-boy", "paco-rabanne-1-million-elixir"]
  },
  {
    "id": "roberto-cavalli-just-cavalli-femme",
    "slug": "roberto-cavalli-just-cavalli-femme",
    "h1": "Roberto Cavalli Just Cavalli Parfum Femme Algérie",
    "name": "Just Cavalli Femme",
    "brand": "Roberto Cavalli",
    "brandSlug": "roberto-cavalli",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "EDT",
    "volume": "100ml",
    "price": 5900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/roberto-cavalli-just-cavalli-femme.jpg",
    "shortDescription": "Just Cavalli Femme est un floral fruité lumineux qui capture l'esprit libre et sensuel de la femme Roberto Cavalli. Agrumes, fleurs blanches et bois doux pour une signature unique.",
    "description": "Roberto Cavalli Just Cavalli Femme est né de la vision d'une femme moderne, libre et déterminée. La maison florentine, connue pour ses imprimés animaliers et son esthétique baroque, a transposé cette identité unique dans une fragrance qui se démarque par son caractère floral fruité et sa légèreté désarmante.\n\nLa composition s'ouvre sur une fraîcheur d'agrumes — bergamote et citron — qui invite immédiatement à la bonne humeur. Le cœur floral associe rose blanche, jasmin et fleur d'oranger dans un bouquet délicat qui évoque la Méditerranée ensoleillée. Le fond chaleureux mêle musc, cèdre blanc et vanille dans une douceur enveloppante qui persiste agréablement sur la peau.\n\nJust Cavalli Femme est une fragrance polyvalente, idéale pour les femmes qui aiment les parfums lumineux et sans complexe. Elle accompagne parfaitement les journées de printemps et d'été, mais sa douceur la rend tout aussi agréable lors des soirées automnales.\n\nDisponible chez Maison Numidia avec livraison COD dans les 58 wilayas d'Algérie, ce parfum original est livré avec le flacon authentique et ses accessoires d'emballage d'origine.",
    "notes": {
      "top": ["Bergamote", "Citron", "Pêche"],
      "heart": ["Rose blanche", "Jasmin", "Fleur d'oranger"],
      "base": ["Musc", "Cèdre blanc", "Vanille"]
    },
    "family": "Floral Fruité",
    "occasions": ["Journée", "Week-end", "Printemps"],
    "seasons": ["Printemps", "Été"],
    "longevity": 3,
    "sillage": 3,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["chloe-signature", "guerlain-mon-guerlain-sparkling-bouquet", "roberto-cavalli-just-cavalli-homme"]
  },
  {
    "id": "roberto-cavalli-just-cavalli-homme",
    "slug": "roberto-cavalli-just-cavalli-homme",
    "h1": "Roberto Cavalli Just Cavalli Homme Parfum Algérie",
    "name": "Just Cavalli Homme",
    "brand": "Roberto Cavalli",
    "brandSlug": "roberto-cavalli",
    "category": "parfums-homme",
    "gender": "homme",
    "concentration": "EDT",
    "volume": "90ml",
    "price": 5900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/roberto-cavalli-just-cavalli-homme.jpg",
    "shortDescription": "Just Cavalli Homme incarne l'élégance décontractée à l'italienne. Un boisé aromatique frais où la bergamote rencontre le bois de santal et le musc pour un résultat séduisant.",
    "description": "Roberto Cavalli Just Cavalli Homme est une ode à la liberté masculine selon la vision florentine de Roberto Cavalli. Ce parfum lancé dans les années 2000 a su s'inscrire dans la durée grâce à une composition équilibrée qui parle autant aux hommes classiques qu'aux esprits plus aventuriers.\n\nLa fragrance débute sur une envolée aromatique de bergamote et de lavande, une alliance intemporelle qui séduit immédiatement. Le cœur développe un caractère boisé-épicé avec du poivre noir, du géranium et une touche de muscade qui apportent du relief et du caractère. Le sillage est assuré par le bois de santal, le cèdre et un musc propre qui persistent plusieurs heures sur la peau.\n\nJust Cavalli Homme est le choix de l'homme qui apprécie les parfums modernes sans être esclave des tendances. Sa versatilité en fait un allié pour toutes les occasions : propre et discret au bureau, plus expansif lors d'une soirée.\n\nMaison Numidia vous garantit la livraison de parfums authentiques avec paiement à la réception (COD) dans toutes les wilayas d'Algérie via le réseau Yalidine.",
    "notes": {
      "top": ["Bergamote", "Lavande", "Citrus"],
      "heart": ["Poivre noir", "Géranium", "Muscade"],
      "base": ["Bois de santal", "Cèdre", "Musc blanc"]
    },
    "family": "Boisé Aromatique",
    "occasions": ["Bureau", "Journée", "Week-end"],
    "seasons": ["Printemps", "Été", "Automne"],
    "longevity": 3,
    "sillage": 3,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["roberto-cavalli-just-cavalli-femme", "armani-stronger-with-you-only", "azzaro-wanted"]
  },
  {
    "id": "ferragamo-signorina",
    "slug": "ferragamo-signorina",
    "h1": "Ferragamo Signorina Parfum Femme Algérie",
    "name": "Signorina",
    "brand": "Salvatore Ferragamo",
    "brandSlug": "salvatore-ferragamo",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "EDP",
    "volume": "100ml",
    "price": 7900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/ferragamo-signorina.jpg",
    "shortDescription": "Signorina de Salvatore Ferragamo est un floral poudré élégant qui célèbre la jeune femme italienne sophistiquée. Cassis, rose et bois doux dans une composition irrésistiblement raffinée.",
    "description": "Salvatore Ferragamo Signorina est une fragrance qui capture l'essence de la féminité italienne dans ce qu'elle a de plus lumineux et de plus gracieux. Lancée en 2012, Signorina s'est imposée comme l'un des parfums féminins les plus appréciés de la maison florentine, grâce à sa capacité rare à allier fraîcheur fruitée et élégance florale poudré.\n\nLa composition s'ouvre sur une effusion de cassis et de bergamote qui éveille immédiatement les sens avec une vivacité joyeuse. Le cœur floral associe la rose centifolia — fleur signature de la féminité chez Ferragamo — à un bouquet de fleurs blanches délicates. Le fond révèle une base chaleureuse de bois doux, patchouli léger et musc qui donne à la fragrance sa dimension sensuelle et persistante.\n\nSignorina est une fragrance toutes saisons, idéale pour les femmes qui souhaitent une signature olfactive à la fois moderne et intemporelle. Elle s'exprime avec bonheur sur la peau lors des journées de printemps et d'été, mais reste tout aussi pertinente en automne grâce à sa base boisée enveloppante.\n\nDisponible chez Maison Numidia avec livraison COD dans les 58 wilayas d'Algérie, le flacon authentique Signorina est livré dans son écrin d'origine avec toutes les garanties d'authenticité.",
    "notes": {
      "top": ["Cassis", "Bergamote", "Poire"],
      "heart": ["Rose centifolia", "Fleurs blanches", "Jasmin"],
      "base": ["Bois doux", "Patchouli", "Musc"]
    },
    "family": "Floral Fruité",
    "occasions": ["Journée", "Bureau", "Sorties"],
    "seasons": ["Printemps", "Été", "Automne"],
    "longevity": 4,
    "sillage": 3,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["chloe-love-story", "coach-floral", "nina-ricci-coeur-joie"]
  },
  {
    "id": "ferragamo-attimo-homme",
    "slug": "ferragamo-attimo-homme",
    "h1": "Ferragamo Attimo Parfum Homme Algérie",
    "name": "Attimo pour Homme",
    "brand": "Salvatore Ferragamo",
    "brandSlug": "salvatore-ferragamo",
    "category": "parfums-homme",
    "gender": "homme",
    "concentration": "EDT",
    "volume": "100ml",
    "price": 6900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/ferragamo-attimo-homme.jpg",
    "shortDescription": "Attimo pour Homme de Salvatore Ferragamo est un aquatique-boisé lumineux inspiré du style méditerranéen. Fraîcheur d'agrumes, fleurs marines et fond de cèdre pour un homme élégant.",
    "description": "Salvatore Ferragamo Attimo pour Homme est une célébration olfactive de l'instant présent — attimo signifie \"instant\" en italien. Lancé en 2011, ce parfum masculin incarne parfaitement l'art de vivre méditerranéen, avec son caractère aquatique et lumineux qui rappelle les côtes toscanes baignées de soleil.\n\nLa fragrance s'ouvre sur un éclair d'agrumes — bergamote sicilienne, citron et mandarine — qui capture la fraîcheur d'une brise marine. Le cœur développe une alliance harmonieuse de lavande, de cardamome et de notes marines qui évoquent l'horizon bleu de la Méditerranée. La base apporte profondeur et tenue grâce au cèdre virginie, au vétiver et à un musc propre et élégant.\n\nAttimo pour Homme est le parfum idéal pour les hommes qui privilégient la fraîcheur et la légèreté sans sacrifier l'élégance. Sa signature aquatique-boisée le rend particulièrement adapté aux saisons chaudes et aux journées actives, mais sa tenue en fait un choix pertinent toute l'année.\n\nMaison Numidia propose ce parfum authentique avec livraison COD dans les 58 wilayas d'Algérie. Un choix raffiné pour l'homme algérien épris de fragrances modernes et élégantes.",
    "notes": {
      "top": ["Bergamote", "Citron", "Mandarine"],
      "heart": ["Lavande", "Cardamome", "Notes marines"],
      "base": ["Cèdre", "Vétiver", "Musc"]
    },
    "family": "Aquatique Boisé",
    "occasions": ["Journée", "Bureau", "Plein air"],
    "seasons": ["Printemps", "Été"],
    "longevity": 3,
    "sillage": 3,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["ferragamo-signorina", "azzaro-chrome", "issey-miyake-l-homme-issey"]
  },
  {
    "id": "moschino-toy-boy",
    "slug": "moschino-toy-boy",
    "h1": "Moschino Toy Boy Parfum Homme Algérie",
    "name": "Toy Boy",
    "brand": "Moschino",
    "brandSlug": "moschino",
    "category": "parfums-homme",
    "gender": "homme",
    "concentration": "EDP",
    "volume": "100ml",
    "price": 7900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/moschino-toy-boy.jpg",
    "shortDescription": "Toy Boy de Moschino est un oriental boisé audacieux pour l'homme qui n'a peur de rien. Rose, safran, bois de oud et ambre dans une composition luxueuse et désarmante.",
    "description": "Moschino Toy Boy est une fragrance qui refuse les conventions. Lancée en 2019, elle fait le pari audacieux d'utiliser la rose — fleur traditionnellement associée à la féminité — dans un parfum masculin résolument affirmé. Le résultat est saisissant : un oriental boisé d'une rare sophistication qui bouscule les codes avec un sourire.\n\nLa composition s'ouvre sur un accord safran-rose d'une beauté troublante. Le safran apporte une chaleur épicée immédiate, tandis que la rose de Turquie dépose ses pétales avec une générosité presque théâtrale. Le cœur se déploie autour d'un bois de oud distillé avec soin, d'iris poudrée et de notes cuirées qui donnent au parfum sa dimension orientale et sa noblesse. Le fond chaleureux de vétiver, ambre et patchouli ancre la fragrance dans une longévité remarquable.\n\nToy Boy est fait pour les hommes qui assument leur sensibilité et leur goût pour le luxe sans ostentation. Sa concentration EDP lui confère une excellente tenue — six à huit heures sur la peau — et un sillage enveloppant qui marque les esprits.\n\nDisponible chez Maison Numidia avec livraison COD dans les 58 wilayas d'Algérie. Authentique, livré dans son flacon rose et or emblématique.",
    "notes": {
      "top": ["Safran", "Rose de Turquie"],
      "heart": ["Bois de oud", "Iris", "Cuir"],
      "base": ["Vétiver", "Ambre", "Patchouli"]
    },
    "family": "Oriental Boisé",
    "occasions": ["Soirée", "Dîner", "Événement"],
    "seasons": ["Automne", "Hiver"],
    "longevity": 4,
    "sillage": 4,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["carolina-herrera-bad-boy", "armani-stronger-with-you-only", "givenchy-gentleman-society"]
  },
  {
    "id": "moschino-toy-2",
    "slug": "moschino-toy-2",
    "h1": "Moschino Toy 2 Parfum Femme Algérie",
    "name": "Toy 2",
    "brand": "Moschino",
    "brandSlug": "moschino",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "EDP",
    "volume": "100ml",
    "price": 7500,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/moschino-toy-2.jpg",
    "shortDescription": "Moschino Toy 2 est un floral poudré espiègle qui célèbre la femme-enfant dans ce qu'elle a de plus charmant. Bergamote, pivoine et fond de musc dans un flacon en forme d'ours.",
    "description": "Moschino Toy 2 est la suite espiègle de la collection Toy de la maison italienne. Son flacon iconique en forme de petit ours rose est devenu l'un des objets de parfumerie les plus reconnaissables et collectionnables de la dernière décennie. Mais derrière ce packaging ludique se cache une fragrance florale poudré d'une réelle qualité.\n\nLa composition s'ouvre sur une fraîcheur de bergamote et de citron qui apporte de la vivacité et de l'entrain. Le cœur se développe autour d'un bouquet floral généreux dominé par la pivoine, le muguet et la rose, dans une interprétation joyeuse et contemporaine de la féminité. La base poudré de musc blanc, de bois de santal et d'héliotrope donne à Toy 2 sa dimension sensuelle et son caractère mémorable.\n\nCette fragrance est particulièrement appréciée des femmes qui aiment les parfums floriaux sans lourdeur et qui apprécient le design comme élément à part entière du produit. Le flacon Toy 2 est aussi beau sur une tablette de salle de bain qu'en situation d'utilisation.\n\nMaison Numidia vous propose ce parfum authentique avec livraison COD dans toutes les wilayas d'Algérie. Un cadeau parfait ou une petite folie personnelle pour une femme qui aime la vie.",
    "notes": {
      "top": ["Bergamote", "Citron", "Framboise"],
      "heart": ["Pivoine", "Muguet", "Rose"],
      "base": ["Musc blanc", "Bois de santal", "Héliotrope"]
    },
    "family": "Floral Poudré",
    "occasions": ["Journée", "Week-end", "Déjeuner"],
    "seasons": ["Printemps", "Été"],
    "longevity": 3,
    "sillage": 3,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["ferragamo-signorina", "coach-floral", "chloe-love-story"]
  },
  {
    "id": "hermes-un-jardin-sur-le-nil",
    "slug": "hermes-un-jardin-sur-le-nil",
    "h1": "Hermès Un Jardin sur le Nil Parfum Algérie",
    "name": "Un Jardin sur le Nil",
    "brand": "Hermès",
    "brandSlug": "hermes",
    "category": "parfums-femme",
    "gender": "unisexe",
    "concentration": "EDT",
    "volume": "100ml",
    "price": 10900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/hermes-un-jardin-sur-le-nil.jpg",
    "shortDescription": "Un Jardin sur le Nil d'Hermès est une escapade olfactive sur les bords du Nil. Notes vertes de lotus, mangue verte et bois séché évoquent la beauté sereine de l'Égypte ancienne.",
    "description": "Un Jardin sur le Nil est la deuxième création de la Collection Jardins d'Hermès signée Jean-Claude Ellena. Inspirée d'un séjour sur l'île d'Assouan en Égypte, cette fragrance est une invitation au voyage et à la contemplation, une méditation olfactive sur la beauté sereine du Nil et de ses rives verdoyantes.\n\nJean-Claude Ellena, ancien parfumeur exclusif de la maison Hermès, a su capturer l'essence particulière de cet endroit hors du temps. La fragrance s'ouvre sur des notes vertes aquatiques de fleur de lotus verte et de mangue verte immature, avec un caractère herbacé légèrement acide très caractéristique. Ce choix audacieux — utiliser la mangue avant sa maturité — est une signature Ellena, toujours à la recherche du détail inattendu.\n\nLe cœur évolue vers un arbre callistemon — appelé aussi rince-bouteille — et une terre de Nubie, évocatrice de la rive nubienne du Nil. Le fond apporte chaleur et enracinement avec du bois d'encens de cèdre et un sycamore séché, l'arbre sacré des Pharaons.\n\nUn Jardin sur le Nil est une fragrance unisexe qui parle à ceux qui ont voyagé ou rêvé de voyager. Disponible chez Maison Numidia avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Lotus vert", "Mangue verte", "Notes herbacées"],
      "heart": ["Callistemon", "Terre de Nubie", "Géranium"],
      "base": ["Cèdre", "Bois de sycamore", "Encens"]
    },
    "family": "Aquatique Floral",
    "occasions": ["Journée", "Bureau", "Voyage"],
    "seasons": ["Printemps", "Été"],
    "longevity": 3,
    "sillage": 3,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["hermes-un-jardin-en-mediterranee", "voyage-d-hermes", "terre-d-hermes"]
  },
  {
    "id": "ralph-lauren-polo-green",
    "slug": "ralph-lauren-polo-green",
    "h1": "Ralph Lauren Polo Green Parfum Homme Algérie",
    "name": "Polo Green",
    "brand": "Ralph Lauren",
    "brandSlug": "ralph-lauren",
    "category": "parfums-homme",
    "gender": "homme",
    "concentration": "EDT",
    "volume": "100ml",
    "price": 6900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/ralph-lauren-polo-green.jpg",
    "shortDescription": "Polo Green de Ralph Lauren est l'original, le classique fondateur de toute la gamme Polo. Un fougère-chypré vert et musqué qui incarne l'Amérique libre et nature depuis 1978.",
    "description": "Ralph Lauren Polo Green est bien plus qu'un parfum — c'est un monument olfactif américain. Lancé en 1978, il a défini pendant des décennies ce que devait sentir l'homme sportif, libre et connecté à la nature. Ce parfum a inspiré des générations entières de créateurs et reste aujourd'hui une référence incontournable pour qui s'intéresse à l'histoire de la parfumerie masculine.\n\nLa composition est un fougère-chypré vert d'une générosité rare. L'ouverture est un éclat de basilic, sauge, genièvre et pin maritime qui évoque immédiatement les grands espaces. Le cœur déploie une palette aromatique complexe : géranium, jasmin, rose de mai et vétiver dans un accord charnu et naturel. Le fond apporte une profondeur chypré-boisée avec l'oakmoss (mousse de chêne), le patchouli et le musc qui ancrent ce parfum dans la durée.\n\nPolo Green est le parfum de l'homme qui aime les grands espaces, la nature et le sport. Bien que classique, sa sophistication olfactive le rend agréable à porter dans de nombreuses occasions. Un must-have pour tout amateur sérieux de parfumerie masculine.\n\nMaison Numidia vous garantit un flacon authentique livré COD dans les 58 wilayas d'Algérie via Yalidine.",
    "notes": {
      "top": ["Basilic", "Sauge", "Genièvre", "Pin"],
      "heart": ["Géranium", "Jasmin", "Rose de mai", "Vétiver"],
      "base": ["Mousse de chêne", "Patchouli", "Musc"]
    },
    "family": "Fougère Chypré",
    "occasions": ["Plein air", "Casual", "Week-end"],
    "seasons": ["Printemps", "Été", "Automne"],
    "longevity": 4,
    "sillage": 4,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["polo-blue-ralph-lauren", "polo-black-ralph-lauren", "azzaro-chrome"]
  },
  {
    "id": "escada-magnetism",
    "slug": "escada-magnetism",
    "h1": "Escada Magnetism Parfum Femme Algérie",
    "name": "Magnetism",
    "brand": "Escada",
    "brandSlug": "escada",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "EDP",
    "volume": "75ml",
    "price": 5900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/escada-magnetism.jpg",
    "shortDescription": "Magnetism d'Escada est un oriental floral magnétique qui capture l'irrésistible attraction féminine. Rose, santal et patchouli dans une composition chaude et enveloppante.",
    "description": "Escada Magnetism est une fragrance féminine qui porte bien son nom : dès la première application, elle exerce une attraction irrésistible. Créée par la maison allemande Escada, elle représente l'un des parfums les plus aboutis de la gamme, alliant générosité florale et profondeur orientale dans une composition mémorable.\n\nL'ouverture est une explosion fruitée-florale de bergamote, mandarine et pruneaux qui captive immédiatement l'attention. Le cœur déploie un bouquet floral opulent dominé par la rose de mai, le jasmin et l'ylang-ylang dans une générosité typiquement Escada. La base révèle progressivement un accord oriental sophistiqué de bois de santal, patchouli, ambre et musc qui confère à Magnetism sa dimension sensuelle et sa longévité remarquable.\n\nCette fragrance s'adresse aux femmes qui aiment les parfums qui ne passent pas inaperçus. Son sillage enveloppant accompagne parfaitement les soirées et les occasions spéciales, tout en restant suffisamment équilibré pour les journées au bureau.\n\nDisponible chez Maison Numidia avec livraison COD dans les 58 wilayas d'Algérie. Un choix audacieux pour la femme algérienne qui aime exprimer sa féminité avec force et élégance.",
    "notes": {
      "top": ["Bergamote", "Mandarine", "Pruneaux"],
      "heart": ["Rose de mai", "Jasmin", "Ylang-ylang"],
      "base": ["Bois de santal", "Patchouli", "Ambre", "Musc"]
    },
    "family": "Oriental Floral",
    "occasions": ["Soirée", "Dîner", "Événement"],
    "seasons": ["Automne", "Hiver"],
    "longevity": 4,
    "sillage": 4,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["escada-joyful", "lalique-amour", "bvlgari-goldea"]
  },
  {
    "id": "escada-joyful",
    "slug": "escada-joyful",
    "h1": "Escada Joyful Parfum Femme Algérie",
    "name": "Joyful",
    "brand": "Escada",
    "brandSlug": "escada",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "EDP",
    "volume": "75ml",
    "price": 5500,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/escada-joyful.jpg",
    "shortDescription": "Escada Joyful est un floral fruité solaire qui incarne la bonne humeur et la légèreté. Litchi, freesia et bois de santal dans une composition pétillante et addictive.",
    "description": "Escada Joyful est le parfum de la femme qui aborde la vie avec optimisme et légèreté. La maison Escada, connue pour ses collections colorées et festives, a réussi avec Joyful à capturer en flacon l'essence même de la joie de vivre et du plaisir des petits moments du quotidien.\n\nLa fragrance s'ouvre sur une vague fruitée et pétillante de litchi, mangue et pamplemousse qui met instantanément de bonne humeur. Le cœur s'épanouit en un bouquet floral de freesia, pivoine et jasmin — léger, délicat et solaire à la fois. La base douce de bois de santal, musc blanc et ambre vanillé apporte la chaleur et la persistance nécessaires pour que la fragrance reste mémorable toute la journée.\n\nJoyful est idéal pour les journées de printemps et d'été en Algérie, lorsque la chaleur amplifie les notes fruitées et florales de manière magnifique. Sa légèreté et sa fraîcheur en font aussi un choix pertinent pour les femmes qui préfèrent les parfums discrets et non envahissants.\n\nMaison Numidia livre ce parfum authentique dans toutes les 58 wilayas d'Algérie avec paiement à la réception.",
    "notes": {
      "top": ["Litchi", "Mangue", "Pamplemousse"],
      "heart": ["Freesia", "Pivoine", "Jasmin"],
      "base": ["Bois de santal", "Musc blanc", "Ambre vanillé"]
    },
    "family": "Floral Fruité",
    "occasions": ["Journée", "Week-end", "Printemps"],
    "seasons": ["Printemps", "Été"],
    "longevity": 3,
    "sillage": 3,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["escada-magnetism", "dolce-gabbana-light-blue", "chloe-love-story"]
  },
  {
    "id": "rochas-byzance",
    "slug": "rochas-byzance",
    "h1": "Rochas Byzance Parfum Femme Algérie",
    "name": "Byzance",
    "brand": "Rochas",
    "brandSlug": "rochas",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "EDP",
    "volume": "90ml",
    "price": 6500,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/rochas-byzance.jpg",
    "shortDescription": "Byzance de Rochas est un oriental floral somptueux inspiré des palais byzantins. Rose turque, ylang-ylang et ambre dans une composition majestueuse et enveloppante.",
    "description": "Rochas Byzance est une fragrance féminine qui transporte vers les fastes de l'Empire byzantin, ses palais ornés de mosaïques dorées et ses étoffes précieuses. Créée pour la femme qui aime les parfums qui ont de la présence et de l'histoire, Byzance est l'une des créations les plus nobles de la maison Rochas.\n\nLa composition s'ouvre sur une envolée de bergamote et d'aldéhydes qui donnent un caractère aérien à cette fragrance pourtant profonde. Le cœur est un bouquet floral oriental d'exception : rose de Turquie, ylang-ylang crémeux et jasmin dans une générosité théâtrale. C'est au niveau du fond que Byzance révèle sa véritable nature : ambre chaud, bois de santal, cèdre et musc se fondent dans un accord oriental profond et persistant qui peut durer toute une journée.\n\nByzance est la fragrance de la femme qui n'a pas peur d'être remarquée. Son sillage enveloppant et sa longévité remarquable en font un choix idéal pour les soirées formelles, les dîners et les occasions où l'on veut marquer les esprits.\n\nDisponible chez Maison Numidia avec livraison COD dans les 58 wilayas d'Algérie. Un parfum de caractère pour une femme qui sait ce qu'elle veut.",
    "notes": {
      "top": ["Bergamote", "Aldéhydes", "Citron"],
      "heart": ["Rose de Turquie", "Ylang-ylang", "Jasmin"],
      "base": ["Ambre", "Bois de santal", "Cèdre", "Musc"]
    },
    "family": "Oriental Floral",
    "occasions": ["Soirée", "Dîner", "Occasions spéciales"],
    "seasons": ["Automne", "Hiver"],
    "longevity": 4,
    "sillage": 4,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["escada-magnetism", "guerlain-l-heure-bleue", "cacharel-anais-anais"]
  }
];

const allSlugs = new Set([...existingSlugs, ...newProducts.map(p => p.slug)]);
let errors = 0;
for (const p of newProducts) {
  if (existingSlugs.has(p.slug)) { console.error(`DUPLICATE: ${p.slug}`); errors++; }
  for (const r of p.related) {
    if (!allSlugs.has(r)) { console.error(`MISSING related "${r}" in ${p.slug}`); errors++; }
  }
}
if (errors > 0) { console.error(`${errors} erreur(s) — abandon`); process.exit(1); }

data.products.push(...newProducts);
writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf8');
console.log(`✅ ${newProducts.length} produits ajoutés — total: ${data.products.length} produits`);
