import { readFileSync, writeFileSync } from 'fs';

const filePath = 'data/products.json';
const data = JSON.parse(readFileSync(filePath, 'utf8'));

const existingSlugs = new Set(data.products.map(p => p.slug));

const newProducts = [
  {
    id: "dolce-gabbana-the-one-gentleman",
    slug: "dolce-gabbana-the-one-gentleman",
    h1: "Dolce&Gabbana The One Gentleman Parfum Homme Algérie",
    name: "The One Gentleman",
    brand: "Dolce&Gabbana",
    brandSlug: "dolce-gabbana",
    category: "parfums-homme",
    gender: "homme",
    concentration: "EDT",
    volume: "100ml",
    price: 9500,
    originalPrice: null,
    badge: null,
    image: "/images/products/dolce-gabbana-the-one-gentleman.jpg",
    shortDescription: "Dolce&Gabbana The One Gentleman est un EDT masculin plus raffiné et élégant que l'original The One. Un parfum pour le gentleman italien moderne: séduisant, distingué et infiniment classe.",
    description: "Dolce&Gabbana The One Gentleman est une interprétation plus légère et plus quotidienne du mythique The One, apportant à la collection une dimension de gentillesse et d'élégance décontractée. Là où The One original est intense et oriental, Gentleman adopte un registre plus frais et plus accessible, pour l'homme qui veut l'élégance méditerranéenne au quotidien. Cet Eau de Toilette masculin s'ouvre sur des notes fraîches et aromatiques: le citron de Sicile et le basilic créent une première impression fraîche et ensoleillée qui évoque les jardins d'Italie du Sud. Le cœur est aromatique et légèrement épicé: le thym et la rose créent un accord floral-herbal d'une originalité et d'une fraîcheur remarquables pour un parfum masculin. La base est boisée et ambrée: le tabac léger et l'ambre créent un fond chaleureux et masculin qui prolonge agréablement cette fragrance. The One Gentleman est le parfum de l'homme moderne qui allie sport et élégance naturellement. En Algérie, The One est très populaire et Gentleman en est la version quotidienne parfaite. Livraison dans les 58 wilayas, paiement à la réception.",
    notes: { top: ["Citron de Sicile", "Basilic", "Bergamote"], heart: ["Thym", "Rose", "Géranium"], base: ["Tabac Léger", "Ambre", "Cèdre"] },
    family: "Aromatique Fougère",
    occasions: ["Bureau", "Quotidien", "Soirée"],
    seasons: ["Toutes saisons"],
    longevity: 4,
    sillage: 3,
    inStock: true,
    featured: false,
    isOriental: false,
    related: ["dolce-gabbana-the-one", "dolce-gabbana-intenso", "dolce-gabbana-k"]
  },
  {
    id: "guerlain-mon-guerlain-bloom-of-rose",
    slug: "guerlain-mon-guerlain-bloom-of-rose",
    h1: "Guerlain Mon Guerlain Bloom of Rose Algérie",
    name: "Mon Guerlain Bloom of Rose",
    brand: "Guerlain",
    brandSlug: "guerlain",
    category: "parfums-femme",
    gender: "femme",
    concentration: "EDP",
    volume: "100ml",
    price: 14500,
    originalPrice: null,
    badge: null,
    image: "/images/products/guerlain-mon-guerlain-bloom-of-rose.jpg",
    shortDescription: "Guerlain Mon Guerlain Bloom of Rose est la version florale et rosée de Mon Guerlain. Un EDP féminin lavande et rose d'une douceur printanière, pour la femme qui exprime sa féminité avec légèreté.",
    description: "Guerlain Mon Guerlain Bloom of Rose est l'interprétation la plus florale et la plus romantique de Mon Guerlain, la fragrance signature de la maison Guerlain. Là où l'original est centré sur la lavande et la vanille, Bloom of Rose déplace l'accent vers la rose, créant une version plus florale et plus printanière du parfum. Cet Eau de Parfum féminin s'ouvre sur une alliance fraîche entre la lavande Crispy et la bergamote: une entrée en matière lumineuse et aromatique qui rappelle immédiatement Mon Guerlain tout en annonçant son côté fleuri. Le cœur est une célébration de la rose associée à la lavande: ces deux matières premières nobles s'entremêlent dans un accord floral-aromatique d'une beauté et d'une originalité remarquables. La base reste fidèle à Mon Guerlain: la vanille de Tahiti crémeuse et le musc blanc créent un fond doux et persistant qui ancre cette version florale dans l'univers olfactif de la maison. Bloom of Rose est parfait pour les femmes qui aiment Mon Guerlain mais qui cherchent une version plus florale et plus printanière. En Algérie, Mon Guerlain est l'une des fragrances féminines les plus populaires. Livraison dans les 58 wilayas, paiement à la réception.",
    notes: { top: ["Lavande Crispy", "Bergamote", "Rose Fraîche"], heart: ["Rose de Centifolia", "Lavande Absolue", "Jasmin"], base: ["Vanille de Tahiti", "Musc Blanc", "Fève Tonka"] },
    family: "Floral Aromatique",
    occasions: ["Bureau", "Quotidien", "Printemps"],
    seasons: ["Printemps", "Été"],
    longevity: 5,
    sillage: 3,
    inStock: true,
    featured: false,
    isOriental: false,
    related: ["guerlain-mon-guerlain", "guerlain-mon-guerlain-sparkling-bouquet", "guerlain-aqua-allegoria"]
  },
  {
    id: "lancome-idole-now",
    slug: "lancome-idole-now",
    h1: "Lancôme Idôle Now Parfum Femme Algérie",
    name: "Idôle Now",
    brand: "Lancôme",
    brandSlug: "lancome",
    category: "parfums-femme",
    gender: "femme",
    concentration: "EDP",
    volume: "75ml",
    price: 12900,
    originalPrice: null,
    badge: null,
    image: "/images/products/lancome-idole-now.jpg",
    shortDescription: "Lancôme Idôle Now est la version florale intense d'Idôle. Un EDP féminin floral et boisé pour la femme du moment, active, engagée et résolument tournée vers l'avenir.",
    description: "Lancôme Idôle Now est une évolution d'Idôle, la fragrance féminine de Lancôme qui célèbre la femme engagée et tournée vers l'avenir. Now explore une dimension plus intense et plus affirmée, pour la femme qui agit maintenant plutôt que de remettre à demain. Cet Eau de Parfum féminin s'ouvre sur une bergamote plus intense et des notes florales qui créent une première impression dynamique et confiante. Le cœur floral est plus riche que dans l'original: le jasmin et la rose s'expriment avec une générosité supplémentaire, créant un accord floral d'une beauté affirmée. La base boisée est plus profonde: le patchouli et le vétiver créent un fond terreux et persistant qui ancre cette fragrance dans un registre résolument contemporain et affirmé. Idôle Now est le parfum de la femme qui prend les choses en main, qui décide et qui agit. En Algérie, Lancôme Idôle est une fragrance populaire et Now en est la version plus affirmée. Livraison dans les 58 wilayas, paiement à la réception.",
    notes: { top: ["Bergamote Intense", "Mandarine", "Rose"], heart: ["Jasmin", "Rose Centifolia", "Pivoine"], base: ["Patchouli", "Vétiver", "Musc Blanc"] },
    family: "Floral Boisé",
    occasions: ["Bureau", "Quotidien", "Soirée"],
    seasons: ["Toutes saisons"],
    longevity: 5,
    sillage: 4,
    inStock: true,
    featured: false,
    isOriental: false,
    related: ["idole-lancome", "idole-aura-lancome", "tresor-lancome"]
  },
  {
    id: "ysl-mon-paris-couture",
    slug: "ysl-mon-paris-couture",
    h1: "YSL Mon Paris Couture Parfum Femme Algérie",
    name: "Mon Paris Couture",
    brand: "YSL",
    brandSlug: "ysl",
    category: "parfums-femme",
    gender: "femme",
    concentration: "EDP",
    volume: "90ml",
    price: 14900,
    originalPrice: null,
    badge: null,
    image: "/images/products/ysl-mon-paris-couture.jpg",
    shortDescription: "YSL Mon Paris Couture est la version haute couture et florale de Mon Paris. Un EDP féminin floral luxueux et romantique, pour la femme qui voit Paris comme la capitale de l'amour absolu.",
    description: "Yves Saint Laurent Mon Paris Couture est l'expression haute couture de Mon Paris, la fragrance romantique qui célèbre Paris, ville de l'amour par excellence. Cette version Couture explore une dimension plus luxueuse et plus florale, pour les femmes qui veulent vivre Paris dans ce qu'elle a de plus opulent. Cet Eau de Parfum féminin s'ouvre sur une alliance fraîche et fruitée entre la fraise des bois et le citron: une entrée en matière plus fruitée et plus gourmande que l'original. Le cœur floral Couture est somptueux: la pivoine et la rose créent un accord floral généreux et romantique d'une beauté et d'une richesse dignes de la haute couture parisienne. La base est chaude et enveloppante: la fève tonka et le patchouli créent un fond ambré-patchoulie qui donne à cette version sa profondeur et sa persistance supérieures. Mon Paris Couture est le parfum de la femme qui a le coeur romantique et qui vit l'amour avec passion et générosité. En Algérie, Mon Paris YSL est très populaire et Couture en est la version premium. Livraison dans les 58 wilayas, paiement à la réception.",
    notes: { top: ["Fraise des Bois", "Citron", "Framboise"], heart: ["Pivoine", "Rose", "Jasmin"], base: ["Fève Tonka", "Patchouli", "Musc"] },
    family: "Floral Fruité",
    occasions: ["Soirée", "Mariage", "Occasion spéciale"],
    seasons: ["Printemps", "Automne"],
    longevity: 5,
    sillage: 4,
    inStock: true,
    featured: false,
    isOriental: false,
    related: ["mon-paris-ysl", "libre-ysl", "ysl-y-femme"]
  },
  {
    id: "bvlgari-splendida-rose-rose",
    slug: "bvlgari-splendida-rose-rose",
    h1: "Bvlgari Splendida Rose Rose Parfum Femme Algérie",
    name: "Splendida Rose Rose",
    brand: "Bvlgari",
    brandSlug: "bvlgari",
    category: "parfums-femme",
    gender: "femme",
    concentration: "EDP",
    volume: "100ml",
    price: 12500,
    originalPrice: null,
    badge: null,
    image: "/images/products/bvlgari-splendida-rose-rose.jpg",
    shortDescription: "Bvlgari Splendida Rose Rose est un EDP féminin dédié à la double rose — un hymne absolu à la fleur-reine de la parfumerie selon Bvlgari. Romantique, opulent et d'une beauté italienne irréprochable.",
    description: "Bvlgari Splendida Rose Rose est l'expression la plus romantique et la plus florale de la collection Splendida, une ode à la rose déclinée dans sa double beauté: la rose fraîche du jardin et la rose absolue de la haute parfumerie. Cet Eau de Parfum féminin est une composition entièrement dédiée à la reine des fleurs, présentée avec la générosité et le savoir-faire de la maison Bvlgari. L'ouverture est une explosion de rose fraîche: la rose turque et la bergamote créent une première impression florale d'une fraîcheur et d'une beauté saisissantes. Le cœur est la révélation: la rose centifolia et la rose de Damas s'expriment ensemble dans un accord floral d'une richesse et d'une complexité dignes d'une maison de joaillerie. La base est enveloppante et féminine: le musc blanc et le bois de cèdre créent un fond délicat qui laisse la rose s'exprimer pleinement sans l'alourdir. Rose Rose est le parfum de la femme qui aime les fleurs dans toute leur beauté naturelle, celle qui ne cherche pas à compliquer ce qui est déjà parfait. En Algérie, Bvlgari est une marque de luxe très appréciée. Livraison dans les 58 wilayas, paiement à la réception.",
    notes: { top: ["Rose Turque", "Bergamote", "Litchi"], heart: ["Rose Centifolia", "Rose Damascène", "Jasmin"], base: ["Musc Blanc", "Cèdre", "Ambre Doux"] },
    family: "Floral Rose",
    occasions: ["Mariage", "Occasion spéciale", "Printemps"],
    seasons: ["Printemps", "Été"],
    longevity: 4,
    sillage: 3,
    inStock: true,
    featured: false,
    isOriental: false,
    related: ["bvlgari-splendida-magnolia", "bvlgari-rose-essentielle", "bvlgari-pour-femme"]
  },
  {
    id: "lattafa-velvet-oud",
    slug: "lattafa-velvet-oud",
    h1: "Lattafa Velvet Oud Parfum Oriental Algérie",
    name: "Velvet Oud",
    brand: "Lattafa",
    brandSlug: "lattafa",
    category: "parfums-orientaux",
    gender: "unisexe",
    concentration: "EDP",
    volume: "100ml",
    price: 3500,
    originalPrice: null,
    badge: null,
    image: "/images/products/lattafa-velvet-oud.jpg",
    shortDescription: "Lattafa Velvet Oud est un EDP oriental unisexe au oud velouté et enveloppant. Un parfum arabe de luxe accessible qui marie la douceur du velours à la profondeur du oud précieux.",
    description: "Lattafa Velvet Oud est une fragrance orientale unisexe qui associe deux concepts apparemment opposés — la douceur veloutée et la profondeur du oud — pour créer quelque chose d'unique et d'immédiatement séduisant. Cet Eau de Parfum oriental est une composition généreuse et accessible qui apporte le luxe de la parfumerie du Golfe dans un format quotidien. L'ouverture est chaleureuse et douce: des notes de vanille crémeuse et d'épices légères créent une entrée en matière veloutée et enveloppante qui annonce la richesse orientale qui suit. Le cœur est dominé par le oud: un oud boisé d'une douceur inhabituelle, traité pour révéler ses facettes les plus séduisantes sans l'agressivité parfois associée à cette matière première. La base est profonde et persistante: l'ambre et le musc oriental créent un fond chaud et enveloppant qui s'exprime magnifiquement pendant de nombreuses heures. Velvet Oud est le parfum oriental par excellence pour ceux qui veulent s'initier au oud dans une version douce et accessible. En Algérie, Lattafa est une marque très populaire pour ses parfums orientaux de qualité à prix abordable. Livraison dans les 58 wilayas, paiement à la réception.",
    notes: { top: ["Vanille Crémeuse", "Épices Douces", "Bergamote"], heart: ["Oud Velouté", "Rose Orientale", "Santal"], base: ["Ambre", "Musc Oriental", "Patchouli"] },
    family: "Oriental Oudé",
    occasions: ["Soirée", "Mariage", "Quotidien"],
    seasons: ["Automne", "Hiver"],
    longevity: 5,
    sillage: 4,
    inStock: true,
    featured: false,
    isOriental: true,
    related: ["lattafa-oud-for-glory", "lattafa-khamrah", "lattafa-oud-mood"]
  },
  {
    id: "al-haramain-amber-oud-tobacco",
    slug: "al-haramain-amber-oud-tobacco",
    h1: "Al Haramain Amber Oud Tobacco Edition Algérie",
    name: "Amber Oud Tobacco Edition",
    brand: "Al Haramain",
    brandSlug: "al-haramain",
    category: "parfums-orientaux",
    gender: "unisexe",
    concentration: "EDP",
    volume: "60ml",
    price: 6500,
    originalPrice: null,
    badge: null,
    image: "/images/products/al-haramain-amber-oud-tobacco.jpg",
    shortDescription: "Al Haramain Amber Oud Tobacco Edition est un EDP oriental unisexe riche en tabac et oud. Une fragrance du Golfe d'une complexité et d'une profondeur saisissantes pour les amateurs de parfums orientaux intenses.",
    description: "Al Haramain Amber Oud Tobacco Edition est une expression particulièrement audacieuse de la collection Amber Oud, incorporant le tabac comme note principale pour créer quelque chose de résolument différent de ce qui se fait habituellement dans la parfumerie orientale. Ce parfum oriental unisexe est une ode à la complexité: tabac, oud et ambre se combinent pour créer une fragrance d'une profondeur et d'une richesse absolument remarquables. L'ouverture est immédiatement distinctive: le tabac et des épices orientales créent une première impression chaude et légèrement sucrée qui est immédiatement différente de tout ce qu'on a senti auparavant. Le cœur est l'alliance qui définit ce parfum: le oud boisé et le tabac enveloppant créent un accord oriental fumé d'une complexité et d'une beauté saisissantes. La base est profonde et persistante: l'ambre et le musc oriental créent un fond opulent d'une persistance exceptionnelle. Al Haramain Amber Oud Tobacco Edition est pour les amateurs de parfums orientaux qui n'ont pas peur de l'intensité et qui cherchent quelque chose d'unique. En Algérie, Al Haramain est une référence en matière de parfums orientaux. Livraison dans les 58 wilayas, paiement à la réception.",
    notes: { top: ["Tabac", "Épices Orientales", "Cardamome"], heart: ["Oud Boisé", "Rose Orientale", "Safran"], base: ["Ambre", "Musc Oriental", "Vétiver"] },
    family: "Oriental Fumé",
    occasions: ["Soirée", "Cérémonie", "Hiver"],
    seasons: ["Automne", "Hiver"],
    longevity: 6,
    sillage: 5,
    inStock: true,
    featured: false,
    isOriental: true,
    related: ["al-haramain-amber-oud", "al-haramain-midnight-oud", "al-haramain-black-oudh"]
  },
  {
    id: "swiss-arabian-oud-wa-ward",
    slug: "swiss-arabian-oud-wa-ward",
    h1: "Swiss Arabian Oud Wa Ward Parfum Oriental Algérie",
    name: "Oud Wa Ward",
    brand: "Swiss Arabian",
    brandSlug: "swiss-arabian",
    category: "parfums-orientaux",
    gender: "unisexe",
    concentration: "EDP",
    volume: "50ml",
    price: 4500,
    originalPrice: null,
    badge: null,
    image: "/images/products/swiss-arabian-oud-wa-ward.jpg",
    shortDescription: "Swiss Arabian Oud Wa Ward — oud et rose en arabe — est un EDP oriental unisexe qui marie la profondeur du oud à la délicatesse de la rose de Taïf. Un parfum traditionnel du Golfe d'une beauté floral-orientale incomparable.",
    description: "Swiss Arabian Oud Wa Ward est une traduction olfactive de son nom arabe: oud wa ward signifie oud et rose, deux matières premières qui sont au cœur de la tradition parfumière arabe depuis des siècles. Cette Eau de Parfum orientale unisexe est une composition qui célèbre cet accord classique de la parfumerie arabe: le oud profond et boisé rencontrant la rose délicate et fleurie pour créer quelque chose de magnifiquement équilibré. L'ouverture est florale et légèrement épicée: la rose de Taïf et le safran créent une première impression florale-épicée d'une beauté et d'une authenticité remarquables. Le cœur est l'alliance du oud et de la rose: ces deux matières premières s'expriment ensemble dans un accord floral-oriental d'une richesse et d'une profondeur qui évoquent les souks parfumés du Golfe. La base est chaude et persistante: l'ambre et le musc créent un fond oriental enveloppant qui prolonge magnifiquement ce beau mariage du oud et de la rose. Oud Wa Ward est le parfum de ceux qui comprennent et apprécient la parfumerie arabe traditionnelle dans toute sa beauté. En Algérie, Swiss Arabian est très apprécié pour ses parfums orientaux authentiques. Livraison dans les 58 wilayas, paiement à la réception.",
    notes: { top: ["Rose de Taïf", "Safran", "Bergamote"], heart: ["Oud Arabe", "Rose Absolue", "Jasmin"], base: ["Ambre", "Musc", "Santal"] },
    family: "Oriental Floral",
    occasions: ["Mariage", "Cérémonie", "Soirée"],
    seasons: ["Toutes saisons"],
    longevity: 5,
    sillage: 4,
    inStock: true,
    featured: false,
    isOriental: true,
    related: ["swiss-arabian-shaghaf-oud", "swiss-arabian-jannat-ul-firdaus", "swiss-arabian-mukhalat-malaki"]
  },
  {
    id: "azzaro-chrome-parfum",
    slug: "azzaro-chrome-parfum",
    h1: "Azzaro Chrome Parfum Homme Algérie",
    name: "Chrome Le Parfum",
    brand: "Azzaro",
    brandSlug: "azzaro",
    category: "parfums-homme",
    gender: "homme",
    concentration: "Parfum",
    volume: "100ml",
    price: 9900,
    originalPrice: null,
    badge: null,
    image: "/images/products/azzaro-chrome-parfum.jpg",
    shortDescription: "Azzaro Chrome Le Parfum est la concentration Parfum ultime de Chrome. Un masculin aquatique boisé d'une intensité et d'une persistance exceptionnelles, pour l'homme qui veut Chrome à son maximum.",
    description: "Azzaro Chrome Le Parfum représente l'expression la plus intense et la plus concentrée de Chrome, la fragrance masculine aquatique qui a fait la renommée d'Azzaro dans les années 90 et qui reste une référence du genre. Cette concentration Parfum prend tout ce qui rend Chrome irrésistible et l'amplifie: plus de fraîcheur marine, plus de profondeur boisée et une persistance absolument remarquable. L'ouverture est une explosion d'intensité marine: l'accord aquatique concentré et les agrumes créent une première impression de fraîcheur et de puissance qui dépasse de loin les versions EDT et EDP. Le cœur boisé et aquatique est la révélation de cette concentration: le cèdre et le vétiver s'expriment avec une richesse et une profondeur rarement atteintes dans les fragrances aquatiques. La base est profonde et persistante: les muscs blancs et l'ambre marin créent un fond d'une persistance de 12 à 14 heures, transformant Chrome en une fragrance de connaisseurs. Chrome Le Parfum est le choix des amateurs de Chrome qui veulent la version ultime, celle qui tient toute la journée sans nécessité de réapplication. En Algérie, Chrome est une marque très populaire. Livraison dans les 58 wilayas, paiement à la réception.",
    notes: { top: ["Accord Aquatique Concentré", "Bergamote Intense", "Agrumes Nobles"], heart: ["Cèdre", "Vétiver", "Lavande"], base: ["Musc Blanc Profond", "Ambre Marin", "Bois de Santal"] },
    family: "Aquatique Boisé",
    occasions: ["Bureau", "Quotidien", "Soirée"],
    seasons: ["Toutes saisons"],
    longevity: 6,
    sillage: 4,
    inStock: true,
    featured: false,
    isOriental: false,
    related: ["azzaro-chrome", "azzaro-chrome-intense", "azzaro-chrome-cologne"]
  },
  {
    id: "givenchy-l-homme-liberte",
    slug: "givenchy-l-homme-liberte",
    h1: "Givenchy L'Homme Liberté Parfum Algérie",
    name: "L'Homme Liberté",
    brand: "Givenchy",
    brandSlug: "givenchy",
    category: "parfums-homme",
    gender: "homme",
    concentration: "EDP",
    volume: "100ml",
    price: 12500,
    originalPrice: null,
    badge: null,
    image: "/images/products/givenchy-l-homme-liberte.jpg",
    shortDescription: "Givenchy L'Homme Liberté est un EDP masculin floral et épicé pour l'homme libre. Une fragrance moderne qui revendique l'indépendance et l'authenticité comme valeurs suprêmes de la masculinité.",
    description: "Givenchy L'Homme Liberté est une déclaration d'indépendance olfactive, une fragrance masculine créée pour l'homme qui vit selon ses propres règles et qui refuse de se conformer aux attentes des autres. Cet Eau de Parfum masculin est une composition ambitieuse qui explore de nouveaux territoires olfactifs pour la maison Givenchy. L'ouverture est fraîche et légèrement épicée: la bergamote et le gingembre créent une entrée en matière dynamique et masculine qui donne le ton de cette fragrance libre. Le cœur est floral et légèrement boisé: l'iris et le géranium créent un accord floral-boisé masculin d'une sophistication et d'une originalité remarquables. La base est profonde et affirmée: le patchouli et le vétiver créent un fond terreux et masculin qui donne à L'Homme Liberté son caractère et sa persistance. L'Homme Liberté est le parfum de l'homme qui exprime sa masculinité à sa façon, sans compromis ni contraintes. En Algérie, Givenchy est une maison de prestige très appréciée. Livraison dans les 58 wilayas, paiement à la réception.",
    notes: { top: ["Bergamote", "Gingembre", "Citron"], heart: ["Iris", "Géranium", "Épices"], base: ["Patchouli", "Vétiver", "Cèdre"] },
    family: "Floral Boisé",
    occasions: ["Bureau", "Soirée", "Quotidien"],
    seasons: ["Toutes saisons"],
    longevity: 5,
    sillage: 4,
    inStock: true,
    featured: false,
    isOriental: false,
    related: ["givenchy-gentleman", "givenchy-gentleman-society", "givenchy-blue-label"]
  },
  {
    id: "nina-ricci-coeur-joie",
    slug: "nina-ricci-coeur-joie",
    h1: "Nina Ricci Coeur Joie Parfum Femme Algérie",
    name: "Coeur Joie",
    brand: "Nina Ricci",
    brandSlug: "nina-ricci",
    category: "parfums-femme",
    gender: "femme",
    concentration: "EDP",
    volume: "100ml",
    price: 8500,
    originalPrice: null,
    badge: null,
    image: "/images/products/nina-ricci-coeur-joie.jpg",
    shortDescription: "Nina Ricci Coeur Joie est un EDP féminin floral romantique qui chante la joie du cœur. Un parfum de bonheur et d'optimisme signé Nina Ricci, pour la femme qui célèbre la vie avec enthousiasme.",
    description: "Nina Ricci Coeur Joie est une fragrance féminine qui porte en elle toute la joie de vivre et le romantisme de la maison Nina Ricci, célèbre pour ses créations délicatement féminines et profondément romantiques. Ce parfum est une célébration du bonheur simple et de la légèreté du cœur amoureux de la vie. Cet Eau de Parfum féminin s'ouvre sur des notes florales et légèrement fruitées: la rose fraîche et la bergamote créent une première impression lumineuse et romantique qui évoque immédiatement la joie d'un matin de printemps. Le cœur est une célébration florale: la pivoine et le muguet créent un accord floral romantique d'une délicatesse et d'une beauté typiquement Nina Ricci. La base est douce et enveloppante: la vanille et le musc blanc créent un fond doux et lumineux qui prolonge agréablement cette fragrance joyeuse. Coeur Joie est le parfum des femmes heureuses qui veulent partager leur joie avec le monde. En Algérie, Nina Ricci est une marque très appréciée pour ses fragrances féminines romantiques. Livraison dans les 58 wilayas, paiement à la réception.",
    notes: { top: ["Rose Fraîche", "Bergamote", "Framboise"], heart: ["Pivoine", "Muguet", "Jasmin"], base: ["Vanille", "Musc Blanc", "Bois Léger"] },
    family: "Floral Fruité",
    occasions: ["Quotidien", "Printemps", "Bureau"],
    seasons: ["Printemps", "Été"],
    longevity: 4,
    sillage: 3,
    inStock: true,
    featured: false,
    isOriental: false,
    related: ["nina-ricci-l-air-du-temps", "nina-ricci-nina", "nina-ricci-bellissima"]
  },
  {
    id: "kenzo-homme",
    slug: "kenzo-homme",
    h1: "Kenzo Homme Parfum Algérie",
    name: "Kenzo Homme",
    brand: "Kenzo",
    brandSlug: "kenzo",
    category: "parfums-homme",
    gender: "homme",
    concentration: "EDT",
    volume: "100ml",
    price: 8500,
    originalPrice: null,
    badge: null,
    image: "/images/products/kenzo-homme.jpg",
    shortDescription: "Kenzo Homme est l'EDT masculin originel de la maison Kenzo, lancé en 1991. Un parfum boisé et marin intemporel, pour l'homme en harmonie avec la nature — japonais dans son âme, universel dans sa beauté.",
    description: "Kenzo Homme est la première fragrance masculine créée par la maison Kenzo, lancée en 1991 et depuis lors l'un des parfums masculins les plus respectés de sa génération. Cette fragrance incarne la philosophie de la maison Kenzo: une rencontre entre l'esthétique japonaise — épurée, naturelle et en harmonie avec les éléments — et la modernité de la mode internationale. L'ouverture de Kenzo Homme est unique en son genre: le jasmin qui s'ouvre sur des notes marines légèrement iodées crée une juxtaposition poétique inattendue entre fleur et mer. Le cœur est boisé et naturel: le cèdre et les notes de feuilles créent un accord boisé-végétal d'une fraîcheur et d'une naturalité remarquables. La base est terreux et boisée: le vétiver et le musc créent un fond boisé persistant qui ancre cette fragrance dans un registre résolument masculin et naturel. Kenzo Homme est le parfum de l'homme sensible à la beauté de la nature, celui qui trouve l'équilibre entre force et douceur. En Algérie, Kenzo est une marque appréciée pour ses fragrances originales. Livraison dans les 58 wilayas, paiement à la réception.",
    notes: { top: ["Jasmin", "Notes Marines", "Bergamote"], heart: ["Cèdre", "Feuilles Vertes", "Lavande"], base: ["Vétiver", "Musc", "Bois de Santal"] },
    family: "Boisé Aquatique",
    occasions: ["Bureau", "Quotidien", "Nature"],
    seasons: ["Printemps", "Été", "Automne"],
    longevity: 4,
    sillage: 3,
    inStock: true,
    featured: false,
    isOriental: false,
    related: ["kenzo-l-eau-homme", "kenzo-pour-homme", "davidoff-cool-water-homme"]
  }
];

// Validate
const allSlugs = new Set([...existingSlugs, ...newProducts.map(p => p.slug)]);
let errors = 0;
for (const p of newProducts) {
  if (existingSlugs.has(p.slug)) { console.error(`DUPLICATE: ${p.slug}`); errors++; }
  for (const r of p.related) {
    if (!allSlugs.has(r)) { console.error(`MISSING related "${r}" in ${p.slug}`); errors++; }
  }
}
if (errors > 0) { console.error(`${errors} erreur(s) — abandon`); process.exit(1); }

data.products.push(...newProducts);
writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf8');
console.log(`✅ ${newProducts.length} produits ajoutés — total: ${data.products.length} produits`);
