import { readFileSync, writeFileSync } from 'fs';

const filePath = 'data/products.json';
const data = JSON.parse(readFileSync(filePath, 'utf8'));
const existingSlugs = new Set(data.products.map(p => p.slug));

const newProducts = [
  {
    "id": "kilian-love-dont-be-shy",
    "slug": "kilian-love-dont-be-shy",
    "h1": "By Kilian Love Don't Be Shy Parfum Algérie",
    "name": "Love, Don't Be Shy",
    "brand": "By Kilian",
    "brandSlug": "kilian",
    "category": "parfums-femme",
    "gender": "unisexe",
    "concentration": "EDP",
    "volume": "50ml",
    "price": 21900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/kilian-love-dont-be-shy.jpg",
    "shortDescription": "By Kilian Love Don't Be Shy est un gourmand floral addictif et romantique. Néroli, fleur d'oranger et caramel miel dans une composition sensuelle et sucrée qui ne laisse personne indifférent.",
    "description": "By Kilian Love, Don't Be Shy est l'une des fragrances les plus célèbres et les plus copiées de la niche contemporaine. Créée par Calice Becker pour la maison By Kilian fondée par Kilian Hennessy, cette fragrance est devenue une référence absolue dans le registre gourmand-floral de luxe.\n\nSon concept est simple et irrésistible : la douceur du miel et du caramel habillée de fleur d'oranger et de néroli, comme un baiser sucré. L'ouverture est une explosion de néroli et bergamote qui apporte fraîcheur et luminosité. Le cœur est la pièce maîtresse : fleur d'oranger absolue et miel crémeux dans un accord floral-gourmand d'une séduction immédiate. La base de musc blanc, caramel et vanille est enveloppante et persistante, créant un sillage poudré et sucré qui invite au rapprochement.\n\nLove, Don't Be Shy est une invitation à l'amour et à la vulnérabilité romantique. Sa popularité sur les réseaux sociaux et dans la communauté parfumerie témoigne de son pouvoir de séduction universelle.\n\nMaison Numidia propose ce parfum By Kilian authentique avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Néroli", "Bergamote", "Zestes d'agrumes"],
      "heart": ["Fleur d'oranger absolue", "Miel", "Jasmin"],
      "base": ["Musc blanc", "Caramel", "Vanille"]
    },
    "family": "Gourmand Floral",
    "occasions": ["Soirée", "Romance", "Occasions spéciales"],
    "seasons": ["Printemps", "Automne", "Hiver"],
    "longevity": 5,
    "sillage": 4,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["kilian-angels-share", "viktor-rolf-bon-bon", "tom-ford-lost-cherry"]
  },
  {
    "id": "kilian-angels-share",
    "slug": "kilian-angels-share",
    "h1": "By Kilian Angels Share Parfum Algérie",
    "name": "Angels' Share",
    "brand": "By Kilian",
    "brandSlug": "kilian",
    "category": "parfums-homme",
    "gender": "unisexe",
    "concentration": "EDP",
    "volume": "50ml",
    "price": 21900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/kilian-angels-share.jpg",
    "shortDescription": "By Kilian Angels' Share est un gourmand boisé inspiré du cognac vieilli en fût de chêne. Calvados, muscade et bois de cèdre dans une composition luxueuse et addictive pour les connaisseurs.",
    "description": "By Kilian Angels' Share est un hommage olfactif à la tradition française des spiritueux de luxe. La Part des Anges — Angels' Share — désigne en œnologie la quantité d'alcool qui s'évapore à travers les tonneaux de bois lors du vieillissement des cognacs et armagnacs. C'est cette évaporation mystérieuse et précieuse que By Kilian a capturée dans ce parfum.\n\nLa composition est un gourmand boisé d'une sophistication remarquable. L'ouverture est immédiatement enivrante : calvados pomme, cannelle et muscade créent un accord spiritueux épicé qui évoque l'intérieur d'un chai en automne. Le cœur développe un bois de chêne ambré et vanillé, évocateur des tonneaux de vieillissement. La base est deep et persistante — bois de cèdre, fève tonka et un musc ambré — qui ancre la fragrance dans une longévité remarquable.\n\nAngels' Share est l'une des fragrances masculines niche les plus discutées et les plus appréciées des dernières années. Son originalité et sa qualité de matières premières en font un investissement olfactif qui se justifie pleinement.\n\nMaison Numidia propose ce parfum By Kilian authentique avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Calvados", "Cannelle", "Muscade"],
      "heart": ["Bois de chêne ambré", "Vanille chêne", "Amandes"],
      "base": ["Bois de cèdre", "Fève tonka", "Musc ambré"]
    },
    "family": "Gourmand Boisé",
    "occasions": ["Soirée", "Hiver", "Occasions spéciales"],
    "seasons": ["Automne", "Hiver"],
    "longevity": 5,
    "sillage": 4,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["kilian-love-dont-be-shy", "tobacco-vanille-tom-ford", "chopard-casmir"]
  },
  {
    "id": "initio-oud-for-greatness",
    "slug": "initio-oud-for-greatness",
    "h1": "Initio Oud for Greatness Parfum Algérie",
    "name": "Oud for Greatness",
    "brand": "Initio Parfums Privés",
    "brandSlug": "initio",
    "category": "parfums-orientaux",
    "gender": "unisexe",
    "concentration": "EDP",
    "volume": "90ml",
    "price": 23500,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/initio-oud-for-greatness.jpg",
    "shortDescription": "Initio Oud for Greatness est un oriental boisé de luxe absolu. Oud du Bangladesh, encens noir et santal dans une composition niche qui redéfinit la grandeur olfactive.",
    "description": "Initio Parfums Privés Oud for Greatness est une fragrance niche qui ne fait pas dans la demi-mesure. La maison française Initio, fondée en 2015, s'est spécialisée dans les fragrances qui explorent les effets psychologiques des molécules olfactives — une approche scientifique de la séduction par le parfum.\n\nOud for Greatness est leur proposition la plus ambitieuse : un oud de Bangladesh de la plus haute qualité, utilisé sans restriction dans une composition qui ne cherche pas à plaire à tous — elle cherche à marquer les esprits de ceux qui ont le courage de la porter. L'ouverture est directe et saisissante : oud noir fumé et encens de résine dans un accord immédiatement puissant. Le cœur développe un safran précieux et une amande douce qui apportent chaleur et profondeur. La base est monumentale — bois de santal, ambre gris et musc civet — d'une persistance qui peut durer plusieurs jours sur les vêtements.\n\nOud for Greatness est réservé aux véritables amateurs d'oud qui cherchent l'expérience maximale. Disponible chez Maison Numidia avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Oud noir du Bangladesh", "Encens noir", "Safran"],
      "heart": ["Amande douce", "Rose noire", "Bois de oud fumé"],
      "base": ["Bois de santal", "Ambre gris", "Musc civet"]
    },
    "family": "Oriental Oudé",
    "occasions": ["Soirée", "Occasions spéciales", "Hiver"],
    "seasons": ["Automne", "Hiver"],
    "longevity": 5,
    "sillage": 5,
    "inStock": true,
    "featured": false,
    "isOriental": true,
    "related": ["initio-side-effect", "amouage-interlude-man", "tom-ford-oud-wood"]
  },
  {
    "id": "initio-side-effect",
    "slug": "initio-side-effect",
    "h1": "Initio Side Effect Parfum Algérie",
    "name": "Side Effect",
    "brand": "Initio Parfums Privés",
    "brandSlug": "initio",
    "category": "parfums-homme",
    "gender": "unisexe",
    "concentration": "EDP",
    "volume": "90ml",
    "price": 21500,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/initio-side-effect.jpg",
    "shortDescription": "Initio Side Effect est un oriental vanillé addictif et magnétique. Rhum, vanille noire et musc animal dans une composition qui crée une dépendance olfactive immédiate.",
    "description": "Initio Parfums Privés Side Effect est construit autour d'un concept provocateur : la dépendance olfactive. La maison française, spécialisée dans l'étude des effets psycho-olfactifs des fragrances, a créé avec Side Effect un parfum qui joue délibérément sur les mécanismes de la récompense et de la séduction.\n\nLa composition est un oriental vanillé d'une générosité assumée. L'ouverture est un accord rhum-vanille immédiatement séduisant et légèrement capiteux. Le cœur développe une vanille noire bourbon d'une richesse et d'une créamosité rares, accompagnée d'une note de tabac blond et de jasmin. La base est un accord musc animal-ambre-myrrhe d'une persistance et d'une sensualité troublante.\n\nSide Effect est une fragrance qui se perçoit sur la peau comme une signature olfactive permanente — chaleureux, légèrement sucré, animal dans le bon sens du terme. Sa popularité mondiale témoigne de son efficacité dans la création d'attraction et de mémorabilité.\n\nMaison Numidia propose ce parfum Initio authentique avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Rhum", "Vanille fraîche", "Citrus doux"],
      "heart": ["Vanille noire Bourbon", "Tabac blond", "Jasmin"],
      "base": ["Musc animal", "Ambre", "Myrrhe"]
    },
    "family": "Oriental Gourmand",
    "occasions": ["Soirée", "Romance", "Hiver"],
    "seasons": ["Automne", "Hiver"],
    "longevity": 5,
    "sillage": 4,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["initio-oud-for-greatness", "baccarat-rouge-540", "creed-aventus"]
  },
  {
    "id": "amouage-dia-homme",
    "slug": "amouage-dia-homme",
    "h1": "Amouage Dia Homme Parfum Algérie",
    "name": "Dia pour Homme",
    "brand": "Amouage",
    "brandSlug": "amouage",
    "category": "parfums-homme",
    "gender": "homme",
    "concentration": "EDP",
    "volume": "100ml",
    "price": 22900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/amouage-dia-homme.jpg",
    "shortDescription": "Amouage Dia pour Homme est un floral aromatique divin et aérien. Bergamote, rose de Turquie et encens dans une composition masculine d'une élégance spirituelle unique.",
    "description": "Amouage Dia pour Homme — \"Dia\" signifiant \"divin\" en grec — est une fragrance masculine d'une beauté et d'une élégance rares. La maison omanaise Amouage, fondée en 1983 avec l'ambition de créer les parfums les plus précieux au monde, a réussi avec Dia un chef-d'oeuvre de parfumerie classique aux références orientales.\n\nLa composition est un floral aromatique d'une sophistication masculive. L'ouverture est fraîche et aromatique — bergamote de Calabre, sauge romaine et un accord épicé de cardamome. Le cœur se déploie autour d'un bouquet floral masculin d'une beauté inattendue : rose de Turquie, jasmin et héliotrope dans un accord fleuri qui transcende les genres. La base encensée et boisée — encens de l'Oman, bois d'ambre gris, cèdre — donne à Dia sa dimension spirituelle et sa persistance exceptionnelle.\n\nDia pour Homme est pour l'homme cultivé et ouvert d'esprit qui cherche une fragrance masculine hors des sentiers battus. Sa qualité de matières premières est sans équivalent dans sa gamme de prix.\n\nMaison Numidia propose ce parfum Amouage authentique avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Bergamote de Calabre", "Sauge romaine", "Cardamome"],
      "heart": ["Rose de Turquie", "Jasmin", "Héliotrope"],
      "base": ["Encens de l'Oman", "Ambre gris", "Cèdre"]
    },
    "family": "Floral Aromatique",
    "occasions": ["Bureau", "Soirée", "Occasions formelles"],
    "seasons": ["Printemps", "Automne"],
    "longevity": 5,
    "sillage": 4,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["amouage-interlude-man", "amouage-reflection", "amouage-beloved-homme"]
  },
  {
    "id": "amouage-lyric-femme",
    "slug": "amouage-lyric-femme",
    "h1": "Amouage Lyric Femme Parfum Algérie",
    "name": "Lyric pour Femme",
    "brand": "Amouage",
    "brandSlug": "amouage",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "EDP",
    "volume": "100ml",
    "price": 22900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/amouage-lyric-femme.jpg",
    "shortDescription": "Amouage Lyric pour Femme est un floral oriental somptueux et lyrique. Rose absolue, encens et musc en un opéra olfactif de la maison omanaise pour la femme de prestige.",
    "description": "Amouage Lyric pour Femme est une oeuvre lyrique au sens propre du terme — une composition olfactive qui raconte une histoire de beauté, d'amour et de profondeur orientale à travers ses notes. La maison Amouage, réputée pour ses créations qui n'hésitent pas à pousser les matières premières à leur maximum, a créé avec Lyric l'un de ses sommets féminins.\n\nLa composition s'ouvre sur une envolée de rose et de bergamote d'une générosité immédiate. Le cœur est un opéra floral : rose absolue de Bulgarie, magnolia et orchidée dans un accord floral d'une richesse et d'une complexité rarement atteintes. L'encens de Frankincense — myrrhe — apporte la dimension orientale et spirituelle caractéristique de la maison omanaise. La base de musc blanc, ambre et bois de santal crée une persistance qui peut se maintenir pendant vingt-quatre heures.\n\nLyric est pour la femme qui veut une fragrance de prestige absolue — un parfum qui témoigne d'une connaissance et d'une appréciation de la grande parfumerie.\n\nMaison Numidia propose ce parfum Amouage authentique avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Rose", "Bergamote", "Cardamome"],
      "heart": ["Rose absolue de Bulgarie", "Magnolia", "Orchidée", "Encens"],
      "base": ["Musc blanc", "Ambre gris", "Bois de santal"]
    },
    "family": "Floral Oriental",
    "occasions": ["Soirée", "Occasions spéciales", "Prestige"],
    "seasons": ["Automne", "Hiver", "Printemps"],
    "longevity": 5,
    "sillage": 5,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["amouage-reflection", "frederic-malle-portrait-of-a-lady", "byredo-gypsy-water"]
  },
  {
    "id": "amouage-beloved-homme",
    "slug": "amouage-beloved-homme",
    "h1": "Amouage Beloved Homme Parfum Algérie",
    "name": "Beloved pour Homme",
    "brand": "Amouage",
    "brandSlug": "amouage",
    "category": "parfums-homme",
    "gender": "homme",
    "concentration": "EDP",
    "volume": "100ml",
    "price": 22900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/amouage-beloved-homme.jpg",
    "shortDescription": "Amouage Beloved pour Homme est un boisé épicé royal et enveloppant. Encens, cuir et ambre gris dans une composition masculine profonde qui incarne l'âme de l'Oman.",
    "description": "Amouage Beloved pour Homme est une fragrance masculine qui porte en elle l'essence même de la maison Amouage et de son pays d'origine, l'Oman — ses encens millénaires, ses caravanes de résines précieuses, sa tradition parfumière inégalée dans le monde arabe.\n\nLa composition s'ouvre sur un accord citrus-épicé de bergamote, poivre rouge et cardamome. Le cœur est dominé par un encens d'Oman d'une qualité exceptionnelle, accompagné d'une rose orientale et de cuir noble dans un accord boisé-résineuse d'une profondeur remarquable. La base d'ambre gris, bois de oud et musc crée un sillage persistant qui peut accompagner une journée entière et même se retrouver sur les vêtements le lendemain.\n\nBeloved pour Homme est la fragrance du connaisseur qui apprécie l'art de la parfumerie orientale dans sa dimension la plus noble et la plus authentique.\n\nMaison Numidia propose ce parfum Amouage authentique avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Bergamote", "Poivre rouge", "Cardamome"],
      "heart": ["Encens d'Oman", "Rose orientale", "Cuir noble"],
      "base": ["Ambre gris", "Bois de oud", "Musc"]
    },
    "family": "Oriental Boisé",
    "occasions": ["Soirée", "Occasions formelles", "Prestige"],
    "seasons": ["Automne", "Hiver"],
    "longevity": 5,
    "sillage": 5,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["amouage-dia-homme", "amouage-interlude-man", "creed-royal-oud"]
  },
  {
    "id": "frederic-malle-portrait-of-a-lady",
    "slug": "frederic-malle-portrait-of-a-lady",
    "h1": "Frédéric Malle Portrait of a Lady Parfum Algérie",
    "name": "Portrait of a Lady",
    "brand": "Frédéric Malle",
    "brandSlug": "frederic-malle",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "EDP",
    "volume": "100ml",
    "price": 24900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/frederic-malle-portrait-of-a-lady.jpg",
    "shortDescription": "Frédéric Malle Portrait of a Lady est un chef-d'oeuvre de la parfumerie niche moderne. Rose de Turquie, patchouli marocain et framboise dans une composition floral-boisée absolue signée Dominique Ropion.",
    "description": "Frédéric Malle Portrait of a Lady est régulièrement cité parmi les dix meilleures fragrances de la parfumerie contemporaine. Créée par le légendaire parfumeur Dominique Ropion pour la maison Frédéric Malle, elle est l'exemple parfait de ce que peut accomplir un parfumeur de génie lorsqu'il dispose d'une liberté totale de création et de budgets de matières premières illimités.\n\nLa fragrance est une ode à la rose dans toute sa complexité et sa profondeur. L'ouverture est une framboise lumineuse et légèrement épicée qui préfigure la générosité à venir. Le cœur est monumental : rose de Turquie en quantités remarquables, patchouli marocain, cèdre de Virginie et un accord épicé-floral qui dépasse la rose pour créer quelque chose d'absolument unique. La base de sandalwood et musc préserve la beauté florale.\n\nPortrait of a Lady est pour les femmes qui ont épuisé les parfums mainstream et qui cherchent quelque chose de vraiment exceptionnel. Une expérience olfactive unique.\n\nMaison Numidia propose ce parfum Frédéric Malle authentique avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Framboise", "Bergamote", "Épices douces"],
      "heart": ["Rose de Turquie", "Patchouli marocain", "Cannelle", "Cèdre"],
      "base": ["Bois de santal", "Musc blanc", "Ambre"]
    },
    "family": "Floral Boisé",
    "occasions": ["Soirée", "Occasions spéciales", "Prestige"],
    "seasons": ["Automne", "Hiver", "Printemps"],
    "longevity": 5,
    "sillage": 5,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["frederic-malle-carnal-flower", "amouage-lyric-femme", "byredo-gypsy-water"]
  },
  {
    "id": "frederic-malle-carnal-flower",
    "slug": "frederic-malle-carnal-flower",
    "h1": "Frédéric Malle Carnal Flower Parfum Algérie",
    "name": "Carnal Flower",
    "brand": "Frédéric Malle",
    "brandSlug": "frederic-malle",
    "category": "parfums-femme",
    "gender": "unisexe",
    "concentration": "EDP",
    "volume": "100ml",
    "price": 24900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/frederic-malle-carnal-flower.jpg",
    "shortDescription": "Frédéric Malle Carnal Flower est le portrait olfactif le plus saisissant de la tubéreuse. Tubéreuse absolue, eucalyptus et melon dans une composition florale sensuelle et troublante.",
    "description": "Frédéric Malle Carnal Flower est souvent décrit comme le meilleur parfum à la tubéreuse jamais créé. Composé par Dominique Ropion — le même maître parfumeur que Portrait of a Lady — Carnal Flower utilise la tubéreuse absolue en quantités qui ne sont possibles que lorsqu'on refuse tout compromis budgétaire.\n\nLa tubéreuse est l'une des fleurs les plus troublantes et les plus sensuelles de la parfumerie. Dans Carnal Flower, elle est présentée sans filtre : créameuse, légèrement animale, d'une générosité florale qui peut sembler presque obscène dans son abondance. L'eucalyptus en tête apporte une fraîcheur camphrée inattendue qui donne du relief à la composition. Le melon et la coriandre ajoutent des touches fruitées-herbacées qui empêchent la tubéreuse de devenir trop lourde. La base de musc blanc et bois de santal préserve la pureté florale.\n\nCarnal Flower est réservé aux amateurs qui connaissent la tubéreuse et veulent en découvrir la version maximale. Disponible chez Maison Numidia avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Eucalyptus", "Melon", "Coriandre"],
      "heart": ["Tubéreuse absolue", "Jasmin", "Ylang-ylang"],
      "base": ["Musc blanc", "Bois de santal", "Ambregris"]
    },
    "family": "Floral",
    "occasions": ["Soirée", "Prestige", "Occasions spéciales"],
    "seasons": ["Été", "Automne"],
    "longevity": 5,
    "sillage": 4,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["frederic-malle-portrait-of-a-lady", "amouage-reflection", "tom-ford-black-orchid"]
  },
  {
    "id": "byredo-gypsy-water",
    "slug": "byredo-gypsy-water",
    "h1": "Byredo Gypsy Water Parfum Algérie",
    "name": "Gypsy Water",
    "brand": "Byredo",
    "brandSlug": "byredo",
    "category": "parfums-femme",
    "gender": "unisexe",
    "concentration": "EDP",
    "volume": "100ml",
    "price": 16900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/byredo-gypsy-water.jpg",
    "shortDescription": "Byredo Gypsy Water est une fragrance forestière boisée et libre qui évoque la vie nomade. Bergamote, pin et ambre dans une composition naturelle et poétique de la maison suédoise.",
    "description": "Byredo Gypsy Water est l'un des parfums les plus populaires de la maison suédoise Byredo, fondée en 2006 par Ben Gorham. Inspiré par la vie libre et nomade des Roms — les Gitans — Gypsy Water est une fragrance qui évoque les nuits autour d'un feu de camp dans la forêt, la liberté des grands espaces et une certaine mélancolie poétique du voyage.\n\nLa composition est un boisé naturel d'une belle authenticité. L'ouverture est fraîche et légèrement résineuse : bergamote, citron et une touche de poivre qui donnent de la vivacité. Le cœur développe un accord pin-incense d'une naturalité désarmante — comme un sous-bois après la pluie. La base d'ambre gris, vanille et musc boisé donne à Gypsy Water sa chaleur, sa persistance et cet aspect \"peau de quelqu'un qui sent naturellement bon\" qui le rend si addictif.\n\nGypsy Water est pour tous ceux qui aiment les parfums naturels et boisés sans artifice. Sa popularité dans la communauté parfumerie témoigne de son efficacité et de son originalité.\n\nMaison Numidia propose ce parfum Byredo authentique avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Bergamote", "Citron", "Poivre"],
      "heart": ["Pin", "Encens", "Orris"],
      "base": ["Ambre gris", "Vanille", "Musc boisé"]
    },
    "family": "Boisé",
    "occasions": ["Bureau", "Casual", "Journée"],
    "seasons": ["Printemps", "Automne", "Toute saison"],
    "longevity": 4,
    "sillage": 3,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["byredo-bal-d-afrique", "maison-margiela-replica-jazz-club", "tom-ford-oud-wood"]
  },
  {
    "id": "byredo-bal-d-afrique",
    "slug": "byredo-bal-d-afrique",
    "h1": "Byredo Bal d Afrique Parfum Algérie",
    "name": "Bal d'Afrique",
    "brand": "Byredo",
    "brandSlug": "byredo",
    "category": "parfums-femme",
    "gender": "unisexe",
    "concentration": "EDP",
    "volume": "100ml",
    "price": 16900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/byredo-bal-d-afrique.jpg",
    "shortDescription": "Byredo Bal d'Afrique est une fragrance fleurie-boisée lumineuse inspirée du Paris africain des années 1930. Néroli, fleurs sauvages et cèdre africain dans une composition solaire et joyeuse.",
    "description": "Byredo Bal d'Afrique est une célébration du Paris des années 1930 — ce moment unique où artistes, musiciens et intellectuels africains et caribéens se réunissaient dans les clubs et les cafés parisiens pour célébrer une culture en pleine effervescence. Cette fragrance capture l'esprit festif et lumineux de cette époque dorée.\n\nLa composition est une invitation à la joie. L'ouverture est immédiatement solaire et lumineuse : bergamote africaine, néroli frais et une touche de citron. Le cœur déploie des fleurs sauvages d'Afrique — frangipanier, jasmin, fleurs des champs — dans un accord floral léger et lumineux. La base de bois de cèdre africain, ambre et musc blanc donne à Bal d'Afrique sa chaleur, sa profondeur et sa persistance.\n\nBal d'Afrique est une fragrance qui met de bonne humeur et qui évoque irrésistiblement la lumière, la musique et la joie de vivre. Sa versatilité unisexe en fait un parfum pour tous ceux qui aiment les fragrances florales-boisées solaires.\n\nMaison Numidia propose ce parfum Byredo authentique avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Bergamote africaine", "Néroli", "Citron"],
      "heart": ["Fleurs sauvages d'Afrique", "Frangipanier", "Jasmin"],
      "base": ["Cèdre africain", "Ambre", "Musc blanc", "Vétiver"]
    },
    "family": "Floral Boisé",
    "occasions": ["Journée", "Bureau", "Casual"],
    "seasons": ["Printemps", "Été", "Automne"],
    "longevity": 4,
    "sillage": 3,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["byredo-gypsy-water", "creed-aventus", "acqua-di-parma-colonia"]
  },
  {
    "id": "memo-paris-african-leather",
    "slug": "memo-paris-african-leather",
    "h1": "Memo Paris African Leather Parfum Algérie",
    "name": "African Leather",
    "brand": "Memo Paris",
    "brandSlug": "memo-paris",
    "category": "parfums-homme",
    "gender": "unisexe",
    "concentration": "EDP",
    "volume": "75ml",
    "price": 22500,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/memo-paris-african-leather.jpg",
    "shortDescription": "Memo Paris African Leather est un cuiré boisé sensoriel et évocateur. Cuir tanné, encens et bois africains dans une composition niche qui transporte vers les savanes africaines.",
    "description": "Memo Paris African Leather est une fragrance qui s'inscrit dans la grande tradition de la maison Memo Paris — des fragrances inspirées par des voyages réels dans des contrées lointaines, racontées avec le vocabulaire de la parfumerie de luxe française.\n\nAfrican Leather s'inspire des steppes et savanes africaines — la sécheresse et la chaleur, le cuir des équipements de voyage, la fumée des feux de brousse et les résines des arbres africains. La composition est un cuiré-boisé d'une authenticité et d'une précision remarquables.\n\nL'ouverture est directe et caractéristique : cuir tanné d'Afrique, poivre noir et bergamote dans un accord immédiatement évocateur. Le cœur développe une alliance encens-bois d'ébène-ciste qui apporte profondeur et texture à la composition. La base d'ambre gris africain, musc et patchouli ancre la fragrance dans une persistance qui peut durer une journée entière.\n\nAfrican Leather est pour les aventuriers et les voyageurs — ceux qui portent leurs expériences comme une seconde peau. Disponible chez Maison Numidia avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Cuir tanné", "Poivre noir", "Bergamote"],
      "heart": ["Encens africain", "Bois d'ébène", "Ciste"],
      "base": ["Ambre gris", "Musc", "Patchouli africain"]
    },
    "family": "Cuiré Boisé",
    "occasions": ["Soirée", "Casual", "Aventure"],
    "seasons": ["Automne", "Hiver"],
    "longevity": 5,
    "sillage": 4,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["amouage-interlude-man", "tom-ford-tuscan-leather", "kilian-love-dont-be-shy"]
  }
];

const allSlugs = new Set([...existingSlugs, ...newProducts.map(p => p.slug)]);
let errors = 0;
for (const p of newProducts) {
  if (existingSlugs.has(p.slug)) { console.error(`DUPLICATE: ${p.slug}`); errors++; }
  for (const r of p.related) {
    if (!allSlugs.has(r)) { console.error(`MISSING related "${r}" in ${p.slug}`); errors++; }
  }
}
if (errors > 0) { console.error(`${errors} erreur(s) — abandon`); process.exit(1); }

data.products.push(...newProducts);
writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf8');
console.log(`✅ ${newProducts.length} produits ajoutés — total: ${data.products.length} produits`);
