import { readFileSync, writeFileSync } from 'fs';

const filePath = 'data/products.json';
const data = JSON.parse(readFileSync(filePath, 'utf8'));
const existingSlugs = new Set(data.products.map(p => p.slug));

const newProducts = [
  {
    "id": "lattafa-ejaazi",
    "slug": "lattafa-ejaazi",
    "h1": "Lattafa Ejaazi Parfum Oriental Algérie",
    "name": "Ejaazi",
    "brand": "Lattafa",
    "brandSlug": "lattafa",
    "category": "parfums-orientaux",
    "gender": "unisexe",
    "concentration": "EDP",
    "volume": "100ml",
    "price": 3200,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/lattafa-ejaazi.jpg",
    "shortDescription": "Lattafa Ejaazi est un oriental boisé fruité enveloppant et généreux. Framboise, rose de Damas et oud dans une composition de prestige à prix accessible pour la maison Lattafa.",
    "description": "Lattafa Ejaazi est une création de la maison dubaïote Lattafa Perfumes qui a su s'imposer comme l'une des références les plus appréciées de la parfumerie orientale contemporaine. Ejaazi — qui signifie \"mon miracle\" en arabe — est une fragrance unisexe qui associe la générosité orientale à une accessibilité rare dans ce segment.\n\nLa composition s'ouvre sur un accord fruité lumineux de framboise et de bergamote qui donne une fraîcheur initiale bienvenue. Le cœur est le cœur même de la fragrance orientale : rose de Damas généreuse, jasmin épanoui et une touche épicée de cannelle. Le fond est profond et riche : oud distillé, musc blanc et ambre dans un accord persistant et enveloppant qui peut se percevoir pendant de nombreuses heures.\n\nEjaazi est idéal pour toutes les occasions où l'on veut un parfum oriental de qualité sans dépenser une fortune. Sa composition soignée et sa tenue remarquable en font une valeur sûre du marché des parfums orientaux en Algérie.\n\nDisponible chez Maison Numidia avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Framboise", "Bergamote", "Mandarine"],
      "heart": ["Rose de Damas", "Jasmin", "Cannelle"],
      "base": ["Oud", "Musc blanc", "Ambre"]
    },
    "family": "Oriental Fruité",
    "occasions": ["Soirée", "Occasions spéciales", "Hiver"],
    "seasons": ["Automne", "Hiver"],
    "longevity": 5,
    "sillage": 4,
    "inStock": true,
    "featured": false,
    "isOriental": true,
    "related": ["lattafa-oud-mood", "lattafa-bade-al-oud", "swiss-arabian-shaghaf-oud"]
  },
  {
    "id": "lattafa-fakhar-homme",
    "slug": "lattafa-fakhar-homme",
    "h1": "Lattafa Fakhar Homme Parfum Oriental Algérie",
    "name": "Fakhar pour Homme",
    "brand": "Lattafa",
    "brandSlug": "lattafa",
    "category": "parfums-orientaux",
    "gender": "homme",
    "concentration": "EDP",
    "volume": "100ml",
    "price": 3500,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/lattafa-fakhar-homme.jpg",
    "shortDescription": "Lattafa Fakhar pour Homme est un oriental épicé boisé viril et envoûtant. Safran, oud noir et ambre dans une composition somptueuse qui incarne la fierté (fakhar) de l'homme arabe.",
    "description": "Lattafa Fakhar pour Homme est une ode à la fierté et à la noblesse de l'homme oriental. Fakhar signifie \"fierté\" en arabe, et cette fragrance porte ce nom avec tout le caractère et la profondeur qu'il implique. Créée par Lattafa Perfumes, maison dubaïote reconnue pour la qualité de ses compositions à prix accessible, Fakhar pour Homme est l'une des fragrances masculines orientales les plus complètes de la gamme.\n\nLa composition s'ouvre avec autorité sur un safran luxueux et une rose orientale, accord signature des grandes fragrances du Moyen-Orient. Le cœur développe un bois de oud fumé et épicé, accompagné de cuir noir et de muscade dans un accord d'une virilité assumée. La base est profonde et persistante — ambre gris, bois de santal et musc ambré — qui peut se maintenir sur la peau pendant douze heures ou plus.\n\nFakhar pour Homme convient à l'homme algérien qui apprécie les fragrances orientales de caractère, sans jamais sacrifier la qualité à l'accessibilité. Disponible chez Maison Numidia avec livraison COD dans les 58 wilayas.",
    "notes": {
      "top": ["Safran", "Rose orientale", "Bergamote"],
      "heart": ["Oud noir", "Cuir", "Muscade"],
      "base": ["Ambre gris", "Bois de santal", "Musc ambré"]
    },
    "family": "Oriental Épicé",
    "occasions": ["Soirée", "Hiver", "Occasions formelles"],
    "seasons": ["Automne", "Hiver"],
    "longevity": 5,
    "sillage": 5,
    "inStock": true,
    "featured": false,
    "isOriental": true,
    "related": ["lattafa-ejaazi", "lattafa-bade-al-oud", "al-haramain-amber-oud-tobacco"]
  },
  {
    "id": "lattafa-maqaal",
    "slug": "lattafa-maqaal",
    "h1": "Lattafa Maqaal Parfum Oriental Algérie",
    "name": "Maqaal",
    "brand": "Lattafa",
    "brandSlug": "lattafa",
    "category": "parfums-orientaux",
    "gender": "unisexe",
    "concentration": "EDP",
    "volume": "100ml",
    "price": 3200,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/lattafa-maqaal.jpg",
    "shortDescription": "Lattafa Maqaal est un oud boisé riche et généreux, typique du savoir-faire de la maison dubaïote. Notes de bois de oud, de santal et d'ambre dans une composition profonde et persistante.",
    "description": "Lattafa Maqaal est une fragrance orientale unisexe qui célèbre la richesse et la profondeur de l'oud dans toute sa splendeur. Maqaal — qui évoque un endroit de contemplation et de rencontre en arabe — est une composition qui invite à la sérénité et à l'introspection, tout en dégageant une présence remarquable.\n\nLa composition s'ouvre sur un accord boisé-résineux immédiat, avec des notes vertes légèrement fumées qui donnent au parfum une profondeur naturelle dès les premières secondes. Le cœur est dominé par un oud de qualité, distillé avec soin pour en extraire les nuances boisées, légèrement animaliques et fumées qui font la valeur de cette matière première. Le bois de santal créamy accompagne l'oud et adoucit sa profondeur. La base est un accord ambre-musc persistant qui ancre la fragrance dans la durée.\n\nMaqaal est la fragrance des hommes et femmes qui aiment l'oud authentique sans artifice. Sa composition honnête et sa tenue remarquable en font un excellent rapport qualité-prix pour un parfum oriental.\n\nDisponible chez Maison Numidia avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Oud fumé", "Notes vertes", "Épices douces"],
      "heart": ["Oud de qualité", "Bois de santal", "Rose"],
      "base": ["Ambre", "Musc", "Benjoin"]
    },
    "family": "Oriental Oudé",
    "occasions": ["Soirée", "Prière", "Occasions spéciales"],
    "seasons": ["Automne", "Hiver"],
    "longevity": 5,
    "sillage": 4,
    "inStock": true,
    "featured": false,
    "isOriental": true,
    "related": ["lattafa-ejaazi", "lattafa-velvet-oud", "rasasi-dhan-al-oudh"]
  },
  {
    "id": "al-haramain-amber-oud-bleu",
    "slug": "al-haramain-amber-oud-bleu",
    "h1": "Al Haramain Amber Oud Bleu Parfum Oriental Algérie",
    "name": "Amber Oud Bleu Edition",
    "brand": "Al Haramain",
    "brandSlug": "al-haramain",
    "category": "parfums-orientaux",
    "gender": "unisexe",
    "concentration": "EDP",
    "volume": "60ml",
    "price": 6500,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/al-haramain-amber-oud-bleu.jpg",
    "shortDescription": "Al Haramain Amber Oud Bleu Edition est une déclinaison fraîche et aquatique de l'iconique Amber Oud. Bergamote, oud bleu et ambre dans une composition orientale étonnamment légère.",
    "description": "Al Haramain Amber Oud Bleu Edition est une réinterprétation fraîche et moderne de l'iconique Amber Oud de la maison saoudienne. Là où l'Amber Oud original est chaud, profond et enveloppant, la version Bleu prend une direction aquatique et fraîche qui la rend beaucoup plus accessible pour les journées et les saisons chaudes.\n\nLa composition s'ouvre sur une envolée fraîche de bergamote, citron et notes aquatiques qui captent immédiatement l'attention par leur légèreté surprenante. Le cœur introduit progressivement l'oud — traité ici de manière plus légère et plus fraîche que dans l'original — accompagné de jasmin et de cèdre bleu. La base est un accord ambre-musc d'une douceur caractéristique de la maison Al Haramain.\n\nAmber Oud Bleu Edition est idéal pour les amateurs de fragrances orientales qui souhaitent un oud porté à des températures estivales, ou pour ceux qui s'initient à l'univers de l'oud et cherchent une version accessible et moderne.\n\nMaison Numidia propose ce parfum Al Haramain authentique avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Bergamote", "Citron", "Notes aquatiques"],
      "heart": ["Oud bleu", "Jasmin", "Cèdre"],
      "base": ["Ambre", "Musc", "Bois blancs"]
    },
    "family": "Oriental Aquatique",
    "occasions": ["Journée", "Bureau", "Été"],
    "seasons": ["Printemps", "Été"],
    "longevity": 4,
    "sillage": 3,
    "inStock": true,
    "featured": false,
    "isOriental": true,
    "related": ["al-haramain-amber-oud", "al-haramain-amber-oud-gold", "lattafa-ejaazi"]
  },
  {
    "id": "ajmal-aurum",
    "slug": "ajmal-aurum",
    "h1": "Ajmal Aurum Parfum Oriental Femme Algérie",
    "name": "Aurum",
    "brand": "Ajmal",
    "brandSlug": "ajmal",
    "category": "parfums-orientaux",
    "gender": "femme",
    "concentration": "EDP",
    "volume": "75ml",
    "price": 5500,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/ajmal-aurum.jpg",
    "shortDescription": "Ajmal Aurum est un floral oriental précieux et lumineux. Rose dorée, jasmin et ambre dans une composition féminine somptueuse signée de la grande maison de parfumerie Ajmal.",
    "description": "Ajmal Aurum est une fragrance féminine qui porte en elle tout le savoir-faire de la maison Ajmal, fondée en 1951 en Inde et devenue l'une des maisons de parfumerie orientale les plus respectées au monde. Aurum — qui signifie \"or\" en latin — est une composition précieuse qui mérite pleinement ce nom luxueux.\n\nLa fragrance s'ouvre sur un accord floral fruité lumineux : pêche dorée, mandarine et bergamote dans une effusion solaire et joyeuse. Le cœur est là où Aurum révèle sa vraie nature : rose de Damas et jasmin sambac dans un accord floral oriental d'une générosité et d'une beauté remarquables. La base dorée d'ambre, de musc et de bois de santal est enveloppante et persistante.\n\nAjmal Aurum est une fragrance pour les femmes qui aiment les parfums orientaux floraux, riches mais pas lourds. Sa composition équilibrée lui permet de convenir aussi bien aux occasions du soir qu'aux journées spéciales.\n\nMaison Numidia propose ce parfum Ajmal authentique avec livraison COD dans toutes les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Pêche dorée", "Mandarine", "Bergamote"],
      "heart": ["Rose de Damas", "Jasmin sambac", "Orchidée"],
      "base": ["Ambre", "Musc", "Bois de santal"]
    },
    "family": "Floral Oriental",
    "occasions": ["Soirée", "Occasions spéciales", "Hiver"],
    "seasons": ["Automne", "Hiver"],
    "longevity": 5,
    "sillage": 4,
    "inStock": true,
    "featured": false,
    "isOriental": true,
    "related": ["ajmal-sacrifice-pour-femme", "al-haramain-rose-d-arabie", "swiss-arabian-noora"]
  },
  {
    "id": "ajmal-wisal",
    "slug": "ajmal-wisal",
    "h1": "Ajmal Wisal Parfum Oriental Femme Algérie",
    "name": "Wisal",
    "brand": "Ajmal",
    "brandSlug": "ajmal",
    "category": "parfums-orientaux",
    "gender": "femme",
    "concentration": "EDP",
    "volume": "50ml",
    "price": 4800,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/ajmal-wisal.jpg",
    "shortDescription": "Ajmal Wisal est un floral poudré oriental doux et romantique. Framboise, rose de mai et musc dans une composition féminine enveloppante qui célèbre l'union et la connexion.",
    "description": "Ajmal Wisal — qui signifie \"union\" ou \"connexion\" en arabe — est une fragrance féminine qui évoque l'idée de rapprochement, de tendresse et de douceur partagée. Cette création de la maison Ajmal est un floral poudré oriental d'une douceur désarmante, idéal pour les femmes qui cherchent un parfum romantique et enveloppant.\n\nLa composition débute sur une fraîcheur fruitée de framboise et de bergamote, légère et attrayante. Le cœur floral déploie une rose de mai généreuse, du jasmin et une touche de poudre d'iris dans un accord romantique et féminin. La base douce d'ambre, musc blanc et vanille légère crée un sillage enveloppant et chaleureux qui invoque la douceur d'un moment intime partagé.\n\nWisal est le parfum idéal pour les journées et soirées romantiques. Sa douceur et son sillage poudré-fleuri en font aussi un excellent choix pour les femmes qui aiment les parfums qui évoquent la tendresse et la féminité.\n\nDisponible chez Maison Numidia avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Framboise", "Bergamote", "Pêche"],
      "heart": ["Rose de mai", "Jasmin", "Iris poudré"],
      "base": ["Ambre", "Musc blanc", "Vanille légère"]
    },
    "family": "Floral Poudré Oriental",
    "occasions": ["Soirée", "Romance", "Occasions spéciales"],
    "seasons": ["Automne", "Hiver"],
    "longevity": 4,
    "sillage": 3,
    "inStock": true,
    "featured": false,
    "isOriental": true,
    "related": ["ajmal-aurum", "swiss-arabian-noora", "al-haramain-rose-oud"]
  },
  {
    "id": "armaf-club-de-nuit-intense-man",
    "slug": "armaf-club-de-nuit-intense-man",
    "h1": "Armaf Club de Nuit Intense Man Parfum Homme Algérie",
    "name": "Club de Nuit Intense Man",
    "brand": "Armaf",
    "brandSlug": "armaf",
    "category": "parfums-homme",
    "gender": "homme",
    "concentration": "EDP",
    "volume": "105ml",
    "price": 5500,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/armaf-club-de-nuit-intense-man.jpg",
    "shortDescription": "Armaf Club de Nuit Intense Man est un fougère boisé puissant et charismatique. Connu pour son rapprochement avec Creed Aventus, il offre des notes de bergamote fumée, bouleau et musc à prix accessible.",
    "description": "Armaf Club de Nuit Intense Man est l'un des parfums masculins les plus discutés dans la communauté des passionnés de parfumerie. La raison ? Sa ressemblance frappante avec le légendaire Creed Aventus, parfum culte vendu à un prix bien plus élevé. Pour les connaisseurs algériens qui apprécient la qualité mais qui respectent leur budget, Club de Nuit Intense Man représente une proposition difficile à ignorer.\n\nLa composition s'ouvre sur une bergamote fumée accompagnée d'ananas et de blackcurrant qui donnent immédiatement ce caractère caractéristique et reconnaissable. Le cœur développe un accord boisé-fruité de bouleau fumé, bois de rose et cèdre qui constitue le pilier olfactif de la fragrance. La base est profonde et persistante : musc blanc, ambre, vétiver et une note fumée qui peut se maintenir pendant de longues heures.\n\nClub de Nuit Intense Man est une fragrance polyvalente qui convient aux occasions professionnelles comme aux soirées. Son excellente longévité et son sillage affirmé en font un choix très rentable pour le parfumeur conscient de son budget.\n\nMaison Numidia propose ce parfum Armaf authentique avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Bergamote fumée", "Ananas", "Blackcurrant"],
      "heart": ["Bouleau fumé", "Bois de rose", "Cèdre"],
      "base": ["Musc blanc", "Ambre", "Vétiver", "Birch fumé"]
    },
    "family": "Fougère Boisé",
    "occasions": ["Bureau", "Soirée", "Occasions importantes"],
    "seasons": ["Printemps", "Automne", "Hiver"],
    "longevity": 5,
    "sillage": 5,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["creed-aventus", "paco-rabanne-1-million-elixir", "armaf-club-de-nuit-intense-femme"]
  },
  {
    "id": "afnan-9pm",
    "slug": "afnan-9pm",
    "h1": "Afnan 9PM Parfum Homme Algérie",
    "name": "9PM",
    "brand": "Afnan",
    "brandSlug": "afnan",
    "category": "parfums-homme",
    "gender": "homme",
    "concentration": "EDP",
    "volume": "100ml",
    "price": 4500,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/afnan-9pm.jpg",
    "shortDescription": "Afnan 9PM est un oriental épicé séduisant et nocturne. Connu pour sa proximité avec Jean Paul Gaultier Le Male, il propose cardamome, vanille et bois à un prix très accessible.",
    "description": "Afnan 9PM est l'une des créations les plus réussies de la maison Afnan Perfumes de Dubaï. Ce parfum masculin a rapidement gagné une réputation de « dupe accessible » du célèbre Jean Paul Gaultier Le Male, l'un des parfums masculins les plus vendus au monde. Pour les amateurs algériens qui apprécient ce style olfactif particulier — oriental-épicé avec des notes de vanille et de cardamome — 9PM offre une alternative convaincante à un prix très accessible.\n\nLa composition s'ouvre sur une envolée épicée de cardamome fraîche et de lavande aromatique, accord signature très proche de son inspiration. Le cœur développe un accord floral-épicé de cannelle, géranium et muscade dans une richesse orientale immédiate. La base est généreuse et sensuelle : vanille noire, ambre et musc blanc dans un accord chaud et persistant qui reste perceptible plusieurs heures après l'application.\n\n9PM est parfait pour les soirées et les occasions importantes où l'on veut un parfum séduisant et remarqué sans investir dans un flacon de luxe. Sa longévité et son sillage sont à la hauteur des parfums bien plus coûteux.\n\nMaison Numidia livre ce parfum avec paiement COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Cardamome", "Lavande", "Bergamote"],
      "heart": ["Cannelle", "Géranium", "Muscade"],
      "base": ["Vanille noire", "Ambre", "Musc blanc"]
    },
    "family": "Oriental Épicé",
    "occasions": ["Soirée", "Sortie nocturne", "Hiver"],
    "seasons": ["Automne", "Hiver"],
    "longevity": 5,
    "sillage": 4,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["le-male-jean-paul-gaultier", "rasasi-al-wisam-evening", "afnan-supremacy-noir"]
  },
  {
    "id": "afnan-supremacy-noir",
    "slug": "afnan-supremacy-noir",
    "h1": "Afnan Supremacy Noir Parfum Oriental Algérie",
    "name": "Supremacy Noir",
    "brand": "Afnan",
    "brandSlug": "afnan",
    "category": "parfums-orientaux",
    "gender": "unisexe",
    "concentration": "EDP",
    "volume": "100ml",
    "price": 3800,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/afnan-supremacy-noir.jpg",
    "shortDescription": "Afnan Supremacy Noir est un oriental boisé sombre et envoûtant. Oud, rose noire et ambre dans une composition nocturne et mystérieuse qui incarne la sophistication orientale moderne.",
    "description": "Afnan Supremacy Noir est une fragrance orientale unisexe qui porte bien son nom : c'est un parfum de suprématie olfactive, sombre, profond et impossiblement attrayant. Créé par la maison Afnan Perfumes, il appartient à cette catégorie de parfums orientaux qui refusent la demi-mesure et assument pleinement leur intensité.\n\nLa composition s'ouvre sur un accord rose-safran immédiat et pénétrant, dans la tradition des grandes fragrances orientales du Golfe. Le cœur déploie un oud de caractère, légèrement fumé et résineuxm accompagné de cuir noir et de bois d'ébène dans un accord sombre et viril. La base est un nid profond d'ambre gris, musc noir et benjoin qui ancre la fragrance dans une persistance remarquable.\n\nSupremacy Noir convient à tous ceux qui recherchent un parfum oriental intense et mystérieux. Sa composition de qualité et son accessibilité en font un choix idéal pour s'initier aux grandes fragrances orientales.\n\nDisponible chez Maison Numidia avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Rose", "Safran", "Bergamote noire"],
      "heart": ["Oud fumé", "Cuir noir", "Bois d'ébène"],
      "base": ["Ambre gris", "Musc noir", "Benjoin"]
    },
    "family": "Oriental Boisé",
    "occasions": ["Soirée", "Nuit", "Occasions spéciales"],
    "seasons": ["Automne", "Hiver"],
    "longevity": 5,
    "sillage": 4,
    "inStock": true,
    "featured": false,
    "isOriental": true,
    "related": ["afnan-9pm", "lattafa-fakhar-homme", "rasasi-dhan-al-oudh"]
  },
  {
    "id": "orientica-oud-saffron",
    "slug": "orientica-oud-saffron",
    "h1": "Orientica Oud Saffron Parfum Oriental Algérie",
    "name": "Oud Saffron",
    "brand": "Orientica",
    "brandSlug": "orientica",
    "category": "parfums-orientaux",
    "gender": "unisexe",
    "concentration": "EDP",
    "volume": "80ml",
    "price": 6500,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/orientica-oud-saffron.jpg",
    "shortDescription": "Orientica Oud Saffron est un oriental luxueux à la croisée du safran iranien et de l'oud du Moyen-Orient. Une composition richissime pour les amateurs des grands parfums orientaux.",
    "description": "Orientica Oud Saffron est une fragrance qui honore deux des matières premières les plus précieuses de la parfumerie orientale : le safran et l'oud. La maison Orientica, connue pour ses créations de qualité à prix intermédiaire, a réussi avec ce parfum à créer une composition qui rivalise avec certains niche bien plus coûteux.\n\nLa composition s'ouvre sur un accord safran généreux et chaleureux, légèrement métallique et épicé, qui installe immédiatement la fragrance dans le registre luxueux. Des notes de rose persane accompagnent le safran dans le cœur, ajoutant une dimension florale orientale typique. La base est profonde et complexe : oud de qualité, bois de santal et ambre dans un accord qui peut facilement se maintenir pendant dix à douze heures.\n\nOud Saffron est la fragrance parfaite pour les amateurs d'orientaux qui souhaitent un parfum à l'oud et au safran de qualité sans débourser des sommes astronomiques. Sa générosité olfactive et sa persistance en font un excellent rapport qualité-prix.\n\nMaison Numidia propose ce parfum Orientica authentique avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Safran", "Rose persane", "Cardamome"],
      "heart": ["Oud", "Ambre rose", "Bois fumé"],
      "base": ["Bois de santal", "Ambre gris", "Musc"]
    },
    "family": "Oriental Épicé",
    "occasions": ["Soirée", "Prière", "Occasions formelles"],
    "seasons": ["Automne", "Hiver"],
    "longevity": 5,
    "sillage": 5,
    "inStock": true,
    "featured": false,
    "isOriental": true,
    "related": ["al-haramain-amber-oud-tobacco", "afnan-supremacy-noir", "lattafa-fakhar-homme"]
  },
  {
    "id": "swiss-arabian-dee-luxe",
    "slug": "swiss-arabian-dee-luxe",
    "h1": "Swiss Arabian Dee Luxe Parfum Oriental Femme Algérie",
    "name": "Dee Luxe",
    "brand": "Swiss Arabian",
    "brandSlug": "swiss-arabian",
    "category": "parfums-orientaux",
    "gender": "femme",
    "concentration": "EDP",
    "volume": "75ml",
    "price": 4500,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/swiss-arabian-dee-luxe.jpg",
    "shortDescription": "Swiss Arabian Dee Luxe est un floral oriental doux et féminin. Framboise, rose de Damas et musc pour une fragrance orientale accessible et enveloppante de la maison suisso-arabe.",
    "description": "Swiss Arabian Dee Luxe est une fragrance féminine de la maison Swiss Arabian Perfumes, marque fondée en 1974 à Jeddah et devenue l'une des références incontournables de la parfumerie orientale de qualité à prix accessible. Dee Luxe incarne l'art de vivre oriental dans une composition florale délicate et enveloppante.\n\nLa composition s'ouvre sur une effusion fruitée de framboise et de cassis qui apporte fraîcheur et attrait. Le cœur est un bouquet oriental floral : rose de Damas, jasmin et oud délicat dans un accord typiquement oriental mais accessible. La base musc-ambre est douce et persistante, laissant un sillage agréable et féminin.\n\nDee Luxe est idéal pour les femmes qui s'initient à la parfumerie orientale ou qui cherchent un parfum oriental floral pour un usage quotidien. Son équilibre entre la légèreté et la profondeur orientale le rend versatile et agréable en toute saison.\n\nMaison Numidia propose ce parfum Swiss Arabian authentique avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Framboise", "Cassis", "Bergamote"],
      "heart": ["Rose de Damas", "Jasmin", "Oud léger"],
      "base": ["Musc", "Ambre", "Vanille légère"]
    },
    "family": "Floral Oriental",
    "occasions": ["Journée", "Bureau", "Sorties"],
    "seasons": ["Toute saison"],
    "longevity": 4,
    "sillage": 3,
    "inStock": true,
    "featured": false,
    "isOriental": true,
    "related": ["swiss-arabian-noora", "swiss-arabian-layali-rouge", "ajmal-wisal"]
  },
  {
    "id": "lattafa-oud-mood-noir",
    "slug": "lattafa-oud-mood-noir",
    "h1": "Lattafa Oud Mood Noir Parfum Oriental Algérie",
    "name": "Oud Mood Noir",
    "brand": "Lattafa",
    "brandSlug": "lattafa",
    "category": "parfums-orientaux",
    "gender": "unisexe",
    "concentration": "EDP",
    "volume": "100ml",
    "price": 3500,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/lattafa-oud-mood-noir.jpg",
    "shortDescription": "Lattafa Oud Mood Noir est la déclinaison sombre et fumée de l'Oud Mood original. Oud fumé, musc noir et ambre dans une composition intense et mystérieuse pour les amateurs d'orientaux profonds.",
    "description": "Lattafa Oud Mood Noir est la version la plus sombre et la plus intense de la famille Oud Mood de Lattafa. Là où l'Oud Mood original joue sur la douceur et l'accessibilité, Noir assume une personnalité plus fumée, plus profonde et plus mystérieuse qui ravira les amateurs de fragrances orientales intenses.\n\nLa composition s'ouvre sur un accord résine-fumé immédiat : oud noir, encens et bergamote sombre dans une introduction qui capte immédiatement l'attention. Le cœur est un accord oud-rose d'une profondeur orientale remarquable, avec une touche de cuir qui renforce le caractère sombre et masuclin de la composition. La base est un accord ambre-musc intense — ambre gris, musc noir et benjoin — qui ancre le parfum dans une persistance redoutable.\n\nOud Mood Noir est fait pour les journées fraîches et les soirées d'hiver algériennes. Sa densité olfactive et son sillage imposant en font un parfum de présence, qui marque son passage sans effort.\n\nDisponible chez Maison Numidia avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Oud noir", "Encens", "Bergamote sombre"],
      "heart": ["Rose orientale", "Cuir", "Épices"],
      "base": ["Ambre gris", "Musc noir", "Benjoin"]
    },
    "family": "Oriental Boisé",
    "occasions": ["Soirée", "Hiver", "Nuit"],
    "seasons": ["Automne", "Hiver"],
    "longevity": 5,
    "sillage": 5,
    "inStock": true,
    "featured": false,
    "isOriental": true,
    "related": ["lattafa-oud-mood", "lattafa-maqaal", "afnan-supremacy-noir"]
  }
];

const allSlugs = new Set([...existingSlugs, ...newProducts.map(p => p.slug)]);
let errors = 0;
for (const p of newProducts) {
  if (existingSlugs.has(p.slug)) { console.error(`DUPLICATE: ${p.slug}`); errors++; }
  for (const r of p.related) {
    if (!allSlugs.has(r)) { console.error(`MISSING related "${r}" in ${p.slug}`); errors++; }
  }
}
if (errors > 0) { console.error(`${errors} erreur(s) — abandon`); process.exit(1); }

data.products.push(...newProducts);
writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf8');
console.log(`✅ ${newProducts.length} produits ajoutés — total: ${data.products.length} produits`);
