import { readFileSync, writeFileSync } from 'fs';

const filePath = 'data/products.json';
const data = JSON.parse(readFileSync(filePath, 'utf8'));
const existingSlugs = new Set(data.products.map(p => p.slug));

const newProducts = [
  {
    "id": "jo-malone-peony-blush-suede",
    "slug": "jo-malone-peony-blush-suede",
    "h1": "Jo Malone Peony Blush Suede Parfum Femme Algérie",
    "name": "Peony & Blush Suede",
    "brand": "Jo Malone London",
    "brandSlug": "jo-malone",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "Cologne",
    "volume": "100ml",
    "price": 11900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/jo-malone-peony-blush-suede.jpg",
    "shortDescription": "Jo Malone Peony & Blush Suede est l'un des parfums féminins les plus aimés de la maison britannique. Pivoine, pêche et suède dans une composition florale luxueuse et délicatement poudré.",
    "description": "Jo Malone London Peony & Blush Suede est l'une des fragrances les plus emblématiques et les plus appréciées de la maison britannique fondée en 1990. Cette cologne — terme que Jo Malone utilise pour toutes ses fragrances, indépendamment de leur concentration réelle — est un floral poudré d'une sophistication rare qui a conquis des millions de femmes à travers le monde.\n\nLa composition est un portrait olfactif de la pivoine dans toute sa splendeur. L'ouverture s'ouvre sur une pêche blanche et une rose délicate qui préfigurent le cœur floral. La pivoine — fraîche, légèrement poudré, d'une féminité absolue — s'épanouit au cœur de la composition dans toute sa générosité. La note de suède au fond est la touche signature qui distingue ce parfum : douce, légèrement animale, elle apporte une profondeur luxueuse et sensuelle qui fait de Peony & Blush Suede un parfum mémorable.\n\nCette fragrance peut se porter seule ou être layée avec d'autres colognes Jo Malone — l'art du layering étant au cœur de la philosophie de la maison. Sa versatilité et son raffinement en font un parfum idéal pour toutes les occasions.\n\nMaison Numidia propose ce parfum Jo Malone London authentique avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Pêche blanche", "Rose", "Groseille rouge"],
      "heart": ["Pivoine fraîche", "Jasmin"],
      "base": ["Suède", "Bois de santal", "Musc"]
    },
    "family": "Floral Poudré",
    "occasions": ["Bureau", "Journée", "Occasions spéciales"],
    "seasons": ["Printemps", "Été", "Automne"],
    "longevity": 3,
    "sillage": 3,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["jo-malone-english-pear", "jo-malone-lime-basil-mandarin", "chloe-signature"]
  },
  {
    "id": "jo-malone-lime-basil-mandarin",
    "slug": "jo-malone-lime-basil-mandarin",
    "h1": "Jo Malone Lime Basil Mandarin Parfum Algérie",
    "name": "Lime Basil & Mandarin",
    "brand": "Jo Malone London",
    "brandSlug": "jo-malone",
    "category": "parfums-femme",
    "gender": "unisexe",
    "concentration": "Cologne",
    "volume": "100ml",
    "price": 11900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/jo-malone-lime-basil-mandarin.jpg",
    "shortDescription": "Jo Malone Lime Basil & Mandarin est la signature olfactive iconique de la maison britannique. Citron vert, basilic et mandarine dans une composition aromatique-citrus d'une fraîcheur absolue.",
    "description": "Jo Malone London Lime Basil & Mandarin est probablement la fragrance la plus iconique et la plus reconnaissable de la maison britannique. C'est la première cologne qui a fait la réputation de Jo Malone, et elle reste à ce jour l'une des plus vendues de la maison grâce à sa fraîcheur immédiate et son originalité désarmante.\n\nLa composition est un accord aromatique-citrus d'une vivacité remarquable. L'ouverture est une explosion de citron vert vif — frais, légèrement piquant — accompagnée d'une mandarine juteuse. Le cœur introduit le basilic vert — note herbacée que l'on attendait pas dans un parfum, mais qui s'intègre avec une logique absolue, apportant fraîcheur végétale et caractère distinctif. La base légère de bois de cèdre et musc préserve la légèreté de la composition.\n\nLime Basil & Mandarin est une fragrance unisexe par excellence — fraîche, directe, sans genre. Son originalité fait qu'elle attire aussi bien les hommes que les femmes qui apprécient les parfums herbacés-citrus.\n\nMaison Numidia propose cette cologne Jo Malone London authentique avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Citron vert", "Mandarine", "Bergamote"],
      "heart": ["Basilic vert", "Thym"],
      "base": ["Bois de cèdre blanc", "Musc végétal"]
    },
    "family": "Aromatique Citrus",
    "occasions": ["Bureau", "Journée", "Sport"],
    "seasons": ["Printemps", "Été"],
    "longevity": 2,
    "sillage": 2,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["jo-malone-peony-blush-suede", "jo-malone-wood-sage-sea-salt", "hermes-un-jardin-sur-le-nil"]
  },
  {
    "id": "jo-malone-wood-sage-sea-salt",
    "slug": "jo-malone-wood-sage-sea-salt",
    "h1": "Jo Malone Wood Sage Sea Salt Parfum Algérie",
    "name": "Wood Sage & Sea Salt",
    "brand": "Jo Malone London",
    "brandSlug": "jo-malone",
    "category": "parfums-femme",
    "gender": "unisexe",
    "concentration": "Cologne",
    "volume": "100ml",
    "price": 11900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/jo-malone-wood-sage-sea-salt.jpg",
    "shortDescription": "Jo Malone Wood Sage & Sea Salt est un aquatique boisé salin et naturel. Ambrette, sauge et sel marin dans une composition qui évoque les falaises battues par l'Atlantique.",
    "description": "Jo Malone London Wood Sage & Sea Salt est une fragrance qui transporte immédiatement vers les paysages côtiers balayés par le vent — les falaises de Cornouailles, les plages sauvages de l'Atlantique, l'air iodé et pur d'un matin de tempête. Cette cologne unisexe est l'une des plus appréciées de la collection pour son caractère naturel et évocateur.\n\nLa composition s'ouvre sur un accord sel de mer immédiat — minéral, légèrement iodé, absolument vrai — accompagné d'une ambrette fraîche. Le cœur introduit la sauge en herbe qui apporte un côté aromatique sec et légèrement terreux, en parfaite harmonie avec les notes marines. La base de bois de driftwood — bois flotté — et ambrette crée un accord naturel et authentique d'une texture particulièrement satisfaisante.\n\nWood Sage & Sea Salt est pour ceux qui aiment les parfums qui sentent vrai et naturel, loin des compositions artificielles et sur-traitées. Son caractère unisexe en fait un choix versatile pour tous.\n\nMaison Numidia propose cette cologne Jo Malone London authentique avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Sel de mer", "Ambrette", "Agrumes marins"],
      "heart": ["Sauge en herbe", "Fleurs sauvages"],
      "base": ["Bois flotté", "Ambrette", "Musc marin"]
    },
    "family": "Aquatique Boisé",
    "occasions": ["Bureau", "Casual", "Sport"],
    "seasons": ["Printemps", "Été"],
    "longevity": 2,
    "sillage": 2,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["jo-malone-lime-basil-mandarin", "creed-millesime-imperial", "issey-miyake-l-eau-d-issey"]
  },
  {
    "id": "maison-margiela-replica-by-the-fireplace",
    "slug": "maison-margiela-replica-by-the-fireplace",
    "h1": "Maison Margiela Replica By the Fireplace Parfum Algérie",
    "name": "Replica By the Fireplace",
    "brand": "Maison Margiela",
    "brandSlug": "maison-margiela",
    "category": "parfums-femme",
    "gender": "unisexe",
    "concentration": "EDT",
    "volume": "100ml",
    "price": 10900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/maison-margiela-replica-by-the-fireplace.jpg",
    "shortDescription": "Maison Margiela Replica By the Fireplace est une ode olfactive à la chaleur d'un feu de cheminée. Bois de châtaignier, vanille fumée et musc dans une composition hivernale et réconfortante.",
    "description": "Maison Margiela Replica By the Fireplace est l'un des parfums les plus originaux et les plus discutés de la ligne Replica — cette collection de fragrances qui cherche à capturer des moments de vie spécifiques dans toute leur vérité olfactive. By the Fireplace capture l'ambiance d'une soirée d'hiver au coin du feu — la chaleur du bois qui brûle, l'odeur de châtaigne grillée, la douceur d'un pull en laine.\n\nLa composition est un accord boisé-fumé-gourmand d'une originalité remarquable. L'ouverture est immédiatement fumée et boisée : bois de pin brûlé, encens de résine et une légère note de cigare qui évoquent le bois qui prend feu. Le cœur introduit une châtaigne gourmande et vanillée d'une douceur réconfortante — comme une châtaigne rôtie sur les braises. La base de musc, ambre et bois de cèdre donne à By the Fireplace sa persistance hivernale.\n\nCette fragrance est idéale pour les soirées d'hiver algériennes — les nuits fraîches où l'on se retrouve autour d'un foyer. Son caractère original et mémorable en fait un parfum de conversation.\n\nMaison Numidia propose ce parfum Maison Margiela authentique avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Bois de pin brûlé", "Encens", "Clou de girofle"],
      "heart": ["Châtaigne", "Vanille fumée", "Guaïac"],
      "base": ["Musc", "Ambre", "Cèdre"]
    },
    "family": "Boisé Fumé",
    "occasions": ["Soirée", "Hiver", "Casual"],
    "seasons": ["Automne", "Hiver"],
    "longevity": 4,
    "sillage": 3,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["maison-margiela-replica-beach-walk", "maison-margiela-replica-jazz-club", "tobacco-vanille-tom-ford"]
  },
  {
    "id": "maison-margiela-replica-beach-walk",
    "slug": "maison-margiela-replica-beach-walk",
    "h1": "Maison Margiela Replica Beach Walk Parfum Algérie",
    "name": "Replica Beach Walk",
    "brand": "Maison Margiela",
    "brandSlug": "maison-margiela",
    "category": "parfums-femme",
    "gender": "unisexe",
    "concentration": "EDT",
    "volume": "100ml",
    "price": 10900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/maison-margiela-replica-beach-walk.jpg",
    "shortDescription": "Maison Margiela Replica Beach Walk est une balade estivale olfactive. Bergamote, noix de coco et bois de cèdre dans une composition marine et solaire qui évoque une plage idéale.",
    "description": "Maison Margiela Replica Beach Walk capture en flacon ce moment parfait que chacun a vécu : une balade sur une plage baignée de soleil, les pieds dans le sable chaud, l'air iodé et une lumière dorée qui semble arrêter le temps. C'est un parfum qui ne parfume pas — il transporte.\n\nLa composition est un accord solaire-marin d'une légèreté et d'une naturalité désarmantes. L'ouverture est un citrus frais mêlé de bergamote et de fleur d'oranger qui évoquent l'air marin estival. Le cœur développe un accord noix de coco et fleurs de tiaré qui apportent l'exotisme tropical du cocktail sur la plage. La base boisée légère — cèdre blanc et ambre solaire — simule la chaleur du sable et du soleil sur la peau.\n\nBeach Walk est idéal pour les étés algériens — à la plage, à la terrasse d'un café ou simplement pour apporter la fraîcheur estivale dans n'importe quelle journée. Sa légèreté en fait un parfum qu'on peut reapliquer sans retenue.\n\nMaison Numidia propose ce parfum Maison Margiela authentique avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Bergamote", "Citrus frais", "Fleur d'oranger"],
      "heart": ["Noix de coco", "Tiaré", "Rose marine"],
      "base": ["Cèdre blanc", "Ambre solaire", "Musc sableux"]
    },
    "family": "Floral Aquatique",
    "occasions": ["Plage", "Été", "Casual"],
    "seasons": ["Printemps", "Été"],
    "longevity": 2,
    "sillage": 2,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["maison-margiela-replica-by-the-fireplace", "creed-millesime-imperial", "issey-miyake-l-eau-d-issey"]
  },
  {
    "id": "maison-margiela-replica-jazz-club",
    "slug": "maison-margiela-replica-jazz-club",
    "h1": "Maison Margiela Replica Jazz Club Parfum Homme Algérie",
    "name": "Replica Jazz Club",
    "brand": "Maison Margiela",
    "brandSlug": "maison-margiela",
    "category": "parfums-homme",
    "gender": "unisexe",
    "concentration": "EDT",
    "volume": "100ml",
    "price": 10900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/maison-margiela-replica-jazz-club.jpg",
    "shortDescription": "Maison Margiela Replica Jazz Club est l'ambiance d'un club de jazz de minuit. Vétiver fumé, rhum et tabac dans une composition boisée-fumée qui évoque les nuits new-yorkaises des années 1950.",
    "description": "Maison Margiela Replica Jazz Club transporte dans l'ambiance enfumée et sensuelle d'un club de jazz new-yorkais dans les années 1950 — la lumière tamisée, le piano qui joue en sourdine, le verre de bourbon, la fumée douce du tabac et le cuir des canapés. C'est l'un des parfums les plus narratifs et les plus évocateurs de la collection Replica.\n\nLa composition est un accord boisé-fumé-épicé d'une originalité remarquable. L'ouverture introduit immédiatement le rhum et le poivre dans un accord capiteux et séduisant qui définit le caractère de la fragrance. Le cœur développe le tabac blond et le vétiver — note signature de Jazz Club — dans une alliance boisée-fumée très typique des parfums masculins classiques. La base de musc, bois de santal et cardamome ancre la fragrance dans une persistance satisfaisante.\n\nJazz Club est idéal pour les hommes qui apprécient les parfums boisés-fumés originaux. Son caractère narratif en fait un parfum de conversation et une signature olfactive distinctive.\n\nMaison Numidia propose ce parfum Maison Margiela authentique avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Rhum", "Poivre rose", "Bergamote"],
      "heart": ["Tabac blond", "Vétiver", "Feuilles de violette"],
      "base": ["Musc", "Bois de santal", "Cardamome"]
    },
    "family": "Boisé Fumé",
    "occasions": ["Soirée", "Casual", "Hiver"],
    "seasons": ["Automne", "Hiver"],
    "longevity": 4,
    "sillage": 3,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["maison-margiela-replica-by-the-fireplace", "maison-margiela-replica-beach-walk", "tobacco-vanille-tom-ford"]
  },
  {
    "id": "acqua-di-parma-colonia",
    "slug": "acqua-di-parma-colonia",
    "h1": "Acqua di Parma Colonia Parfum Algérie",
    "name": "Colonia",
    "brand": "Acqua di Parma",
    "brandSlug": "acqua-di-parma",
    "category": "parfums-homme",
    "gender": "unisexe",
    "concentration": "Cologne",
    "volume": "100ml",
    "price": 13500,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/acqua-di-parma-colonia.jpg",
    "shortDescription": "Acqua di Parma Colonia est l'eau de cologne italienne parfaite depuis 1916. Citron de Sicile, fleur de lavande et vétiver dans un parfum iconique qui incarne le luxe discret à l'italienne.",
    "description": "Acqua di Parma Colonia est bien plus qu'un parfum — c'est une institution italienne. Créée en 1916 à Parme, cette colonia est restée fidèle à sa formule originale pendant plus d'un siècle, résistant aux modes et aux tendances avec une assurance qui ne peut venir que d'une qualité absolument indiscutable.\n\nLa composition est un citrus aromatique d'une pureté et d'une noblesse rares. L'ouverture est une effusion de citron de Sicile, bergamote de Calabre et orange douce d'une fraîcheur immédiate et revigorante. Le cœur développe un accord floral-aromatique de lavande anglaise, rose et vétiver dans une composition équilibrée. La base de sandalwood, vétiver et musc est discrète mais persistante.\n\nColonia est la référence absolue pour qui cherche un parfum élégant, discret et intemporel pour le bureau et les occasions quotidiennes. Son rapport qualité-prix est discutable pour certains, mais ses amateurs fidèles y voient l'essence même du luxe discret à l'italienne.\n\nMaison Numidia propose ce parfum Acqua di Parma authentique avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Citron de Sicile", "Bergamote de Calabre", "Orange douce"],
      "heart": ["Lavande", "Rose", "Vétiver"],
      "base": ["Bois de santal", "Musc", "Cèdre"]
    },
    "family": "Aromatique Citrus",
    "occasions": ["Bureau", "Journée", "Casual"],
    "seasons": ["Printemps", "Été"],
    "longevity": 2,
    "sillage": 2,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["acqua-di-parma-magnolia-nobile", "hermes-eau-des-merveilles", "voyage-d-hermes"]
  },
  {
    "id": "acqua-di-parma-magnolia-nobile",
    "slug": "acqua-di-parma-magnolia-nobile",
    "h1": "Acqua di Parma Magnolia Nobile Parfum Femme Algérie",
    "name": "Magnolia Nobile",
    "brand": "Acqua di Parma",
    "brandSlug": "acqua-di-parma",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "EDP",
    "volume": "100ml",
    "price": 14500,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/acqua-di-parma-magnolia-nobile.jpg",
    "shortDescription": "Acqua di Parma Magnolia Nobile est un hommage floral royal à la magnolia blanche. Magnolia, néroli et bois de santal dans une composition luxueuse qui incarne l'élégance italienne au féminin.",
    "description": "Acqua di Parma Magnolia Nobile est la proposition féminine de la maison de Parme — une célébration de la fleur de magnolia dans toute sa noblesse italienne. Cette fragrance est conçue pour la femme qui apprécie le luxe dans sa forme la plus authentique : sans ostentation, avec une qualité de matières premières irréprochable.\n\nLa composition s'ouvre sur une envolée lumineuse de néroli et de bergamote qui apportent fraîcheur et légèreté. Le cœur est dominé par la magnolia blanche — fraîche, légèrement créameuse, avec cette note caractéristique mi-fleurie mi-fruitée qui fait le charme de cette fleur printemps. La fleur d'oranger l'accompagne dans un accord floral d'une beauté naturelle. La base de bois de santal, vétiver et musc blanc donne à Magnolia Nobile sa profondeur et sa persistance.\n\nMagnolia Nobile s'adresse aux femmes qui aiment les fragrances florales naturelles et de qualité. Son origine italienne et ses matières premières nobles en font un parfum de luxe accessible.\n\nDisponible chez Maison Numidia avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Néroli", "Bergamote", "Citrus"],
      "heart": ["Magnolia blanche", "Fleur d'oranger", "Jasmin"],
      "base": ["Bois de santal", "Vétiver", "Musc blanc"]
    },
    "family": "Floral",
    "occasions": ["Bureau", "Journée", "Occasions spéciales"],
    "seasons": ["Printemps", "Été"],
    "longevity": 3,
    "sillage": 3,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["acqua-di-parma-colonia", "guerlain-mon-guerlain-sparkling-bouquet", "chloe-nomade"]
  },
  {
    "id": "lancome-idole-le-parfum",
    "slug": "lancome-idole-le-parfum",
    "h1": "Lancôme Idôle Le Parfum Femme Algérie",
    "name": "Idôle Le Parfum",
    "brand": "Lancôme",
    "brandSlug": "lancome",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "Parfum",
    "volume": "50ml",
    "price": 14900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/lancome-idole-le-parfum.jpg",
    "shortDescription": "Lancôme Idôle Le Parfum est la version la plus concentrée de la fragrance iconique. Rose de Mai, jasmin et musc blanc dans leur expression maximale pour une expérience olfactive absolue.",
    "description": "Lancôme Idôle Le Parfum est la forme la plus pure et la plus concentrée d'Idôle — le parfum féminin qui a redéfini la communication parfumerie de Lancôme depuis son lancement en 2019. Dans cette version Parfum, chaque note est poussée à son expression maximale dans une formulation riche et persistante.\n\nLa composition Parfum amplifie la rose de mai dans toute sa générosité naturelle. Cette rose précieuse — cultivée dans la région grassoise en Provence — est ici présentée dans sa version la plus noble, accompagnée du musc blanc dans sa forme la plus pure et la plus créameuse. Le jasmin sambac apporte une dimension florale plus profonde et plus tropicale.\n\nIdôle Le Parfum est pour les femmes qui aiment l'Idôle original mais qui cherchent une tenue maximale — pour les occasions où l'on veut que son parfum dure toute la soirée et au-delà. Sa concentration Parfum garantit une persistance qui peut atteindre douze heures.\n\nMaison Numidia propose ce parfum Lancôme authentique avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Bergamote", "Néroli", "Poire"],
      "heart": ["Rose de Mai", "Musc blanc intense", "Jasmin sambac"],
      "base": ["Bois de santal", "Musc crémeux", "Ambre doux"]
    },
    "family": "Floral Musqué",
    "occasions": ["Soirée", "Occasions spéciales", "Bureau"],
    "seasons": ["Printemps", "Automne"],
    "longevity": 5,
    "sillage": 4,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["lancome-idole", "idole-aura-lancome", "lancome-idole-now"]
  },
  {
    "id": "hermes-h24-intense",
    "slug": "hermes-h24-intense",
    "h1": "Hermès H24 Intense Parfum Homme Algérie",
    "name": "H24 Intense",
    "brand": "Hermès",
    "brandSlug": "hermes",
    "category": "parfums-homme",
    "gender": "homme",
    "concentration": "EDP",
    "volume": "100ml",
    "price": 13500,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/hermes-h24-intense.jpg",
    "shortDescription": "Hermès H24 Intense est la version EDP plus profonde et chaleureuse du H24. Hosta, clary sage et santal dans une composition boisée-verte d'une intensité nouvelle.",
    "description": "Hermès H24 Intense est la déclinaison EDP du H24 — ce parfum masculin lancé en 2021 qui a introduit une signature olfactive radicalement nouvelle chez Hermès avec ses notes vertes de feuilles d'hosta. L'Intense prend cette base végétale et lui insuffle plus de profondeur, de chaleur et de persistance pour une expérience olfactive plus mémorable.\n\nCréée par Christine Nagel, parfumeur de la maison Hermès, H24 Intense maintient la promesse végétale du H24 — ces feuilles d'hosta fraîches et légèrement vert-métal — tout en l'ancrant dans une base plus profonde et plus boisée. La sauge sclarée est plus présente et plus aromatique dans cette version. Le bois de santal au fond est plus chaleureux et plus généreux.\n\nH24 Intense s'adresse aux hommes qui apprécient la modernité et l'originalité du H24 original mais qui souhaitent un parfum plus persistant pour les occasions importantes. Son caractère boisé-vert unique le distingue de la majorité des parfums masculins sur le marché.\n\nDisponible chez Maison Numidia avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Sauge sclarée", "Bergamote", "Cardamome"],
      "heart": ["Hosta feuilles", "Romarin", "Rose"],
      "base": ["Bois de santal intense", "Vétiver", "Musc"]
    },
    "family": "Boisé Aromatique",
    "occasions": ["Bureau", "Soirée", "Occasions importantes"],
    "seasons": ["Automne", "Hiver"],
    "longevity": 5,
    "sillage": 4,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["h24-hermes", "hermes-eau-intense-vetiver", "terre-d-hermes"]
  },
  {
    "id": "carolina-herrera-bad-boy-parfum",
    "slug": "carolina-herrera-bad-boy-parfum",
    "h1": "Carolina Herrera Bad Boy Parfum Homme Algérie",
    "name": "Bad Boy Le Parfum",
    "brand": "Carolina Herrera",
    "brandSlug": "carolina-herrera",
    "category": "parfums-homme",
    "gender": "homme",
    "concentration": "Parfum",
    "volume": "100ml",
    "price": 12500,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/carolina-herrera-bad-boy-parfum.jpg",
    "shortDescription": "Carolina Herrera Bad Boy Le Parfum est la version la plus intense du flacon-massue. Bergamote noire, bois de gaïac fumé et musc boisé dans une composition masculine de haute intensité.",
    "description": "Carolina Herrera Bad Boy Le Parfum est l'expression ultime du Bad Boy — ce parfum masculin audacieux dont le flacon en forme de massue noire et or est devenu l'un des objets de parfumerie les plus reconnaissables du marché. Cette version Parfum prend le Bad Boy à son niveau maximal d'intensité et de persistance.\n\nLa composition Parfum amplifie chaque dimension du Bad Boy. La bergamote est plus sombre, plus profonde, presque noire dans son caractère. La sauge aromatique est plus intense et plus mémorable. Le cœur de cèdre et cuir est plus riche et plus présent. La base de chêne coumarine-vétiver-tonka est beaucoup plus généreuse, créant un accord boisé d'une persistance remarquable qui peut se maintenir pendant plus de douze heures.\n\nBad Boy Le Parfum est pour les occasions where les hommes veulent s'assurer que leur parfum reste présent du début à la fin. Sa concentration maximale et son sillage affirmé en font un parfum de soirée et d'événements importants.\n\nMaison Numidia propose ce parfum Carolina Herrera authentique avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Bergamote noire", "Sauge intense"],
      "heart": ["Cèdre fumé", "Cuir profond", "Cardamome"],
      "base": ["Chêne coumarine", "Vétiver profond", "Tonka", "Musc boisé"]
    },
    "family": "Boisé Aromatique",
    "occasions": ["Soirée", "Occasions importantes", "Hiver"],
    "seasons": ["Automne", "Hiver"],
    "longevity": 5,
    "sillage": 5,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["carolina-herrera-bad-boy", "jean-paul-gaultier-bad-boy", "dior-sauvage-parfum"]
  },
  {
    "id": "dior-fahrenheit-parfum",
    "slug": "dior-fahrenheit-parfum",
    "h1": "Dior Fahrenheit Parfum Homme Algérie",
    "name": "Fahrenheit Parfum",
    "brand": "Dior",
    "brandSlug": "dior",
    "category": "parfums-homme",
    "gender": "homme",
    "concentration": "Parfum",
    "volume": "75ml",
    "price": 14900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/dior-fahrenheit-parfum.jpg",
    "shortDescription": "Dior Fahrenheit Parfum est la version absolue du classique masculin légendaire. Violette, cuir et bois de santal dans une intensité boisée-cuirée incomparable depuis 1988.",
    "description": "Dior Fahrenheit Parfum est l'extrait de parfum — la concentration maximale — du légendaire Fahrenheit de Christian Dior, créé en 1988. Ce parfum est souvent cité comme l'une des fragrances masculines les plus originales et les plus influentes de l'histoire de la parfumerie, reconnaissable entre toutes pour sa signature violette-boisée-cuirée unique.\n\nLa concentration Parfum amplifie chaque aspect du Fahrenheit dans sa forme la plus pure et la plus précieuse. L'ouverture de violette et bergamote est plus intense et plus mémorable. Le cœur de cuir et bois de gaïac est plus riche et plus profond. La base de bois de santal, vétiver et musc est plus généreuse et plus persistante.\n\nFahrenheit Parfum est pour les hommes qui connaissent et aiment ce classique légendaire, et qui souhaitent le vivre dans sa forme la plus intense et la plus mémorable. Pour les collectionneurs et les connaisseurs de la parfumerie masculine classique, c'est un must absolu.\n\nMaison Numidia propose ce parfum Dior authentique avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Violette intense", "Bergamote", "Mandarine"],
      "heart": ["Cuir profond", "Bois de gaïac", "Vétiver"],
      "base": ["Bois de santal intense", "Musc animal", "Ambre profond"]
    },
    "family": "Boisé Cuiré",
    "occasions": ["Soirée", "Occasions importantes", "Hiver"],
    "seasons": ["Automne", "Hiver"],
    "longevity": 5,
    "sillage": 5,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["dior-fahrenheit", "fahrenheit-dior", "dior-sauvage-parfum"]
  }
];

const allSlugs = new Set([...existingSlugs, ...newProducts.map(p => p.slug)]);
let errors = 0;
for (const p of newProducts) {
  if (existingSlugs.has(p.slug)) { console.error(`DUPLICATE: ${p.slug}`); errors++; }
  for (const r of p.related) {
    if (!allSlugs.has(r)) { console.error(`MISSING related "${r}" in ${p.slug}`); errors++; }
  }
}
if (errors > 0) { console.error(`${errors} erreur(s) — abandon`); process.exit(1); }

data.products.push(...newProducts);
writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf8');
console.log(`✅ ${newProducts.length} produits ajoutés — total: ${data.products.length} produits`);
