import { readFileSync, writeFileSync } from 'fs';
const filePath = 'data/products.json';
const data = JSON.parse(readFileSync(filePath, 'utf8'));
const existingSlugs = new Set(data.products.map(p => p.slug));

const newProducts = [
  {
    "id": "mugler-angel-elixir",
    "slug": "mugler-angel-elixir",
    "h1": "Mugler Angel Elixir Parfum Femme Algérie",
    "name": "Angel Elixir",
    "brand": "Mugler",
    "brandSlug": "mugler",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "EDP",
    "volume": "100ml",
    "price": 11900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/mugler-angel-elixir.jpg",
    "shortDescription": "Angel Elixir de Mugler réinterprète l'iconique Angel dans une version plus florale et moins sucrée. Bergamote pétillante, pivoine fraîche et vétiver boisé pour un Angel plus moderne et lumineux.",
    "description": "Mugler Angel Elixir est une réinterprétation moderne et audacieuse du légendaire Angel, l'un des parfums féminins les plus célèbres et les plus vendus au monde depuis son lancement révolutionnaire en 1992. Là où l'Angel original a imposé les notes gourmandes de patchouli et de cacao dans la parfumerie féminine, l'Elixir propose une vision plus fraîche et plus contemporaine.\n\nLa maison Mugler, fondée par le couturier Thierry Mugler, a toujours eu le goût du défi et de la transgression. Angel Elixir incarne cette philosophie : respecter l'héritage tout en osant le réinventer.\n\nL'ouverture de l'Elixir est immédiatement différente de l'original : la bergamote vive et les notes hespéridées créent une fraîcheur lumineuse qui n'existait pas dans le parfum de 1992. La pivoine fraîche s'y ajoute rapidement pour une dimension florale qui allège l'ensemble.\n\nLe cœur floral est la grande nouveauté de cette version. La rose et le jasmin s'épanouissent avec générosité, donnant à l'Elixir une féminité plus directe et plus accessible que l'Angel classique. Les notes de patchouli sont présentes mais beaucoup plus discrètes.\n\nLa base conserve quelques caractéristiques de l'Angel original — le patchouli et la vanille — mais dans des proportions nettement réduites. Le vétiver et le musc blanc créent un fond plus boisé et moins sucré, plus adapté aux femmes qui trouvaient l'Angel original trop intense.\n\nDisponible chez Maison Numidia, livraison dans les 58 wilayas d'Algérie par Yalidine, paiement à la réception.",
    "notes": {
      "top": ["Bergamote", "Pivoine", "Citron"],
      "heart": ["Rose", "Jasmin", "Patchouli"],
      "base": ["Vétiver", "Vanille", "Musc blanc", "Patchouli"]
    },
    "family": "Floral Boisé",
    "occasions": ["Quotidien", "Bureau", "Rendez-vous"],
    "seasons": ["Printemps", "Automne"],
    "longevity": 4,
    "sillage": 4,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["mugler-alien-goddess-intense", "dior-j-adore-infinissime", "lancome-idole-aura"]
  },
  {
    "id": "mugler-alien-goddess-intense",
    "slug": "mugler-alien-goddess-intense",
    "h1": "Mugler Alien Goddess Intense Parfum Femme Algérie",
    "name": "Alien Goddess Intense",
    "brand": "Mugler",
    "brandSlug": "mugler",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "EDP Intense",
    "volume": "90ml",
    "price": 11900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/mugler-alien-goddess-intense.jpg",
    "shortDescription": "Alien Goddess Intense de Mugler intensifie la divinité solaire de l'Alien Goddess. Fleur d'oranger, jasmin enivrant et vanille bourbon crémeuse dans une version plus profonde et plus enveloppante.",
    "description": "Mugler Alien Goddess Intense est l'expression la plus puissante et la plus divine de l'Alien Goddess, parfum féminin lancé en 2021 comme héritière moderne du légendaire Alien. Cette version Intense amplifie chaque note, révélant la déesse intérieure avec plus de force et de présence.\n\nL'Alien original, lancé en 2005, était une ode au mystère et à l'étrangeté avec ses notes florales blanches et sa couleur jaune topaze iconique. L'Alien Goddess a modernisé ce héritage en y ajoutant une dimension plus lumineuse et plus florale. La version Intense va encore plus loin dans l'intensité et la persistance.\n\nL'ouverture est solaire et envoûtante : la bergamote crémeuse et la fleur d'oranger s'imposent avec une générosité immédiate. Cette première impression est chaleureuse et lumineuse, évoquant le soleil méditerranéen sur une peau dorée.\n\nLe cœur est le triomphe du jasmin sambac, l'une des matières premières les plus précieuses et les plus envoûtantes de la parfumerie. Ici, dans la version Intense, il s'exprime avec encore plus de générosité et de richesse. La rose blanche l'accompagne dans une harmonie florale majestueuse.\n\nLa base est dominée par la vanille bourbon de Madagascar, crémeuse et douce, soutenue par le bois de santal et un musc ambré. Cette base est enveloppante et persiste longtemps, créant un sillage chaleureux et inoubliable.\n\nDisponible chez Maison Numidia, livraison dans les 58 wilayas d'Algérie par Yalidine, paiement à la réception.",
    "notes": {
      "top": ["Bergamote", "Fleur d'oranger", "Citron"],
      "heart": ["Jasmin sambac", "Rose blanche", "Iris"],
      "base": ["Vanille bourbon", "Bois de santal", "Musc ambré"]
    },
    "family": "Floral Oriental",
    "occasions": ["Soirée", "Rendez-vous", "Automne-Hiver"],
    "seasons": ["Automne", "Hiver"],
    "longevity": 5,
    "sillage": 5,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["mugler-angel-elixir", "ysl-black-opium-vive", "givenchy-irresistible-rose-velvet"]
  },
  {
    "id": "lancome-idole-aura",
    "slug": "lancome-idole-aura",
    "h1": "Lancôme Idôle Aura Parfum Femme Algérie",
    "name": "Idôle Aura",
    "brand": "Lancôme",
    "brandSlug": "lancome",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "EDP",
    "volume": "100ml",
    "price": 11900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/lancome-idole-aura.jpg",
    "shortDescription": "Idôle Aura de Lancôme est une version florale plus lumineuse et pétillante de l'Idôle. Rose et litchi sur fond de musc poudré pour une fragrance féminine fraîche et optimiste.",
    "description": "Lancôme Idôle Aura est une interprétation estivale et lumineuse de l'Idôle, le parfum féminin phare lancé en 2019 qui a su conquérir une génération entière de femmes modernes. Là où l'Idôle original proposait un floral clean et contemporain, l'Aura ajoute une dimension pétillante et solaire qui le rend particulièrement adapté aux saisons chaudes.\n\nLa ligne Idôle de Lancôme est née d'une vision clairement contemporaine : créer un parfum pour une femme moderne, indépendante et inspirante. L'Aura prolonge cette philosophie en y ajoutant une note de légèreté et d'optimisme qui correspond parfaitement à l'air du temps.\n\nL'ouverture est immédiatement fraîche et fruitée : le litchi rose et la bergamote créent une première impression pétillante et séduisante. Les notes de framboise ajoutent une touche sucrée et moderne qui attire l'attention.\n\nLe cœur est dominé par la rose, ingrédient signature de la maison Lancôme. Ici, c'est une rose rose fraîche et légèrement fruitée qui s'exprime, différente de la rose classique des parfums traditionnels. Le jasmin apporte une douceur florale subtile.\n\nLa base poudreuse et musquée est délicate et persistante. Le musc blanc et l'ambre léger créent un fond aérien qui reste sur la peau de manière très naturelle, comme si le parfum faisait partie de vous.\n\nDisponible chez Maison Numidia, livraison dans les 58 wilayas d'Algérie par Yalidine, paiement à la réception.",
    "notes": {
      "top": ["Litchi", "Bergamote", "Framboise"],
      "heart": ["Rose rose", "Jasmin", "Pivoine"],
      "base": ["Musc blanc", "Ambre léger", "Cèdre"]
    },
    "family": "Floral Fruité",
    "occasions": ["Quotidien", "Printemps-Été", "Bureau"],
    "seasons": ["Printemps", "Été"],
    "longevity": 3,
    "sillage": 3,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["lancome-idole-le-parfum", "lancome-la-vie-est-belle-florale", "dior-miss-dior-blooming-bouquet"]
  },
  {
    "id": "lancome-tresor-in-love",
    "slug": "lancome-tresor-in-love",
    "h1": "Lancôme Trésor In Love Parfum Femme Algérie",
    "name": "Trésor In Love",
    "brand": "Lancôme",
    "brandSlug": "lancome",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "EDP",
    "volume": "100ml",
    "price": 10900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/lancome-tresor-in-love.jpg",
    "shortDescription": "Trésor In Love de Lancôme est une version fraîche et romantique du légendaire Trésor. Rose, pivoine et pêche pour un parfum féminin printanier plein de légèreté et d'amour.",
    "description": "Lancôme Trésor In Love est la déclinaison la plus légère et la plus romantique du Trésor, le parfum féminin iconique lancé en 1990 par Lancôme. Là où le Trésor original est un floral aldéhydé profond et classique, In Love propose une vision plus contemporaine et plus printanière de ce trésor parfumé.\n\nLancé comme un hommage à l'amour et aux débuts de relation, Trésor In Love capture cette légèreté spécifique des premiers émois. C'est un parfum qui évoque les matinées ensoleillées, les fleurs dans les cheveux, et ce sentiment de légèreté incomparable qu'apporte le bonheur.\n\nL'ouverture est immédiatement printanière : la pêche rose juteuse et la bergamote créent une première impression fraîche et légèrement fruitée. La pivoine s'y ajoute rapidement pour un accord floral-fruité typiquement printanier.\n\nLe cœur est un bouquet romantique de rose et de pivoine, deux fleurs qui symbolisent l'amour et la fraîcheur. C'est un accord floral généreux mais jamais lourd, maintenu dans une légèreté aérienne par des notes de musc blanc.\n\nLa base est délicate et naturelle : musc blanc, ambre léger et bois doux créent un fond qui disparaît progressivement comme un beau souvenir, laissant juste ce qu'il faut pour que le parfum reste présent sans s'imposer.\n\nParfait pour les journées printanières et estivales en Algérie. Disponible chez Maison Numidia, livraison dans les 58 wilayas d'Algérie par Yalidine, paiement à la réception.",
    "notes": {
      "top": ["Pêche", "Bergamote", "Mandarine"],
      "heart": ["Rose", "Pivoine", "Jasmin"],
      "base": ["Musc blanc", "Ambre", "Bois doux"]
    },
    "family": "Floral Fruité",
    "occasions": ["Quotidien", "Printemps", "Romantique"],
    "seasons": ["Printemps", "Été"],
    "longevity": 3,
    "sillage": 3,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["lancome-idole-aura", "lancome-la-nuit-tresor-nu", "dior-miss-dior-blooming-bouquet"]
  },
  {
    "id": "dior-j-adore-infinissime",
    "slug": "dior-j-adore-infinissime",
    "h1": "Dior J'Adore Infinissime Parfum Femme Algérie",
    "name": "J'Adore Infinissime",
    "brand": "Dior",
    "brandSlug": "dior",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "EDP",
    "volume": "100ml",
    "price": 14900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/dior-j-adore-infinissime.jpg",
    "shortDescription": "J'Adore Infinissime de Dior est une version plus fraîche et magnolia-centrée du légendaire J'Adore. Magnolia lumineux, fleur d'oranger et poire pour une réinterprétation moderne de ce classique intemporel.",
    "description": "Dior J'Adore Infinissime est une réinterprétation fraîche et lumineuse du légendaire J'Adore, l'un des parfums féminins les plus vendus et les plus emblématiques au monde depuis son lancement en 1999. Là où le J'Adore original est un grand floral aldéhydé opulent, l'Infinissime propose une vision plus légère, plus contemporaine et plus accessible.\n\nLe mot 'Infinissime' évoque l'infini, le sublime poussé à son paroxysme. Ce parfum tente de capturer la perfection florale dans sa forme la plus pure et la plus lumineuse.\n\nL'ouverture est fraîche et fruitée : la poire juteuse et la mandarine créent une première impression légère et pétillante qui diffère de l'original plus floral. Cette tête fruitée est moderne et immédiatement séduisante.\n\nLe cœur est dominé par le magnolia, une fleur blanche aux facettes à la fois florales, crémeuses et légèrement épicées. Le jasmin sambac apporte sa sensualité caractéristique, et la rose ylang-ylang complète ce bouquet floral généreux.\n\nLa base conserve la signature enveloppante du J'Adore : le musc blanc, la vanille légère et le bois de santal créent un fond chaud et persistant, moins lourd que l'original mais tout aussi remarquable.\n\nUn parfum idéal pour les femmes qui aiment J'Adore mais recherchent quelque chose de plus aérien. Disponible chez Maison Numidia, livraison dans les 58 wilayas d'Algérie par Yalidine, paiement à la réception.",
    "notes": {
      "top": ["Poire", "Mandarine", "Bergamote"],
      "heart": ["Magnolia", "Jasmin sambac", "Rose ylang-ylang"],
      "base": ["Musc blanc", "Vanille", "Bois de santal"]
    },
    "family": "Floral Fruité",
    "occasions": ["Soirée", "Rendez-vous", "Quotidien"],
    "seasons": ["Printemps", "Été", "Automne"],
    "longevity": 4,
    "sillage": 4,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["dior-miss-dior-blooming-bouquet", "lancome-idole-aura", "chanel-gabrielle-essence"]
  },
  {
    "id": "dior-miss-dior-blooming-bouquet",
    "slug": "dior-miss-dior-blooming-bouquet",
    "h1": "Dior Miss Dior Blooming Bouquet Parfum Femme Algérie",
    "name": "Miss Dior Blooming Bouquet",
    "brand": "Dior",
    "brandSlug": "dior",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "EDT",
    "volume": "100ml",
    "price": 12900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/dior-miss-dior-blooming-bouquet.jpg",
    "shortDescription": "Miss Dior Blooming Bouquet est la version la plus légère et la plus fraîche de la famille Miss Dior. Pivoine rose, litchi et framboise pour un EDT printanier d'une légèreté absolue.",
    "description": "Dior Miss Dior Blooming Bouquet est la version la plus printanière et la plus accessible de la famille Miss Dior, l'une des franchises parfumées les plus réussies de la maison Dior. Lancé en 2007, ce parfum a su conquérir des millions de jeunes femmes à travers le monde grâce à sa légèreté rafraîchissante et son bouquet floral immédiatement agréable.\n\nLà où Miss Dior (EDP) est un floral intense et sophistiqué avec des notes de patchouli, le Blooming Bouquet est aérien, fruité et résolument printanier. Il incarne ce moment précis du printemps où les fleurs éclosent après l'hiver.\n\nL'ouverture est fraîche et légèrement fruitée : la pivoine rose et le litchi s'associent dans un accord floral-fruité immédiatement séduisant. Cette tête est un classique de la parfumerie féminine contemporaine, mais réalisée avec le savoir-faire inimitable de Dior.\n\nLe cœur est un bouquet printanier délicat : pivoine, rose et peony s'entrelacent dans une harmonie florale légère et féminine. C'est un accord simple dans ses intentions mais complexe dans son exécution, qui révèle des facettes différentes au fil du temps.\n\nLa base est légère comme une brise : musc blanc et bois doux créent un fond qui s'évapore progressivement, laissant une trace delicate et agréable. Un parfum idéal pour les journées chaudes du printemps et de l'été algérien.\n\nDisponible chez Maison Numidia, livraison dans les 58 wilayas d'Algérie par Yalidine, paiement à la réception.",
    "notes": {
      "top": ["Litchi", "Framboise", "Bergamote"],
      "heart": ["Pivoine", "Rose", "Jasmin"],
      "base": ["Musc blanc", "Bois doux", "Ambre léger"]
    },
    "family": "Floral Fruité",
    "occasions": ["Quotidien", "Printemps-Été", "Bureau"],
    "seasons": ["Printemps", "Été"],
    "longevity": 3,
    "sillage": 3,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["dior-j-adore-infinissime", "lancome-tresor-in-love", "lancome-idole-aura"]
  },
  {
    "id": "ysl-black-opium-vive",
    "slug": "ysl-black-opium-vive",
    "h1": "YSL Black Opium Vive Parfum Femme Algérie",
    "name": "Black Opium Vive",
    "brand": "Yves Saint Laurent",
    "brandSlug": "ysl",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "EDT",
    "volume": "90ml",
    "price": 10900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/ysl-black-opium-vive.jpg",
    "shortDescription": "Black Opium Vive d'YSL est une version fraîche et pétillante du légendaire Black Opium. Café blanc lumineux, poivre rose et jasmin pour un twist rafraîchissant sur la franchise iconique.",
    "description": "Yves Saint Laurent Black Opium Vive est une réinterprétation lumineuse et pétillante du légendaire Black Opium, l'un des parfums féminins contemporains les plus populaires au monde. Là où le Black Opium original propose un accord café-vanille intense et addictif, le Vive apporte une légèreté et une vivacité qui le rendent plus adapté aux saisons chaudes.\n\nLe Black Opium a révolutionné la parfumerie féminine en 2013 en introduisant le café comme note centrale dans un parfum féminin grand public. Depuis, de nombreuses déclinaisons ont été lancées pour explorer différentes facettes de cette signature olfactive unique.\n\nVive (qui signifie 'vif' ou 'vibrant' en français) propose une vision plus fraîche de cet univers. L'ouverture est pétillante et aromatique : le café blanc lumineux — une interprétation plus légère du café traditionnel — s'associe au poivre rose pour créer une tête épicée et surprenante.\n\nLe cœur est floral et légèrement fruité, dominé par le jasmin frais et la pêche blanche. Ces notes apportent une féminité différente de l'original, plus printanière et plus accessible. Le cœur de Vive est clairement destiné à une utilisation diurne.\n\nLa base conserve quelques éléments de la signature Black Opium — le musc et le bois — mais dans une version allégée qui laisse respirer la composition. Un excellent choix pour les femmes qui aiment l'univers Black Opium mais cherchent quelque chose de plus léger.\n\nDisponible chez Maison Numidia, livraison dans les 58 wilayas d'Algérie par Yalidine, paiement à la réception.",
    "notes": {
      "top": ["Café blanc", "Poivre rose", "Bergamote"],
      "heart": ["Jasmin", "Pêche blanche", "Rose"],
      "base": ["Musc blanc", "Bois de santal", "Vanille légère"]
    },
    "family": "Floral Aromatique",
    "occasions": ["Quotidien", "Bureau", "Printemps-Été"],
    "seasons": ["Printemps", "Été"],
    "longevity": 3,
    "sillage": 3,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["mugler-angel-elixir", "dior-miss-dior-blooming-bouquet", "givenchy-irresistible-rose-velvet"]
  },
  {
    "id": "givenchy-irresistible-rose-velvet",
    "slug": "givenchy-irresistible-rose-velvet",
    "h1": "Givenchy Irrésistible Rose Velvet Parfum Femme Algérie",
    "name": "Irrésistible Rose Velvet",
    "brand": "Givenchy",
    "brandSlug": "givenchy",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "EDP",
    "volume": "80ml",
    "price": 12900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/givenchy-irresistible-rose-velvet.jpg",
    "shortDescription": "Irrésistible Rose Velvet de Givenchy est une version plus intense et veloutée de l'Irrésistible. Rose damassée, musc soyeux et bois de santal pour un EDP féminin d'une sensualité enveloppante.",
    "description": "Givenchy Irrésistible Rose Velvet est la déclinaison la plus sensuelle et la plus intense de l'Irrésistible, le parfum féminin lancé par Givenchy en 2020. Là où l'Irrésistible original proposait un accord frais-floral lumineux, la Rose Velvet plonge dans des territoires plus profonds et plus veloutés, révélant une rose d'une sensualité incomparable.\n\nLa maison Givenchy, créée par le couturier Hubert de Givenchy en 1952, est synonyme d'élégance parisienne et de féminité sophistiquée. Chaque parfum est pensé comme un prolongement de cette vision fashion haute couture.\n\nL'ouverture est immédiatement rose : la bergamote et la rose fraîche créent une première impression florale lumineuse mais déjà plus profonde que l'original. Cette entrée en matière annonce clairement le caractère velvety de la composition.\n\nLe cœur est l'expression la plus intense de la rose dans la ligne Irrésistible. La rose damassée, cueillie à l'aube pour préserver ses composés aromatiques, s'exprime avec une richesse et une complexité remarquables. Elle est soutenue par le musc soyeux qui lui donne cette texture veloutée qui justifie le nom du parfum.\n\nLa base boisée et crémeuse parachève la composition. Le bois de santal et l'ambre rose créent un fond chaleureux et persistant qui transforme progressivement le parfum en quelque chose de plus intime et de plus sensuel.\n\nDisponible chez Maison Numidia, livraison dans les 58 wilayas d'Algérie par Yalidine, paiement à la réception.",
    "notes": {
      "top": ["Bergamote", "Rose fraîche", "Poivre rose"],
      "heart": ["Rose damassée", "Musc soyeux", "Jasmin"],
      "base": ["Bois de santal", "Ambre rose", "Musc blanc"]
    },
    "family": "Floral Rose",
    "occasions": ["Soirée", "Rendez-vous", "Automne"],
    "seasons": ["Automne", "Hiver", "Printemps"],
    "longevity": 4,
    "sillage": 4,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["parfums-de-marly-delina", "ex-nihilo-fleur-narcotique", "mugler-alien-goddess-intense"]
  },
  {
    "id": "versace-eros-flame-parfum",
    "slug": "versace-eros-flame-parfum",
    "h1": "Versace Eros Flame Parfum Homme Algérie",
    "name": "Eros Flame",
    "brand": "Versace",
    "brandSlug": "versace",
    "category": "parfums-homme",
    "gender": "homme",
    "concentration": "EDP",
    "volume": "100ml",
    "price": 10900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/versace-eros-flame-parfum.jpg",
    "shortDescription": "Eros Flame de Versace est le frère ardent de l'Eros. Orange rouge, poivre noir et bois de santal s'enflamment dans un EDP masculin chaud, épicé et terriblement séduisant.",
    "description": "Versace Eros Flame est la déclinaison la plus ardente et la plus épicée du légendaire Eros, ce parfum masculin qui depuis son lancement en 2012 incarne le désir et la passion à la manière de la maison italienne la plus flamboyante. Là où l'Eros original est frais et mentholé, l'Eros Flame est chaud, épicé et infernal dans le meilleur sens du terme.\n\nLe mythe d'Éros, dieu grec de l'amour, est réinterprété ici dans sa dimension la plus ardente. L'Eros Flame capture ce moment de désir intense où la raison cède la place aux instincts les plus profonds.\n\nL'ouverture est immédiatement ardente : l'orange rouge sanguine et le pomelo créent une tête fruitée mais chaude, très différente de la fraîcheur mentholée de l'Eros classique. Le poivre noir apporte une intensité épicée qui donne tout de suite le ton.\n\nLe cœur est boisé et épicé avec une générosité caractéristique de Versace. La rose, traitée de manière très masculine, s'associe à la cardamome et au géranium pour créer un accord complexe et séduisant. Ce cœur est le territoire de l'homme sûr de lui, séducteur et élégant.\n\nLa base est profonde et persistante : bois de santal, vétiver et ambre créent un fond chaud et animal qui reste sur la peau des heures durant. Un sillage remarquable qui ne passe pas inaperçu.\n\nDisponible chez Maison Numidia, livraison dans les 58 wilayas d'Algérie par Yalidine, paiement à la réception.",
    "notes": {
      "top": ["Orange rouge", "Pomelo", "Poivre noir"],
      "heart": ["Rose", "Cardamome", "Géranium"],
      "base": ["Bois de santal", "Vétiver", "Ambre", "Musc"]
    },
    "family": "Oriental Boisé Épicé",
    "occasions": ["Soirée", "Nuit", "Rendez-vous"],
    "seasons": ["Automne", "Hiver"],
    "longevity": 5,
    "sillage": 5,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["paco-rabanne-lady-million-lucky", "hugo-boss-bottled-parfum", "paco-rabanne-olympea-flora"]
  },
  {
    "id": "paco-rabanne-lady-million-lucky",
    "slug": "paco-rabanne-lady-million-lucky",
    "h1": "Paco Rabanne Lady Million Lucky Parfum Femme Algérie",
    "name": "Lady Million Lucky",
    "brand": "Paco Rabanne",
    "brandSlug": "paco-rabanne",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "EDP",
    "volume": "80ml",
    "price": 10900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/paco-rabanne-lady-million-lucky.jpg",
    "shortDescription": "Lady Million Lucky de Paco Rabanne est une version florale-fruitée plus légère de la gamme Lady Million. Citrus solaire, fleur d'oranger et bois blanc pour une Lady Million accessible et pétillante.",
    "description": "Paco Rabanne Lady Million Lucky est une déclinaison plus légère et plus estivale de la franchisée Lady Million, l'une des gammes féminines les plus populaires au monde depuis le lancement en 2010. Là où le Lady Million original est floral-chypré avec une touche mielleuse intense, le Lucky propose une version plus accessible et plus printanière.\n\nLe concept de chance et de luxe populaire est au cœur de la gamme Lady Million depuis ses débuts. Lucky perpétue cette philosophie tout en l'ouvrant vers un registre plus solaire et plus optimiste.\n\nL'ouverture est fraîche et ensoleillée : citrus, framboise et une touche de pêche créent une première impression fruitée et pétillante qui attire immédiatement. Cette tête est légère et joyeuse, parfaite pour les journées estivales.\n\nLe cœur est floral et solaire : la fleur d'oranger apporte sa douceur légèrement mielleuse, accompagnée de jasmin et de rose pour un accord floral généreux mais aérien. C'est un cœur optimiste et lumineux qui évoque les terrasses ensoleillées.\n\nLa base est boisée et légèrement musquée. Le bois blanc, le patchouli discret et le musc blanc créent un fond qui prolonge le parfum de manière agréable sans alourdir la composition.\n\nDisponible chez Maison Numidia, livraison dans les 58 wilayas d'Algérie par Yalidine, paiement à la réception.",
    "notes": {
      "top": ["Citrus", "Framboise", "Pêche"],
      "heart": ["Fleur d'oranger", "Jasmin", "Rose"],
      "base": ["Bois blanc", "Patchouli", "Musc blanc"]
    },
    "family": "Floral Fruité",
    "occasions": ["Quotidien", "Printemps-Été", "Bureau"],
    "seasons": ["Printemps", "Été"],
    "longevity": 3,
    "sillage": 3,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["paco-rabanne-olympea-flora", "dior-miss-dior-blooming-bouquet", "lancome-idole-aura"]
  },
  {
    "id": "paco-rabanne-olympea-flora",
    "slug": "paco-rabanne-olympea-flora",
    "h1": "Paco Rabanne Olympéa Flora Parfum Femme Algérie",
    "name": "Olympéa Flora",
    "brand": "Paco Rabanne",
    "brandSlug": "paco-rabanne",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "EDP",
    "volume": "80ml",
    "price": 10900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/paco-rabanne-olympea-flora.jpg",
    "shortDescription": "Olympéa Flora de Paco Rabanne est une version florale et marine de la déesse Olympéa. Fleur de sel, jasmin et bois de santal blanc pour une déesse qui se rafraîchit dans les vagues.",
    "description": "Paco Rabanne Olympéa Flora est une interprétation florale et marine de l'Olympéa, la déesse parfumée lancée en 2015 comme pendant féminin de l'Invictus. Là où l'Olympéa original est un oriental doux et poudré, la Flora propose une vision plus fraîche et plus aquatique de cette divinité olympienne.\n\nLa déesse Olympéa est une figure puissante et libre, en harmonie avec les éléments naturels. La version Flora la représente au bord de l'eau, les pieds dans les vagues, entourée de fleurs marines et de sel.\n\nL'ouverture est fraîche et iodée : la fleur de sel et les notes marines créent une première impression aquatique et vivifiante. La bergamote et le citron apportent une légèreté hespéridée qui complète cet accord initial.\n\nLe cœur est floral-marin d'une grande délicatesse. Le jasmin aquatique, traité de manière très contemporaine, s'associe à la fleur d'oranger pour créer un accord floral qui évoque les fleurs poussant au bord de la mer Méditerranée. Ce cœur est moderne et frais.\n\nLa base est crémeuse et boisée. Le bois de santal blanc, très doux et laiteux, crée un fond qui prolonge agréablement la composition. La vanille légère et le musc blanc ajoutent une douceur sensuelle à cet ensemble aquatique.\n\nDisponible chez Maison Numidia, livraison dans les 58 wilayas d'Algérie par Yalidine, paiement à la réception.",
    "notes": {
      "top": ["Fleur de sel", "Bergamote", "Citron"],
      "heart": ["Jasmin aquatique", "Fleur d'oranger", "Ambrette"],
      "base": ["Bois de santal blanc", "Vanille", "Musc blanc"]
    },
    "family": "Aquatique Floral",
    "occasions": ["Quotidien", "Printemps-Été", "Plage"],
    "seasons": ["Printemps", "Été"],
    "longevity": 3,
    "sillage": 3,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["paco-rabanne-lady-million-lucky", "maison-margiela-replica-beach-walk", "dior-j-adore-infinissime"]
  },
  {
    "id": "jean-paul-gaultier-ultra-male",
    "slug": "jean-paul-gaultier-ultra-male",
    "h1": "Jean Paul Gaultier Ultra Male Parfum Homme Algérie",
    "name": "Ultra Male",
    "brand": "Jean Paul Gaultier",
    "brandSlug": "jean-paul-gaultier",
    "category": "parfums-homme",
    "gender": "homme",
    "concentration": "EDT Intense",
    "volume": "75ml",
    "price": 9900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/jean-paul-gaultier-ultra-male.jpg",
    "shortDescription": "Ultra Male de Jean Paul Gaultier est la version la plus intense du légendaire Le Male. Poire, lavande et vanille dans une version amplifiée et plus séduisante de ce classique masculin iconique.",
    "description": "Jean Paul Gaultier Ultra Male est l'interprétation la plus intense et la plus séduisante du légendaire Le Male, le parfum masculin iconique créé par Jean Paul Gaultier en 1995 et présenté dans son flacon en forme de torse masculin tatoué. Ultra Male pousse chaque note de l'original dans ses retranchements, créant quelque chose d'irrésistible.\n\nLe Male original est un classique absolu de la parfumerie masculine, reconnaissable entre mille avec sa lavande fraîche et sa note de menthe poivrée. Ultra Male conserve l'ADN de cet accord tout en le transformant avec des notes plus gourmandes et plus sensuelles.\n\nL'ouverture est fruitée et aromatique : la poire fraîche et mûre s'associe à la lavande dans un accord qui rappelle instantanément la famille Le Male tout en proposant quelque chose de plus juteux et de plus moderne.\n\nLe cœur est le lieu où Ultra Male affirme sa singularité. La lavande et le cumin — note épicée souvent utilisée dans les parfums masculins orientaux — créent un accord complexe et légèrement animal. C'est une note audacieuse qui distingue clairement Ultra Male des autres versions de la gamme.\n\nLa base est le triomphe de la vanille et du musc. La vanille crémeuse, presque gourmande, s'associe au bois de santal et au musc blanc pour créer un fond persistant et enveloppant. Cette base explique pourquoi Ultra Male est si apprécié des femmes également.\n\nDisponible chez Maison Numidia, livraison dans les 58 wilayas d'Algérie par Yalidine, paiement à la réception.",
    "notes": {
      "top": ["Poire", "Lavande", "Bergamote"],
      "heart": ["Lavande", "Cumin", "Iris"],
      "base": ["Vanille", "Bois de santal", "Musc blanc", "Ambre"]
    },
    "family": "Oriental Aromatique",
    "occasions": ["Soirée", "Nuit", "Rendez-vous"],
    "seasons": ["Automne", "Hiver"],
    "longevity": 5,
    "sillage": 4,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["jean-paul-gaultier-scandal-absolu", "hugo-boss-bottled-parfum", "versace-eros-flame-parfum"]
  }
];

const allSlugs = new Set([...existingSlugs, ...newProducts.map(p => p.slug)]);
let errors = 0;
for (const p of newProducts) {
  if (existingSlugs.has(p.slug)) { console.error(`DUPLICATE: ${p.slug}`); errors++; }
  for (const r of p.related) {
    if (!allSlugs.has(r)) { console.error(`MISSING related "${r}" in ${p.slug}`); errors++; }
  }
}
if (errors > 0) { console.error(`${errors} erreur(s) — abandon`); process.exit(1); }
data.products.push(...newProducts);
writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf8');
console.log(`✅ ${newProducts.length} produits ajoutés — total: ${data.products.length} produits`);
