import { readFileSync, writeFileSync } from 'fs';
const filePath = 'data/products.json';
const data = JSON.parse(readFileSync(filePath, 'utf8'));
const existingSlugs = new Set(data.products.map(p => p.slug));

const newProducts = [
  {
    "id": "xerjoff-erba-pura",
    "slug": "xerjoff-erba-pura",
    "h1": "Xerjoff Erba Pura Parfum Unisexe Algérie",
    "name": "Erba Pura",
    "brand": "Xerjoff",
    "brandSlug": "xerjoff",
    "category": "parfums-orientaux",
    "gender": "unisexe",
    "concentration": "EDP",
    "volume": "100ml",
    "price": 18900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/xerjoff-erba-pura.jpg",
    "shortDescription": "Erba Pura de Xerjoff est un fruité solaire envoûtant, mêlant mandarine sicilienne et musc blanc dans une harmonie lumineuse. Un parfum unisexe d'exception au sillage remarquable.",
    "description": "Xerjoff Erba Pura est l'un des parfums niche les plus appréciés au monde, une ode à la Méditerranée ensoleillée traduite en fragrance. Créé par la maison italienne Xerjoff, ce jus iconique s'ouvre sur une explosion de mandarines siciliennes juteuses, mêlées à des notes de fruits tropicaux qui évoquent immédiatement les rivages méditerranéens sous le soleil estival.\n\nAu cœur du parfum, les fleurs blanches délicates s'entrelacent avec le musc, créant une transition douce et enveloppante. La base dévoile un musc blanc opulent, chaleureux et persistant, qui reste sur la peau pendant de longues heures avec une douceur incomparable.\n\nCe qui rend Erba Pura unique, c'est sa capacité à être à la fois frais et envoûtant, léger et présent. Le sillage est généreux sans être écrasant, parfait pour toutes les saisons mais particulièrement magnifique durant les mois chauds. En Algérie, où la chaleur méditerranéenne est reine, ce parfum trouve son expression la plus naturelle.\n\nLa maison Xerjoff, fondée à Turin en 2006, est connue pour l'excellence de ses matières premières et ses flacons de cristal travaillés à la main. Erba Pura est proposé dans un flacon élégant qui illustre parfaitement le savoir-faire artisanal de la maison.\n\nParfum unisexe par excellence, Erba Pura séduit autant les hommes que les femmes, les jeunes que les moins jeunes. Disponible chez Maison Numidia avec livraison dans les 58 wilayas d'Algérie par Yalidine, paiement à la réception.",
    "notes": {
      "top": ["Mandarine", "Citron", "Fruits tropicaux"],
      "heart": ["Fleurs blanches", "Musc", "Ambre"],
      "base": ["Musc blanc", "Bois de santal", "Cèdre"]
    },
    "family": "Fruité Boisé",
    "occasions": ["Quotidien", "Printemps-Été", "Rendez-vous"],
    "seasons": ["Printemps", "Été"],
    "longevity": 4,
    "sillage": 4,
    "inStock": true,
    "featured": true,
    "isOriental": true,
    "related": ["xerjoff-naxos", "kilian-love-dont-be-shy", "byredo-bal-d-afrique"]
  },
  {
    "id": "nishane-hacivat",
    "slug": "nishane-hacivat",
    "h1": "Nishane Hacivat Parfum Unisexe Algérie",
    "name": "Hacivat",
    "brand": "Nishane",
    "brandSlug": "nishane",
    "category": "parfums-orientaux",
    "gender": "unisexe",
    "concentration": "Extrait de Parfum",
    "volume": "100ml",
    "price": 19900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/nishane-hacivat.jpg",
    "shortDescription": "Hacivat de Nishane est un extrait de parfum aromatique boisé d'une élégance rare, alliant pamplemousse frais et iris profond sur un fond de vétiver fumé. Un jus de niche turc devenu culte.",
    "description": "Nishane Hacivat est le fleuron de la maison turque Nishane, l'une des références incontournables de la parfumerie niche contemporaine. Ce extrait de parfum unisexe est une véritable œuvre d'art olfactive, construite autour de la tension créative entre fraîcheur et profondeur.\n\nL'entrée est saisissante : pamplemousse vif et notes marines créent une fraîcheur immédiate, presque aquatique. Puis l'iris fait son entrée, floral et poudreux à la fois, apportant une sophistication qui distingue immédiatement Hacivat des parfums ordinaires. Le cœur évolue vers des accords boisés complexes où le vétiver joue un rôle central.\n\nLa base est fumée, terreuse et persistante. Le vétiver haïtien, combiné au patchouli et au bois de oud, crée un fond chaud et enveloppant qui dure des heures sur la peau. Cette dualité fraîcheur-profondeur fait de Hacivat un parfum pour toutes les saisons.\n\nNishane, fondée à Istanbul en 2012, s'inspire du riche patrimoine ottoman tout en proposant une vision résolument contemporaine de la parfumerie de luxe. Le nom Hacivat fait référence au personnage du théâtre d'ombres traditionnel turc Karagöz, symbole d'élégance et de culture.\n\nAvec une longévité exceptionnelle et un sillage maîtrisé, Hacivat est le choix parfait pour ceux qui cherchent un parfum signature distinctif. Disponible chez Maison Numidia, livraison Yalidine 58 wilayas, paiement à la réception.",
    "notes": {
      "top": ["Pamplemousse", "Notes marines", "Citron"],
      "heart": ["Iris", "Poivre rose", "Géranium"],
      "base": ["Vétiver", "Patchouli", "Ambre", "Bois de oud"]
    },
    "family": "Aromatique Boisé",
    "occasions": ["Bureau", "Soirée", "Événement"],
    "seasons": ["Automne", "Printemps"],
    "longevity": 5,
    "sillage": 4,
    "inStock": true,
    "featured": false,
    "isOriental": true,
    "related": ["nishane-ambra-calabria", "byredo-gypsy-water", "memo-paris-african-leather"]
  },
  {
    "id": "nishane-ambra-calabria",
    "slug": "nishane-ambra-calabria",
    "h1": "Nishane Ambra Calabria Parfum Unisexe Algérie",
    "name": "Ambra Calabria",
    "brand": "Nishane",
    "brandSlug": "nishane",
    "category": "parfums-orientaux",
    "gender": "unisexe",
    "concentration": "Extrait de Parfum",
    "volume": "100ml",
    "price": 19900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/nishane-ambra-calabria.jpg",
    "shortDescription": "Ambra Calabria de Nishane capture l'essence de la Calabre italienne dans un extrait solaire et ambré. Bergamote lumineuse sur un cœur fleuri et une base ambrée chaude, pour une fragrance unisexe d'exception.",
    "description": "Nishane Ambra Calabria est un voyage sensoriel vers les côtes ensoleillées de la Calabre, la pointe du Sud de l'Italie où poussent les bergamotiers les plus précieux au monde. Cet extrait de parfum unisexe capte l'essence même de cette région magnifique dans un flacon d'exception.\n\nL'ouverture est un éclat de bergamote pure, lumineuse et pétillante, accompagnée de notes d'agrumes qui évoquent immédiatement le soleil méditerranéen. Cette fraîcheur initiale est d'une qualité supérieure, utilisant de la bergamote d'origine contrôlée pour garantir une authenticité olfactive parfaite.\n\nLe cœur dévoile une dimension florale délicate, où la fleur de néroli et l'iris apportent une élégance feminine mais accessible aux deux genres. Cette transition est fluide, presque imperceptible, comme un coucher de soleil calabrais.\n\nLa base ambrée est chaude, sensuelle et enveloppante. L'ambre, la vanille et le musc blanc créent un fond qui perdure longuement sur la peau, transformant le parfum initial frais en quelque chose de plus intime et de plus personnel au fil des heures.\n\nUn parfum idéal pour le printemps et l'été algérien, apportant cette élégance méditerranéenne qui correspond si bien au caractère solaire et chaleureux de notre pays. Disponible chez Maison Numidia avec livraison dans les 58 wilayas.",
    "notes": {
      "top": ["Bergamote calabraise", "Citron", "Mandarine"],
      "heart": ["Néroli", "Iris", "Rose"],
      "base": ["Ambre", "Musc blanc", "Vanille", "Cèdre"]
    },
    "family": "Agrumes Ambré",
    "occasions": ["Quotidien", "Printemps-Été", "Détente"],
    "seasons": ["Printemps", "Été"],
    "longevity": 4,
    "sillage": 3,
    "inStock": true,
    "featured": false,
    "isOriental": true,
    "related": ["nishane-hacivat", "acqua-di-parma-colonia", "byredo-gypsy-water"]
  },
  {
    "id": "diptyque-philosykos",
    "slug": "diptyque-philosykos",
    "h1": "Diptyque Philosykos Parfum Unisexe Algérie",
    "name": "Philosykos",
    "brand": "Diptyque",
    "brandSlug": "diptyque",
    "category": "parfums-femme",
    "gender": "unisexe",
    "concentration": "EDP",
    "volume": "75ml",
    "price": 17900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/diptyque-philosykos.jpg",
    "shortDescription": "Philosykos de Diptyque est une ode au figuier grec, capturant avec une précision botanique le bois, les feuilles et le fruit dans leur fraîcheur naturelle. Un chef-d'œuvre de la parfumerie niche.",
    "description": "Diptyque Philosykos est l'un des parfums les plus poétiques et les plus réalistes jamais créés. Son nom signifie 'ami du figuier' en grec ancien, et cette fragrance tient pleinement sa promesse : elle restitue avec une fidélité troublante l'arbre entier, des racines aux fruits.\n\nCréé en 1996 et reformulé en 2006, Philosykos s'ouvre sur les notes vertes et légèrement laiteuses du figuier fraîchement coupé. Cette ouverture est unique : on perçoit simultanément la sève du bois, la fraîcheur des feuilles et la rondeur crémeuse du fruit. Ce n'est pas une imitation — c'est presque une transcription chimique d'un figuier grec en plein soleil.\n\nLe cœur préserve cette authenticité botanique, avec des notes florales très discrètes qui représentent les fleurs invisibles du figuier, cachées dans les akènes. La base boisée, légèrement fumée et crémeuse, rappelle le bois de figuier séché au soleil méditerranéen.\n\nMaison Diptyque, fondée à Paris en 1961, est l'une des maisons pionnières de la parfumerie niche. Chaque parfum est une histoire, un voyage, une émotion distillée. Philosykos incarne parfaitement cette philosophie.\n\nUnisexe au sens le plus authentique du terme, Philosykos convient à toutes les personnalités qui apprécient la nature et l'authenticité. Idéal pour le printemps et l'été algérien. Livraison Yalidine 58 wilayas, paiement à la réception chez Maison Numidia.",
    "notes": {
      "top": ["Figue verte", "Feuille de figuier", "Cèdre"],
      "heart": ["Bois de figuier", "Lait de figue", "Fleur de figuier"],
      "base": ["Bois blanc", "Cèdre", "Musc"]
    },
    "family": "Vert Boisé",
    "occasions": ["Quotidien", "Nature", "Printemps-Été"],
    "seasons": ["Printemps", "Été"],
    "longevity": 3,
    "sillage": 3,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["diptyque-do-son", "acqua-di-parma-colonia", "byredo-gypsy-water"]
  },
  {
    "id": "diptyque-do-son",
    "slug": "diptyque-do-son",
    "h1": "Diptyque Do Son Parfum Femme Algérie",
    "name": "Do Son",
    "brand": "Diptyque",
    "brandSlug": "diptyque",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "EDP",
    "volume": "75ml",
    "price": 17900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/diptyque-do-son.jpg",
    "shortDescription": "Do Son de Diptyque est une brise florale marine inspirée de la baie de Do Son au Vietnam. Tubéreuse vaporeuse, rose délicate et brise océanique pour un parfum féminin d'une légèreté absolue.",
    "description": "Diptyque Do Son est un parfum qui raconte l'histoire d'un souvenir de voyage : une nuit à la baie de Do Son au nord du Vietnam, où les bougainvilliers blancs se mêlent à la brise marine et les tiges de tubéreuse flottent dans l'air humide et chaud.\n\nL'entrée est immédiatement évocatrice : une brise légèrement salée, presque iodée, porte les premières notes florales. La tubéreuse, fleur mythique de la parfumerie, s'exprime ici dans toute sa complexité — crémeuse, légèrement camphée, intensément florale mais jamais écrasante. La rose ajoute une douceur veloutée qui tempère la puissance de la tubéreuse.\n\nLe cœur est un accord floral marin d'une rare délicatesse. Les notes de musc blanc apportent une douceur voilée, presque poudreuse, qui rappelle le coton blanchi au soleil. Ce parfum est une invitation à la rêverie et à l'évasion.\n\nLa base, légère et persistante, conserve cette atmosphère vaporeuse sans alourdir la composition. Do Son reste aérien du premier au dernier instant, ce qui en fait un compagnon idéal pour les journées chaudes ou les soirées estivales algériennes.\n\nParfum féminin par essence, Do Son convient aux femmes qui aiment les floraux aquatiques, élégants sans être trop sérieux. Une fragrance de liberté et de légèreté. Disponible chez Maison Numidia, livraison dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Brise marine", "Bergamote", "Rose"],
      "heart": ["Tubéreuse", "Rose", "Musc blanc"],
      "base": ["Bois blanc", "Musc", "Cèdre"]
    },
    "family": "Floral Aquatique",
    "occasions": ["Quotidien", "Printemps-Été", "Détente"],
    "seasons": ["Printemps", "Été"],
    "longevity": 3,
    "sillage": 3,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["diptyque-philosykos", "maison-margiela-replica-beach-walk", "jo-malone-peony-blush-suede"]
  },
  {
    "id": "penhaligons-halfeti",
    "slug": "penhaligons-halfeti",
    "h1": "Penhaligon's Halfeti Parfum Unisexe Algérie",
    "name": "Halfeti",
    "brand": "Penhaligon's",
    "brandSlug": "penhaligons",
    "category": "parfums-orientaux",
    "gender": "unisexe",
    "concentration": "EDP",
    "volume": "100ml",
    "price": 20900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/penhaligons-halfeti.jpg",
    "shortDescription": "Halfeti de Penhaligon's capture l'essence mystérieuse de ce village turc submergé par le barrage de l'Euphrate. Un oriental boisé profond et envoûtant, aux notes de rose turque, oud et ambre.",
    "description": "Penhaligon's Halfeti est l'un des parfums orientaux les plus célèbres de la maison londonienne fondée en 1870. Inspiré par le village de Halfeti, en Turquie, autrefois submergé par les eaux du barrage de Birecik sur l'Euphrate, ce parfum capture quelque chose d'à la fois perdu et éternel.\n\nHalfeti est également connu pour être le seul endroit au monde où pousse naturellement la rose noire de Turquie — une rose si sombre qu'elle semble absorber la lumière. Cette rose mystérieuse est au cœur du parfum, entourée d'épices orientales qui évoquent le Grand Bazar d'Istanbul.\n\nL'ouverture est épicée et fruitée : bergamote, baies de poivre roses et citron créent un premier accord dynamique et lumineux. La transition vers le cœur se fait avec fluidité, révélant la rose turque dans toute sa complexité florale et légèrement épicée.\n\nLa base est riche et profonde : oud, vétiver fumé, ambre chaud et musc créent un sillage envoûtant qui persiste des heures. C'est ici que le parfum révèle sa vraie nature orientale, avec une sophistication qui rappelle les grandes maisons de parfumerie du Moyen-Orient.\n\nParfait pour les soirées algériennes automnales et hivernales, Halfeti est un parfum de caractère pour ceux qui n'ont pas peur de laisser une impression durable. Disponible chez Maison Numidia, livraison Yalidine 58 wilayas, paiement à la réception.",
    "notes": {
      "top": ["Bergamote", "Citron", "Poivre rose", "Baies"],
      "heart": ["Rose turque", "Oud", "Géranium", "Patchouli"],
      "base": ["Vétiver", "Ambre", "Musc", "Labdanum"]
    },
    "family": "Oriental Floral Boisé",
    "occasions": ["Soirée", "Événement", "Hiver"],
    "seasons": ["Automne", "Hiver"],
    "longevity": 5,
    "sillage": 5,
    "inStock": true,
    "featured": false,
    "isOriental": true,
    "related": ["nishane-hacivat", "amouage-beloved-homme", "initio-oud-for-greatness"]
  },
  {
    "id": "parfums-de-marly-delina",
    "slug": "parfums-de-marly-delina",
    "h1": "Parfums de Marly Delina Parfum Femme Algérie",
    "name": "Delina",
    "brand": "Parfums de Marly",
    "brandSlug": "parfums-de-marly",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "EDP",
    "volume": "75ml",
    "price": 22900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/parfums-de-marly-delina.jpg",
    "shortDescription": "Delina de Parfums de Marly est le parfum féminin niche le plus iconique de ces dernières années. Rose pivoine lumineuse sur fond de litchi et de musc vanillé, dans un flacon rose d'une élégance royale.",
    "description": "Parfums de Marly Delina est sans conteste l'un des parfums féminins niche les plus populaires et les plus admirés de la décennie. Depuis son lancement en 2017, ce jus a conquis des millions de femmes à travers le monde, et son succès ne se dément pas.\n\nInspirée par les jardins du Château de Marly, résidence de chasse de Louis XIV, la maison Parfums de Marly perpétue l'art de vivre français du XVIIIe siècle dans ses créations olfactives. Delina est la quintessence de cette philosophie : élégance, féminité et raffinement.\n\nL'ouverture est une explosion de fraîcheur florale : la pivoine et la rose s'unissent au litchi juteux pour créer un accord frais et légèrement fruité d'une grande luminosité. Cette première impression est à la fois délicate et affirmée, féminine sans être sucrée.\n\nLe cœur révèle progressivement sa complexité. La rose de mai, l'une des matières les plus précieuses de la parfumerie, apporte une profondeur florale remarquable. Les épices douces et le néroli ajoutent une dimension chaude et lumineuse.\n\nLa base est sensuelle et persistante : musc blanc, vanille et ambre créent un sillage chaleureux qui reste présent des heures après application. Delina est un parfum qui évolue magnifiquement au fil du temps, se révélant différemment à chaque heure.\n\nDisponible chez Maison Numidia en flacon de 75ml, livraison dans les 58 wilayas d'Algérie par Yalidine, paiement à la réception.",
    "notes": {
      "top": ["Pivoine", "Litchi", "Bergamote", "Feuille de cassis"],
      "heart": ["Rose de mai", "Rose turque", "Néroli", "Poivre rose"],
      "base": ["Musc blanc", "Vanille", "Ambre", "Vétiver"]
    },
    "family": "Floral Fruité",
    "occasions": ["Quotidien", "Rendez-vous", "Soirée"],
    "seasons": ["Printemps", "Été", "Automne"],
    "longevity": 5,
    "sillage": 4,
    "inStock": true,
    "featured": true,
    "isOriental": false,
    "related": ["parfums-de-marly-pegasus", "frederic-malle-portrait-of-a-lady", "kilian-love-dont-be-shy"]
  },
  {
    "id": "parfums-de-marly-pegasus",
    "slug": "parfums-de-marly-pegasus",
    "h1": "Parfums de Marly Pegasus Parfum Homme Algérie",
    "name": "Pegasus",
    "brand": "Parfums de Marly",
    "brandSlug": "parfums-de-marly",
    "category": "parfums-homme",
    "gender": "homme",
    "concentration": "EDP",
    "volume": "125ml",
    "price": 22900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/parfums-de-marly-pegasus.jpg",
    "shortDescription": "Pegasus de Parfums de Marly est le pendant masculin de Delina, une référence absolue de la parfumerie niche. Lavande, bergamote et heliotrope s'unissent à une base boisée vanillée pour un résultat exceptionnel.",
    "description": "Parfums de Marly Pegasus est l'un des parfums masculins niche les plus populaires de sa génération, un véritable monument de la parfumerie contemporaine. Depuis son lancement, ce jus olfactif a su conquérir les hommes les plus exigeants, alliant sophistication classique et modernité.\n\nNommé en hommage au cheval ailé de la mythologie grecque, Pegasus porte bien son nom : il est à la fois puissant et élégant, terrestre et céleste. La maison Parfums de Marly, inspirée de la Cour de Versailles, a créé un parfum qui incarne l'idéal du gentleman moderne.\n\nL'ouverture est classique et rassurante : bergamote vive, lavande provençale et une pointe de poivre créent un accord frais et aromatique immédiatement plaisant. Cette première impression évoque les grands fougères masculins des décennies passées, mais revisités avec une sophistication contemporaine.\n\nLe cœur est dominé par l'héliotrope, une fleur rare aux facettes poudreuses et légèrement vanillées. Ce choix est audacieux et constitue la signature distinctive de Pegasus parmi les parfums masculins. Le jasmin et la géranium apportent des touches florales subtiles.\n\nLa base est boisée, chaude et crémeuse. Le santal, la vanille et le musc blanc créent un fond enveloppant qui dure des heures avec un sillage délicat mais remarqué. Un parfum qui reste présent sans jamais être envahissant.\n\nDisponible chez Maison Numidia, livraison Yalidine dans les 58 wilayas d'Algérie, paiement à la réception.",
    "notes": {
      "top": ["Bergamote", "Lavande", "Poivre"],
      "heart": ["Héliotrope", "Jasmin", "Géranium"],
      "base": ["Bois de santal", "Vanille", "Musc blanc", "Cèdre"]
    },
    "family": "Aromatique Boisé Poudré",
    "occasions": ["Bureau", "Quotidien", "Soirée"],
    "seasons": ["Automne", "Hiver", "Printemps"],
    "longevity": 5,
    "sillage": 4,
    "inStock": true,
    "featured": true,
    "isOriental": false,
    "related": ["parfums-de-marly-layton", "parfums-de-marly-delina", "amouage-dia-homme"]
  },
  {
    "id": "parfums-de-marly-layton",
    "slug": "parfums-de-marly-layton",
    "h1": "Parfums de Marly Layton Parfum Homme Algérie",
    "name": "Layton",
    "brand": "Parfums de Marly",
    "brandSlug": "parfums-de-marly",
    "category": "parfums-homme",
    "gender": "homme",
    "concentration": "EDP",
    "volume": "125ml",
    "price": 22900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/parfums-de-marly-layton.jpg",
    "shortDescription": "Layton de Parfums de Marly est un EDP masculin gourmand-boisé d'exception. Pomme fraîche et lavande s'épanouissent sur un fond de vanille et d'ambre pour un parfum consensuel mais sophistiqué.",
    "description": "Parfums de Marly Layton est une autre icône de la maison, aux côtés de Pegasus et Delina. Ce parfum masculin gourmand-boisé a su trouver son public en proposant un équilibre parfait entre accessibilité et sophistication, entre fraîcheur fruitée et profondeur boisée.\n\nL'ouverture de Layton est immédiatement sympathique et enveloppante. La pomme fraîche, la bergamote et la lavande créent un accord frais, légèrement sucré, qui rappelle les champs de Provence tout en ayant une dimension fruitée moderne. Cette entrée en matière plaisante explique en partie l'immense popularité du parfum.\n\nLe cœur est floral-épicé avec une élégance maîtrisée. La violette, le jasmin et le géranium apportent des nuances florales qui enrichissent la composition sans la féminiser. Les épices douces (cardamome, poivre) maintiennent le caractère masculin de l'accord.\n\nC'est la base qui fait de Layton un parfum véritablement remarquable. Vanille, bois de guaïac, patchouli et musc créent un fond gourmand et boisé d'une longueur impressionnante. Ce sillage chaud et enveloppant reste présent de nombreuses heures, captivant par sa douceur sophistiquée.\n\nIdéal pour les soirées automnales et hivernales en Algérie, mais suffisamment versatile pour être porté en toute saison. Un parfum de caractère pour homme moderne. Disponible chez Maison Numidia, livraison dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Pomme", "Lavande", "Bergamote"],
      "heart": ["Violette", "Jasmin", "Géranium", "Cardamome"],
      "base": ["Vanille", "Bois de guaïac", "Patchouli", "Musc"]
    },
    "family": "Gourmand Boisé",
    "occasions": ["Soirée", "Bureau", "Rendez-vous"],
    "seasons": ["Automne", "Hiver", "Printemps"],
    "longevity": 5,
    "sillage": 4,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["parfums-de-marly-pegasus", "kilian-angels-share", "amouage-beloved-homme"]
  },
  {
    "id": "montale-arabians-tonka",
    "slug": "montale-arabians-tonka",
    "h1": "Montale Arabians Tonka Parfum Unisexe Algérie",
    "name": "Arabians Tonka",
    "brand": "Montale",
    "brandSlug": "montale",
    "category": "parfums-orientaux",
    "gender": "unisexe",
    "concentration": "EDP",
    "volume": "100ml",
    "price": 12900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/montale-arabians-tonka.jpg",
    "shortDescription": "Arabians Tonka de Montale est un EDP oriental gourmand d'une douceur addictive. La fève tonka crémeuse s'unit aux épices arabes et au oud pour créer une fragrance enveloppante et chaude.",
    "description": "Montale Arabians Tonka est un hommage olfactif aux parfums traditionnels arabes, réinterprétés avec la sophistication de la maison parisienne Montale. Ce parfum unisexe combine le meilleur des deux mondes : l'héritage oriental millénaire et la modernité de la parfumerie niche contemporaine.\n\nFondée en 2003 par Pierre Montale, la maison éponyme s'est imposée comme une référence incontournable de la parfumerie orientale accessible. Avec ses flacons de métal caractéristiques et ses compositions généreuses, Montale a su conquérir les amateurs de parfums en Algérie et dans tout le Maghreb.\n\nArabians Tonka s'ouvre sur des notes épicées et légèrement sucrées qui évoquent immédiatement les souks arabes : cannelle, cardamome et safran créent une première impression chaleureuse et accueillante. Cette ouverture est envoûtante sans être agressive.\n\nLe cœur révèle la fève tonka dans toute sa splendeur crémeuse et vanillée. Combinée aux roses et au jasmin oriental, elle crée un accord floral-gourmand d'une complexité remarquable. Le oud apporte une dimension boisée et légèrement fumée qui ancre le parfum dans la tradition orientale.\n\nLa base est riche, chaude et persistante. Ambre, musc et bois de santal créent un fond enveloppant qui reste sur la peau des heures durant. Un parfum idéal pour les soirées algériennes, les cérémonies et les occasions spéciales.\n\nDisponible chez Maison Numidia avec livraison dans les 58 wilayas d'Algérie par Yalidine, paiement à la réception.",
    "notes": {
      "top": ["Cannelle", "Cardamome", "Safran"],
      "heart": ["Fève tonka", "Rose", "Jasmin", "Oud"],
      "base": ["Ambre", "Musc", "Bois de santal", "Vanille"]
    },
    "family": "Oriental Gourmand",
    "occasions": ["Soirée", "Événement", "Hiver"],
    "seasons": ["Automne", "Hiver"],
    "longevity": 5,
    "sillage": 4,
    "inStock": true,
    "featured": false,
    "isOriental": true,
    "related": ["initio-oud-for-greatness", "amouage-beloved-homme", "penhaligons-halfeti"]
  },
  {
    "id": "ex-nihilo-fleur-narcotique",
    "slug": "ex-nihilo-fleur-narcotique",
    "h1": "Ex Nihilo Fleur Narcotique Parfum Femme Algérie",
    "name": "Fleur Narcotique",
    "brand": "Ex Nihilo",
    "brandSlug": "ex-nihilo",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "EDP",
    "volume": "100ml",
    "price": 21900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/ex-nihilo-fleur-narcotique.jpg",
    "shortDescription": "Fleur Narcotique d'Ex Nihilo est un EDP féminin hypnotique alliant rose blanche et tubéreuse à une base musquée enveloppante. Un des parfums niche parisiens les plus désirés de sa génération.",
    "description": "Ex Nihilo Fleur Narcotique est la création la plus emblématique de la maison parisienne Ex Nihilo, fondée en 2013 avec l'ambition de révolutionner la parfumerie de niche grâce à des technologies de personnalisation avancées. Ce parfum féminin est devenu en quelques années l'une des références les plus citées et les plus copiées de la parfumerie niche.\n\nLe nom \"Fleur Narcotique\" annonce la couleur : cette fleur est envoûtante, presque hypnotique. L'ouverture associe des notes de bergamote lumineuse et de pamplemousse rose à des premières facettes florales, créant une entrée fraîche et séduisante.\n\nLe cœur est dominé par la tubéreuse, l'une des fleurs les plus narcotiques de la parfumerie. Ici, elle est traitée avec une délicatesse rare : crémeuse et envoûtante mais jamais lourde, associée à la rose blanche et au muguet pour créer un accord floral d'une beauté troublante. Le jasmin apporte une sensualité supplémentaire à cet accord déjà magnifique.\n\nLa base musquée et ambrée est longue et persistante, créant un sillage doux et sensuel qui reste présent des heures. Ce fond poudré et chaleureux est parfait pour les soirées et les occasions spéciales.\n\nDisponible chez Maison Numidia en flacon de 100ml, livraison dans les 58 wilayas d'Algérie par Yalidine, paiement à la réception.",
    "notes": {
      "top": ["Bergamote", "Pamplemousse rose", "Litchi"],
      "heart": ["Tubéreuse", "Rose blanche", "Muguet", "Jasmin"],
      "base": ["Musc blanc", "Ambre", "Santal", "Vanille"]
    },
    "family": "Floral Musqué",
    "occasions": ["Soirée", "Rendez-vous", "Événement"],
    "seasons": ["Printemps", "Été", "Automne"],
    "longevity": 4,
    "sillage": 4,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["parfums-de-marly-delina", "frederic-malle-portrait-of-a-lady", "kilian-love-dont-be-shy"]
  },
  {
    "id": "serge-lutens-feminite-du-bois",
    "slug": "serge-lutens-feminite-du-bois",
    "h1": "Serge Lutens Féminité du Bois Parfum Femme Algérie",
    "name": "Féminité du Bois",
    "brand": "Serge Lutens",
    "brandSlug": "serge-lutens",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "EDP",
    "volume": "100ml",
    "price": 19900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/serge-lutens-feminite-du-bois.jpg",
    "shortDescription": "Féminité du Bois de Serge Lutens est un monument de la parfumerie niche, créé en 1992. La prune juteuse rencontre le cèdre sec dans une composition intemporelle d'une profondeur remarquable.",
    "description": "Serge Lutens Féminité du Bois est un parfum révolutionnaire, considéré comme l'un des plus influents de la parfumerie moderne. Créé en 1992 par Serge Lutens et Christopher Sheldrake, il a littéralement transformé la manière dont les parfumeurs pensent les accords boisés au féminin.\n\nAvant Féminité du Bois, le bois était essentiellement associé aux parfums masculins. Lutens a eu l'audace de placer le cèdre au cœur d'une fragrance féminine, en l'entourant de prune juteuse et d'épices orientales pour créer quelque chose d'entièrement nouveau et d'infiniment féminin.\n\nL'ouverture est immédiatement distinctive : la prune mûre, légèrement acidulée et très juteuse, s'impose avec force. Les épices douces (cannelle, cardamome) la réchauffent et lui donnent une dimension orientale. Cette ouverture est généreuse, presque excessive, dans le meilleur sens du terme.\n\nLe cœur révèle la majesté du cèdre, traité ici comme une matière précieuse et sensuelle plutôt que comme un simple fond boisé. La rose et le miel apportent une douceur bienvenue qui équilibre la sécheresse du bois. C'est dans ce cœur que le génie de Lutens s'exprime pleinement.\n\nLa base est chaude, sèche et persistante. Ambre, musc et bois de santal créent un fond complexe qui évolue pendant des heures sur la peau, révélant progressivement de nouvelles facettes.\n\nDisponible chez Maison Numidia, livraison Yalidine 58 wilayas, paiement à la réception.",
    "notes": {
      "top": ["Prune", "Cannelle", "Cardamome"],
      "heart": ["Cèdre", "Rose", "Miel", "Iris"],
      "base": ["Ambre", "Musc", "Bois de santal", "Vanille"]
    },
    "family": "Boisé Fruité Oriental",
    "occasions": ["Soirée", "Automne-Hiver", "Événement"],
    "seasons": ["Automne", "Hiver"],
    "longevity": 5,
    "sillage": 4,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["frederic-malle-portrait-of-a-lady", "amouage-lyric-femme", "ex-nihilo-fleur-narcotique"]
  }
];

const allSlugs = new Set([...existingSlugs, ...newProducts.map(p => p.slug)]);
let errors = 0;
for (const p of newProducts) {
  if (existingSlugs.has(p.slug)) { console.error(`DUPLICATE: ${p.slug}`); errors++; }
  for (const r of p.related) {
    if (!allSlugs.has(r)) { console.error(`MISSING related "${r}" in ${p.slug}`); errors++; }
  }
}
if (errors > 0) { console.error(`${errors} erreur(s) — abandon`); process.exit(1); }
data.products.push(...newProducts);
writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf8');
console.log(`✅ ${newProducts.length} produits ajoutés — total: ${data.products.length} produits`);
