import { readFileSync, writeFileSync } from 'fs';

const filePath = 'data/products.json';
const data = JSON.parse(readFileSync(filePath, 'utf8'));
const existingSlugs = new Set(data.products.map(p => p.slug));

const newProducts = [
  {
    "id": "narciso-rodriguez-for-her-edp-rouge",
    "slug": "narciso-rodriguez-for-her-edp-rouge",
    "h1": "Narciso Rodriguez For Her EDP Rouge Parfum Femme Algérie",
    "name": "For Her EDP Rouge",
    "brand": "Narciso Rodriguez",
    "brandSlug": "narciso-rodriguez",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "EDP",
    "volume": "90ml",
    "price": 9500,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/narciso-rodriguez-for-her-edp-rouge.jpg",
    "shortDescription": "Narciso Rodriguez For Her EDP Rouge est la version la plus intense et sensuelle de la fragrance iconique. Musc rouge, rose et bois précieux dans une composition ardente et inoubliable.",
    "description": "Narciso Rodriguez For Her EDP Rouge est la réinterprétation la plus passionnée et la plus intense du parfum fondateur de la maison new-yorkaise. Lancé comme une déclaration d'amour olfactive, Rouge prend la signature musquée de For Her et l'amplifie d'une couleur rouge brûlante — l'ardeur, la passion et la féminité dans leur expression la plus directe.\n\nLa composition s'ouvre sur un accord floral fruité de rose et de nectarine qui apporte une chaleur immédiate. Le cœur est la signature de Narciso Rodriguez : un musc rouge de haute qualité, légèrement ambré, accompagné d'iris et d'ylang-ylang dans un accord floral-musqué d'une sensualité troublante. La base est profonde et persistante — bois de santal, vétiver et ambre rose — qui ancre la fragrance dans une longévité remarquable.\n\nFor Her EDP Rouge est le choix de la femme qui assume sa sensualité avec confiance et élégance. Sa concentration EDP assure une tenue de six à huit heures et un sillage enveloppant qui ne laisse pas indifférent.\n\nMaison Numidia propose ce parfum Narciso Rodriguez authentique avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Rose", "Nectarine", "Bergamote"],
      "heart": ["Musc rouge", "Iris", "Ylang-ylang"],
      "base": ["Bois de santal", "Vétiver", "Ambre rose"]
    },
    "family": "Floral Musqué",
    "occasions": ["Soirée", "Romance", "Occasions spéciales"],
    "seasons": ["Automne", "Hiver"],
    "longevity": 4,
    "sillage": 4,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["narciso-rodriguez-for-her", "narciso-pure-musc", "narciso-rodriguez-musc-noir"]
  },
  {
    "id": "hermes-twilly-d-hermes-eau-poivree",
    "slug": "hermes-twilly-d-hermes-eau-poivree",
    "h1": "Hermès Twilly Eau Poivrée Parfum Femme Algérie",
    "name": "Twilly d'Hermès Eau Poivrée",
    "brand": "Hermès",
    "brandSlug": "hermes",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "EDP",
    "volume": "85ml",
    "price": 11900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/hermes-twilly-d-hermes-eau-poivree.jpg",
    "shortDescription": "Twilly d'Hermès Eau Poivrée est la version épicée et caractère du Twilly original. Poivre rose, gingembre et bois de santal dans une composition audacieuse pour la femme qui ne craint pas de se démarquer.",
    "description": "Twilly d'Hermès Eau Poivrée est une réinterprétation épicée et affirmée du Twilly d'Hermès original. Là où le Twilly traditionnel joue sur la légèreté florale et la fraîcheur, Eau Poivrée assume un caractère plus affirmé, plus épicé et plus mémorable — comme une jeune femme qui a trouvé sa voix et n'hésite plus à l'utiliser.\n\nLa composition s'ouvre sur un accord poivre rose et gingembre frais qui captent immédiatement l'attention avec leur vivacité épicée et leur caractère distinctif. Le cœur floral-épicé associe gardénia, jasmin et une touche de cardamome dans un accord qui allie féminité et caractère avec une aisance remarquable. La base chaude de bois de santal, vétiver et musc ambre donne à Eau Poivrée sa profondeur et sa persistance.\n\nCette fragrance est pour la femme Hermès d'aujourd'hui — cultivée, indépendante, qui aime les belles choses sans les subir. Sa signature épicée la rend reconnaissable entre mille.\n\nDisponible chez Maison Numidia avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Poivre rose", "Gingembre", "Bergamote"],
      "heart": ["Gardénia", "Jasmin", "Cardamome"],
      "base": ["Bois de santal", "Vétiver", "Musc ambré"]
    },
    "family": "Floral Épicé",
    "occasions": ["Bureau", "Journée", "Soirée décontractée"],
    "seasons": ["Automne", "Hiver", "Printemps"],
    "longevity": 4,
    "sillage": 3,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["twilly-d-hermes", "hermes-jour-d-hermes", "hermes-kelly-caleche"]
  },
  {
    "id": "lancome-la-vie-est-belle-florale",
    "slug": "lancome-la-vie-est-belle-florale",
    "h1": "Lancôme La Vie est Belle Florale Parfum Femme Algérie",
    "name": "La Vie est Belle Florale",
    "brand": "Lancôme",
    "brandSlug": "lancome",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "EDP",
    "volume": "100ml",
    "price": 11200,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/lancome-la-vie-est-belle-florale.jpg",
    "shortDescription": "Lancôme La Vie est Belle Florale est la version printanière et fraîche de l'iconique La Vie est Belle. Poire, pivoine et jasmin dans une composition florale légère et solaire.",
    "description": "Lancôme La Vie est Belle Florale est une réinterprétation printanière et aérienne de l'un des parfums féminins les plus aimés au monde. Là où La Vie est Belle original joue sur la richesse gourmande de l'iris et de la praline, Florale prend une direction plus légère, plus solaire et plus florale — comme si la vie belle s'était mise à danser au soleil de printemps.\n\nLa composition s'ouvre sur une fraîcheur fruitée de poire et de litchi, lumineuse et pétillante. Le cœur est un bouquet floral généreux : pivoine, jasmin étoilé et magnolia dans un accord printanier d'une beauté désarmante. La base est plus légère que dans l'original — musc blanc, bois de cèdre et une touche de praline très discrète — qui préserve la fraîcheur florale tout en apportant la tenue nécessaire.\n\nLa Vie est Belle Florale est la version idéale pour les journées chaudes algériennes où l'original peut sembler trop intense. Sa légèreté et sa fraîcheur en font un parfum quotidien agréable et élégant.\n\nMaison Numidia propose ce parfum Lancôme authentique avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Poire", "Litchi", "Bergamote"],
      "heart": ["Pivoine", "Jasmin étoilé", "Magnolia"],
      "base": ["Musc blanc", "Cèdre", "Praline légère"]
    },
    "family": "Floral Fruité",
    "occasions": ["Bureau", "Journée", "Printemps"],
    "seasons": ["Printemps", "Été"],
    "longevity": 3,
    "sillage": 3,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["la-vie-est-belle-lancome", "la-vie-est-belle-intensement", "lancome-idole-now"]
  },
  {
    "id": "guerlain-aqua-allegoria-flora-nymphea",
    "slug": "guerlain-aqua-allegoria-flora-nymphea",
    "h1": "Guerlain Aqua Allegoria Flora Nymphea Parfum Femme Algérie",
    "name": "Aqua Allegoria Flora Nymphea",
    "brand": "Guerlain",
    "brandSlug": "guerlain",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "EDT",
    "volume": "100ml",
    "price": 10900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/guerlain-aqua-allegoria-flora-nymphea.jpg",
    "shortDescription": "Guerlain Aqua Allegoria Flora Nymphea est un floral aquatique cristallin et pur. Lotus blanc, jasmin aquatique et musc blanc dans une composition d'une légèreté et d'une fraîcheur absolues.",
    "description": "Guerlain Aqua Allegoria Flora Nymphea appartient à la collection Aqua Allegoria, l'une des expressions les plus créatives et les plus légères de la maison Guerlain. Cette collection, lancée en 1999, propose chaque année de nouvelles fragrances légères et thématiques qui célèbrent la beauté de la nature dans ses manifestations les plus pures.\n\nFlora Nymphea s'inspire du nénuphar blanc — la nymphea — qui flotte sur l'eau calme des étangs avec une sérénité absolue. La composition s'ouvre sur une fraîcheur cristalline de citron et de bergamote qui évoque une eau pure. Le cœur est un accord floral aquatique d'une délicatesse rare : lotus blanc, jasmin aquatique et rose fraîche dans une composition qui semble ne rien peser sur la peau. La base de musc blanc et de cèdre préserve la légèreté de l'ensemble.\n\nAqua Allegoria Flora Nymphea est le parfum parfait pour les journées chaudes algériennes. Sa légèreté et sa fraîcheur s'y expriment avec bonheur, créant un voile frais et agréable qui accompagne la peau sans jamais l'étouffer.\n\nDisponible chez Maison Numidia avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Citron", "Bergamote", "Notes vertes"],
      "heart": ["Lotus blanc", "Jasmin aquatique", "Rose fraîche"],
      "base": ["Musc blanc", "Cèdre", "Ambre léger"]
    },
    "family": "Floral Aquatique",
    "occasions": ["Journée", "Été", "Bureau"],
    "seasons": ["Printemps", "Été"],
    "longevity": 2,
    "sillage": 2,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["guerlain-aqua-allegoria", "guerlain-aqua-allegoria-bergamote", "hermes-un-jardin-sur-le-nil"]
  },
  {
    "id": "guerlain-aqua-allegoria-forte",
    "slug": "guerlain-aqua-allegoria-forte",
    "h1": "Guerlain Aqua Allegoria Forte Parfum Femme Algérie",
    "name": "Aqua Allegoria Bergamote Calabria Forte",
    "brand": "Guerlain",
    "brandSlug": "guerlain",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "EDP",
    "volume": "125ml",
    "price": 13900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/guerlain-aqua-allegoria-forte.jpg",
    "shortDescription": "Guerlain Aqua Allegoria Forte est la version EDP intense des Aqua Allegoria pour plus de tenue. Bergamote de Calabre, thé vert et musc dans une composition fraîche mais plus persistante.",
    "description": "Guerlain Aqua Allegoria Forte est la réponse de la maison au souhait le plus répandu des fans de la collection Aqua Allegoria : avoir les mêmes fragrances légères et naturelles mais avec plus de tenue. La version Forte est une EDP plus concentrée qui conserve toute la légèreté et la fraîcheur des Aqua Allegoria tout en offrant une persistance significativement améliorée.\n\nLa composition reprend la signature bergamote de Calabre qui fait la réputation de la ligne, dans sa version la plus pure et la plus lumineuse. Des notes de thé vert apportent une fraîcheur végétale caractéristique, accompagnées d'agrumes blancs frais. Le coeur de jasmin blanc et muguet est discret mais présent, ajoutant une dimension florale légère. La base de musc blanc et de bois léger assure la tenue supplémentaire qui caractérise la version Forte.\n\nCette fragrance est particulièrement adaptée au climat algérien : légère et fraîche pour les journées chaudes, mais suffisamment concentrée pour ne pas disparaître en quelques heures.\n\nMaison Numidia propose ce parfum Guerlain authentique avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Bergamote de Calabre", "Agrumes blancs", "Thé vert"],
      "heart": ["Jasmin blanc", "Muguet", "Notes vertes"],
      "base": ["Musc blanc", "Bois léger", "Ambre doux"]
    },
    "family": "Floral Aquatique",
    "occasions": ["Bureau", "Journée", "Été"],
    "seasons": ["Printemps", "Été"],
    "longevity": 3,
    "sillage": 3,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["guerlain-aqua-allegoria", "guerlain-aqua-allegoria-bergamote", "guerlain-aqua-allegoria-flora-nymphea"]
  },
  {
    "id": "dior-joy-intense",
    "slug": "dior-joy-intense",
    "h1": "Dior Joy Intense Parfum Femme Algérie",
    "name": "Joy Intense",
    "brand": "Dior",
    "brandSlug": "dior",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "EDP Intense",
    "volume": "90ml",
    "price": 14500,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/dior-joy-intense.jpg",
    "shortDescription": "Dior Joy Intense est la version la plus concentrée et la plus sensuelle de Joy. Fleur de mai, jasmin absolue et musc blanc dans une intensité florale absolue signée Christian Dior.",
    "description": "Dior Joy Intense est l'expression maximale du parfum Joy de Christian Dior, lancé en 2018. Là où Joy EDT offre légèreté et fraîcheur, Joy Intense assume une densité florale et une profondeur qui en font l'une des fragrances florales les plus riches et les plus longues de la maison.\n\nLa composition Intense amplifie chaque note du Joy original. L'ouverture est une explosion de mandarine et de néroli qui capte l'attention avec une vivacité lumineuse. Le cœur est dominé par la fleur de mai — la fleur emblématique de la parfumerie Dior — et le jasmin grandiflorum absolue dans leur version la plus généreuse et la plus riche. Ce bouquet floral d'une qualité rare est la pièce maîtresse de la fragrance. La base de musc blanc, fond de santal et ambre doux ancre ce bouquet dans une longévité qui peut atteindre douze heures.\n\nJoy Intense est le parfum des grandes occasions : mariages, galas, dîners importants. Son sillage fleuri et sa persistance en font un investissement olfactif qui ne déçoit jamais.\n\nMaison Numidia propose ce parfum Dior authentique avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Mandarine", "Néroli", "Bergamote"],
      "heart": ["Fleur de mai", "Jasmin grandiflorum", "Rose"],
      "base": ["Musc blanc", "Bois de santal", "Ambre doux"]
    },
    "family": "Floral",
    "occasions": ["Soirée", "Occasions spéciales", "Mariage"],
    "seasons": ["Printemps", "Automne"],
    "longevity": 5,
    "sillage": 4,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["dior-joy", "miss-dior", "dior-jadore"]
  },
  {
    "id": "cartier-carat",
    "slug": "cartier-carat",
    "h1": "Cartier Carat Parfum Femme Algérie",
    "name": "Carat",
    "brand": "Cartier",
    "brandSlug": "cartier",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "EDP",
    "volume": "100ml",
    "price": 10900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/cartier-carat.jpg",
    "shortDescription": "Cartier Carat est un floral cristallin et prisme de sept fleurs précieuses. Tuberose, ylang-ylang et jasmin dans une composition qui réfracte la lumière comme un diamant.",
    "description": "Cartier Carat est une fragrance qui réinterprète en olfaction le travail du tailleur de diamants. Comme un carat de diamant taillé à facettes qui décompose la lumière en un arc-en-ciel de couleurs, Carat décompose la lumière florale en sept fleurs précieuses qui se révèlent progressivement.\n\nCette approche olfactive originale signée Mathilde Laurent, parfumeur de la maison Cartier, est une oeuvre de parfumerie d'une sophistication rare. La composition est une fugue florale : tubéreuse, ylang-ylang, jasmin d'Egypte, fleur d'oranger, iris, rose et muguet se succèdent et se superposent dans une complexité qui se dévoile au fil des heures.\n\nL'ouverture est un bouquet floral de rose blanche et d'ylang-ylang d'une légèreté aérienne. Le cœur déploie la tubéreuse et le jasmin dans toute leur splendeur — créamy, généreux, solaire. La base de bois de santal et musc blanc préserve la légèreté de l'ensemble tout en assurant la tenue.\n\nCarat est pour les femmes qui apprécient la parfumerie comme un art. Disponible chez Maison Numidia avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Rose blanche", "Ylang-ylang", "Magnolia"],
      "heart": ["Tubéreuse", "Jasmin d'Egypte", "Fleur d'oranger"],
      "base": ["Iris", "Muguet", "Musc blanc"]
    },
    "family": "Floral",
    "occasions": ["Soirée", "Occasions spéciales", "Luxe"],
    "seasons": ["Printemps", "Été"],
    "longevity": 4,
    "sillage": 3,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["cartier-baiser-vole", "cartier-la-panthere", "van-cleef-arpels-first"]
  },
  {
    "id": "armani-my-way-intense",
    "slug": "armani-my-way-intense",
    "h1": "Armani My Way Intense Parfum Femme Algérie",
    "name": "My Way Intense",
    "brand": "Giorgio Armani",
    "brandSlug": "armani",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "EDP Intense",
    "volume": "90ml",
    "price": 13500,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/armani-my-way-intense.jpg",
    "shortDescription": "Armani My Way Intense est la version la plus profonde et la plus sensuelle de My Way. Fleur d'oranger, iris et bois de santal dans une intensité florale boisée absolue.",
    "description": "Armani My Way Intense est l'expression maximale de My Way — le parfum féminin qui a conquis des millions de femmes depuis 2020. Là où My Way EDP célèbre l'optimisme et l'ouverture au monde avec légèreté, My Way Intense assume une profondeur et une intensité qui en font un parfum de soirée et d'occasions importantes.\n\nLa composition Intense amplifie les notes signature de My Way. La fleur d'oranger d'Egypte est ici plus riche et plus généreuse, déployant sa beauté florale créameuse sans retenue. L'iris de Florence apporte une dimension poudrée et élégante qui ancre la fragrance dans la grande tradition de la parfumerie italienne. La base de bois de santal de Madagascar et de musc ambré est plus dense et plus chaleureuse que dans l'original.\n\nMy Way Intense est pour les femmes qui veulent My Way mais qui cherchent quelque chose de plus affirmé, de plus présent et de plus mémorable. Son sillage enveloppant et sa longévité remarquable en font un investissement olfactif qui se justifie pleinement.\n\nDisponible chez Maison Numidia avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Bergamote", "Fleur d'oranger d'Egypte", "Magnolia"],
      "heart": ["Iris de Florence", "Jasmin", "Tubéreuse"],
      "base": ["Bois de santal de Madagascar", "Musc ambré", "Vétiver"]
    },
    "family": "Floral Boisé",
    "occasions": ["Soirée", "Occasions spéciales", "Hiver"],
    "seasons": ["Automne", "Hiver"],
    "longevity": 5,
    "sillage": 4,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["armani-my-way", "armani-my-way-parfum", "armani-si-intense"]
  },
  {
    "id": "burberry-goddess-intense",
    "slug": "burberry-goddess-intense",
    "h1": "Burberry Goddess Intense Parfum Femme Algérie",
    "name": "Goddess Intense",
    "brand": "Burberry",
    "brandSlug": "burberry",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "EDP Intense",
    "volume": "100ml",
    "price": 12500,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/burberry-goddess-intense.jpg",
    "shortDescription": "Burberry Goddess Intense est la version la plus enveloppante et la plus sensuelle du Goddess. Lavande profonde, vanille dorée et musc dans une composition chaleureuse et irrésistible.",
    "description": "Burberry Goddess Intense est l'interprétation la plus profonde et la plus enveloppante du Goddess — fragrance qui a redéfini la parfumerie féminine Burberry depuis son lancement en 2023. Là où Goddess joue sur la dualité entre la lavande aérienne et la vanille chaude, Goddess Intense amplifie chaque dimension pour créer une expérience olfactive plus intense et plus persistante.\n\nLa composition Intense commence par une lavande française plus généreuse et plus profonde que dans l'original, accompagnée d'une bergamote légèrement mielleuse. Le cœur déploie un accord lavande-fève tonka-vanille d'une douceur enveloppante remarquable, typique du style Burberry Goddess. La base est la révélation de l'Intense : vanille dorée, musc ambré et bois de santal dans un accord chaleureux et persistant qui s'intensifie au fil des heures sur la peau.\n\nGoddess Intense est pour les femmes qui ont aimé le Goddess original mais qui voulaient plus — plus de tenue, plus de chaleur, plus de présence. Un parfum pour les soirées fraîches algériennes.\n\nMaison Numidia propose ce parfum Burberry authentique avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Lavande française", "Bergamote mielleuse", "Néroli"],
      "heart": ["Lavande absolue", "Fève tonka", "Vanille"],
      "base": ["Vanille dorée", "Musc ambré", "Bois de santal"]
    },
    "family": "Oriental Floral",
    "occasions": ["Soirée", "Automne", "Hiver"],
    "seasons": ["Automne", "Hiver"],
    "longevity": 5,
    "sillage": 4,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["goddess-burberry", "burberry-her", "ysl-libre-intense"]
  },
  {
    "id": "chloe-atelier-des-fleurs-cedrus",
    "slug": "chloe-atelier-des-fleurs-cedrus",
    "h1": "Chloé Atelier des Fleurs Cedrus Parfum Femme Algérie",
    "name": "Atelier des Fleurs Cedrus",
    "brand": "Chloé",
    "brandSlug": "chloe",
    "category": "parfums-femme",
    "gender": "unisexe",
    "concentration": "EDP",
    "volume": "75ml",
    "price": 10500,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/chloe-atelier-des-fleurs-cedrus.jpg",
    "shortDescription": "Chloé Atelier des Fleurs Cedrus est un boisé naturel minimaliste et authentique. Cèdre Atlas, bois fumé et musc dans une composition arty et épurée de la collection niche Chloé.",
    "description": "Chloé Atelier des Fleurs Cedrus appartient à la collection Atelier des Fleurs — la ligne niche de Chloé qui propose des fragrances solos ou duos autour de matières premières sélectionnées avec soin et mises en valeur par une approche minimaliste et artisanale.\n\nCedrus est un portrait olfactif du cèdre Atlas dans toute sa singularité. Cette matière première — le bois de cèdre de l'Atlas marocain — est ici présentée sans artifice, dans une composition épurée qui permet à chaque facette du bois de s'exprimer librement.\n\nLa fragrance s'ouvre sur un accord boisé-vert immédiat : bois de cèdre frais, légèrement mentholé et vert dans sa phase initiale. Au fil du temps, le cèdre se développe en révélant ses nuances plus chaudes et légèrement fumées. Des notes d'encens et de résine apportent de la profondeur sans alourdir. La base est une concordance de cèdre chaud, musc propre et ambre léger d'une persistance satisfaisante.\n\nCedrus est une fragrance pour les amateurs de parfums boisés minimalistes et authentiques. Disponible chez Maison Numidia avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Cèdre Atlas vert", "Notes boisées fraîches"],
      "heart": ["Cèdre fumé", "Encens", "Résine"],
      "base": ["Cèdre chaud", "Musc propre", "Ambre léger"]
    },
    "family": "Boisé",
    "occasions": ["Bureau", "Journée", "Casual"],
    "seasons": ["Automne", "Hiver", "Printemps"],
    "longevity": 4,
    "sillage": 3,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["chloe-nomade", "chloe-signature", "terre-d-hermes-parfum"]
  },
  {
    "id": "valentino-voce-viva-intense",
    "slug": "valentino-voce-viva-intense",
    "h1": "Valentino Voce Viva Intense Parfum Femme Algérie",
    "name": "Voce Viva Intense",
    "brand": "Valentino",
    "brandSlug": "valentino",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "EDP Intense",
    "volume": "100ml",
    "price": 12900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/valentino-voce-viva-intense.jpg",
    "shortDescription": "Valentino Voce Viva Intense est la version la plus affirmée du Voce Viva. Bergamote de Sicile, vétiver et accordéon musqué dans une composition florale boisée d'une intensité dramatique.",
    "description": "Valentino Voce Viva Intense est l'expression maximale du parfum phare de la collection Voce Viva de Valentino. Là où le Voce Viva original joue sur la légèreté et la fraîcheur, Intense assume une profondeur et une présence qui en font un parfum de soirée et d'occasions importantes où l'on veut se distinguer.\n\nLa composition Intense amplifie chaque dimension du Voce Viva. La bergamote de Sicile s'ouvre avec plus d'intensité et de chaleur. L'accord central de vétiver — la note signature distinctive du Voce Viva — est ici plus riche, plus fumé et plus prononcé. La mandarine apporte une touche fruitée ensoleillée qui équilibre la profondeur boisée. La base est un accord musqué ambré d'une persistance remarquable.\n\nVoce Viva Intense est pour les femmes qui aiment se démarquer avec élégance. Sa composition originale et son caractère affirméen font un parfum de personnalité — un parfum qu'on reconnaît immédiatement et dont on se souvient.\n\nDisponible chez Maison Numidia avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Bergamote de Sicile", "Mandarine", "Néroli"],
      "heart": ["Vétiver intense", "Iris", "Musc floral"],
      "base": ["Ambre musqué", "Bois de santal", "Fève tonka"]
    },
    "family": "Floral Boisé",
    "occasions": ["Soirée", "Occasions spéciales", "Bureau"],
    "seasons": ["Automne", "Hiver"],
    "longevity": 5,
    "sillage": 4,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["valentino-voce-viva", "valentino-donna", "armani-my-way-intense"]
  },
  {
    "id": "yves-saint-laurent-mon-paris-intensement",
    "slug": "yves-saint-laurent-mon-paris-intensement",
    "h1": "YSL Mon Paris Intensément Parfum Femme Algérie",
    "name": "Mon Paris Intensément",
    "brand": "Yves Saint Laurent",
    "brandSlug": "ysl",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "EDP",
    "volume": "90ml",
    "price": 11200,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/yves-saint-laurent-mon-paris-intensement.jpg",
    "shortDescription": "YSL Mon Paris Intensément est la version la plus sensuelle de Mon Paris. Fraise, pivoine et patchouli dans un accord floral chypré intense et séduisant pour la femme audacieuse.",
    "description": "Yves Saint Laurent Mon Paris Intensément est l'interprétation la plus passionnée et la plus profonde du Mon Paris original — cette déclaration d'amour à la Ville Lumière que la maison YSL a lancée en 2016. Là où Mon Paris joue sur la romance légère et le charme floral, Intensément assume une sensualité plus affirmée et une profondeur qui en font un parfum de séduction assumée.\n\nLa composition s'ouvre sur un accord fruité intense de fraise rouge et de framboise, plus généreux que dans l'original. Le cœur est un bouquet floral-épicé de pivoine, de fleur de poivre rouge et une touche de jasmin dans un accord chaud et piquant. La base révèle la vraie personnalité d'Intensément : patchouli marocain, vétiver et musc blanc dans un accord chypré profond et persistant qui peut se maintenir pendant de nombreuses heures.\n\nMon Paris Intensément est pour les femmes qui veulent plus que la romance légère — qui souhaitent une fragrance qui affirme leur présence et leur caractère avec conviction.\n\nMaison Numidia propose ce parfum YSL authentique avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Fraise rouge", "Framboise", "Bergamote"],
      "heart": ["Pivoine", "Poivre rouge", "Jasmin"],
      "base": ["Patchouli marocain", "Vétiver", "Musc blanc"]
    },
    "family": "Floral Chypré",
    "occasions": ["Soirée", "Sortie", "Hiver"],
    "seasons": ["Automne", "Hiver"],
    "longevity": 5,
    "sillage": 4,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["mon-paris-ysl", "ysl-mon-paris-couture", "ysl-libre-intense"]
  }
];

const allSlugs = new Set([...existingSlugs, ...newProducts.map(p => p.slug)]);
let errors = 0;
for (const p of newProducts) {
  if (existingSlugs.has(p.slug)) { console.error(`DUPLICATE: ${p.slug}`); errors++; }
  for (const r of p.related) {
    if (!allSlugs.has(r)) { console.error(`MISSING related "${r}" in ${p.slug}`); errors++; }
  }
}
if (errors > 0) { console.error(`${errors} erreur(s) — abandon`); process.exit(1); }

data.products.push(...newProducts);
writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf8');
console.log(`✅ ${newProducts.length} produits ajoutés — total: ${data.products.length} produits`);
