import { readFileSync, writeFileSync } from 'fs';

const filePath = 'data/products.json';
const data = JSON.parse(readFileSync(filePath, 'utf8'));
const existingSlugs = new Set(data.products.map(p => p.slug));

const newProducts = [
  {
    "id": "cerruti-1881-homme",
    "slug": "cerruti-1881-homme",
    "h1": "Cerruti 1881 Parfum Homme Algérie",
    "name": "1881 pour Homme",
    "brand": "Cerruti",
    "brandSlug": "cerruti",
    "category": "parfums-homme",
    "gender": "homme",
    "concentration": "EDT",
    "volume": "100ml",
    "price": 5500,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/cerruti-1881-homme.jpg",
    "shortDescription": "Cerruti 1881 pour Homme est un boisé aromatique raffiné né en 1996. Lavande, bois de cèdre et notes de tabac composent cette signature masculine discrète et élégante.",
    "description": "Cerruti 1881 pour Homme est le parfum masculin emblématique de la maison de couture italienne Nino Cerruti. Lancé en 1996, il incarne l'élégance discrète et le savoir-faire italien dans toute sa sobriété. Ce parfum appartient à cette catégorie de fragrances qui traversent les décennies sans jamais paraître datées — une qualité rare qui témoigne de l'équilibre parfait de sa composition.\n\nLa fragrance s'ouvre sur une alliance fraîche et aromatique de lavande et de bergamote, un préambule rassurant et bien construit. Le cœur développe des notes herbacées et boisées de géranium, de sauge et de pin qui donnent au parfum sa signature naturelle et masculine. Le fond révèle une base chaude et persistante de bois de cèdre, bois de santal et vétiver, avec une subtile touche fumée de tabac qui apporte caractère et profondeur.\n\nCerruti 1881 pour Homme est le choix de l'homme élégant qui ne cherche pas à se faire remarquer à tout prix. Sa discrétion et son équilibre en font un parfum de bureau et de journées actives, suffisamment polyvalent pour accompagner aussi les soirées plus décontractées.\n\nDisponible chez Maison Numidia avec livraison COD dans les 58 wilayas d'Algérie. Authenticité garantie, flacon d'origine avec son emballage.",
    "notes": {
      "top": ["Lavande", "Bergamote", "Pin"],
      "heart": ["Géranium", "Sauge", "Cèdre"],
      "base": ["Bois de santal", "Vétiver", "Tabac"]
    },
    "family": "Boisé Aromatique",
    "occasions": ["Bureau", "Journée", "Casual"],
    "seasons": ["Printemps", "Automne"],
    "longevity": 3,
    "sillage": 3,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["azzaro-chrome", "davidoff-cool-water-homme", "cerruti-1881-femme"]
  },
  {
    "id": "cerruti-1881-femme",
    "slug": "cerruti-1881-femme",
    "h1": "Cerruti 1881 Parfum Femme Algérie",
    "name": "1881 pour Femme",
    "brand": "Cerruti",
    "brandSlug": "cerruti",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "EDT",
    "volume": "100ml",
    "price": 5200,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/cerruti-1881-femme.jpg",
    "shortDescription": "Cerruti 1881 pour Femme est un floral fruité délicat à l'italienne. Fraîcheur de pétales de rose, jasmin et fond de musc pour une signature féminine subtile et enveloppante.",
    "description": "Cerruti 1881 pour Femme est la déclinaison féminine de l'iconique parfum de la maison italienne, créée pour accompagner son homologue masculin avec la même élégance et la même sobriété caractéristiques de la griffe. Ce parfum féminin illustre parfaitement le style Cerruti : raffinement sans ostentation, féminité sans excès.\n\nL'ouverture est fraîche et fruitée, avec des notes de rose, de bergamote et une touche légère de pêche qui apportent une luminosité immédiate. Le cœur floral associe jasmin, muguet et ylang-ylang dans une composition généreuse mais jamais lourde. La base apporte la chaleur et la persistance nécessaires grâce au musc blanc, au bois de santal et à l'ambre discret.\n\nCerruti 1881 pour Femme s'adresse à la femme qui aime les parfums féminins sans être envahissants. Sa formule légère et son sillage délicat en font un parfum parfait pour le bureau et les journées chargées, tout en restant agréable pour les sorties du week-end.\n\nMaison Numidia livre ce parfum authentique avec paiement à la réception (COD) dans toutes les wilayas d'Algérie.",
    "notes": {
      "top": ["Rose", "Bergamote", "Pêche"],
      "heart": ["Jasmin", "Muguet", "Ylang-ylang"],
      "base": ["Musc blanc", "Bois de santal", "Ambre"]
    },
    "family": "Floral Fruité",
    "occasions": ["Bureau", "Journée", "Week-end"],
    "seasons": ["Printemps", "Été"],
    "longevity": 3,
    "sillage": 2,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["cerruti-1881-homme", "cacharel-anais-anais", "lacoste-pour-femme"]
  },
  {
    "id": "chopard-wish",
    "slug": "chopard-wish",
    "h1": "Chopard Wish Parfum Femme Algérie",
    "name": "Wish",
    "brand": "Chopard",
    "brandSlug": "chopard",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "EDP",
    "volume": "75ml",
    "price": 5900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/chopard-wish.jpg",
    "shortDescription": "Wish de Chopard est un floral boisé précieux qui reflète le savoir-faire joaillier de la maison. Bergamote, pivoine et bois de cashmere dans un parfum lumineux et sensuel.",
    "description": "Chopard Wish est la fragrance qui réunit l'art joaillier de la maison Chopard avec la parfumerie de luxe. Créée pour une femme élégante et ambitieuse, Wish puise son inspiration dans le brillant des diamants et la préciosité des pierres qui ont fait la réputation internationale de la maison suisse.\n\nLa composition s'ouvre sur une fraîcheur pétillante de bergamote et de pêche, lumineuse comme un diamant au soleil. Le cœur floral associe pivoine, rose centifolia et freesia dans un accord délicat et sensuel. La base précieuse de bois de cashmere, musc blanc et ambre donne à Wish sa profondeur et sa longévité, comme le prix d'une belle pièce de joaillerie.\n\nWish est un parfum qui convient à toutes les occasions : assez discret pour le bureau, assez beau pour les dîners habillés. Son équilibre entre fraîcheur et chaleur en fait un choix polyvalent pour la femme algérienne qui aime les parfums de caractère sans ostentation.\n\nDisponible chez Maison Numidia avec livraison COD dans les 58 wilayas d'Algérie. Un bijou olfactif à un prix accessible.",
    "notes": {
      "top": ["Bergamote", "Pêche", "Framboise"],
      "heart": ["Pivoine", "Rose centifolia", "Freesia"],
      "base": ["Bois de cashmere", "Musc blanc", "Ambre"]
    },
    "family": "Floral Boisé",
    "occasions": ["Bureau", "Journée", "Dîner"],
    "seasons": ["Printemps", "Automne"],
    "longevity": 3,
    "sillage": 3,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["chopard-casmir", "lalique-amour", "bvlgari-goldea"]
  },
  {
    "id": "chopard-casmir",
    "slug": "chopard-casmir",
    "h1": "Chopard Casmir Parfum Femme Algérie",
    "name": "Casmir",
    "brand": "Chopard",
    "brandSlug": "chopard",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "EDP",
    "volume": "100ml",
    "price": 5500,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/chopard-casmir.jpg",
    "shortDescription": "Casmir de Chopard est un oriental gourmand somptueux créé en 1992. Pêche, cannelle et vanille dans une composition chaude et addictive qui évoque la douceur du cachemire.",
    "description": "Chopard Casmir est l'une des grandes réussites de la parfumerie orientale des années 1990. Lancé en 1992, ce parfum féminin n'a pas pris une ride et reste à ce jour une référence dans sa famille olfactive. Son nom évoque les étoffes précieuses du Cachemire, et sa composition ne manque pas de tenir cette promesse de douceur et de luxe.\n\nCasmir s'ouvre sur un accord fruité de pêche juteuse et d'abricot qui capte immédiatement l'attention avec une générosité gourmande. Le cœur développe une richesse épicée-florale : cannelle, rose, jasmin et noix de coco créent un accord oriental gourmand d'une complexité rare. La base est un nid douillet de vanille crémeuse, bois de santal, ambre et musc qui ancrent la fragrance dans une longévité et une persistance remarquables.\n\nCasmir est fait pour les femmes qui aiment les parfums chauds, sensuels et généreux. C'est un parfum d'automne et d'hiver par excellence, qui accompagne à merveille les soirées fraîches et les nuits algériennes d'hiver.\n\nMaison Numidia vous propose ce classique olfactif avec livraison COD dans toutes les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Pêche", "Abricot", "Mandarine"],
      "heart": ["Cannelle", "Rose", "Jasmin", "Noix de coco"],
      "base": ["Vanille", "Bois de santal", "Ambre", "Musc"]
    },
    "family": "Oriental Gourmand",
    "occasions": ["Soirée", "Hiver", "Occasions spéciales"],
    "seasons": ["Automne", "Hiver"],
    "longevity": 5,
    "sillage": 4,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["chopard-wish", "guerlain-samsara", "cacharel-loulou"]
  },
  {
    "id": "elizabeth-taylor-white-diamonds",
    "slug": "elizabeth-taylor-white-diamonds",
    "h1": "Elizabeth Taylor White Diamonds Parfum Femme Algérie",
    "name": "White Diamonds",
    "brand": "Elizabeth Taylor",
    "brandSlug": "elizabeth-taylor",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "EDT",
    "volume": "100ml",
    "price": 4500,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/elizabeth-taylor-white-diamonds.jpg",
    "shortDescription": "White Diamonds d'Elizabeth Taylor est un classique floral aldéhydé né en 1991. Aldehydes, rose turque et néroli composent cette fragrance emblématique portée par des millions de femmes.",
    "description": "Elizabeth Taylor White Diamonds est l'un des parfums les plus vendus de l'histoire. Lancé en 1991, il incarne le glamour hollywoodien de la grande Elizabeth Taylor — son amour des diamants, son élégance naturelle et sa personnalité magnétique. Trente ans après sa création, il reste une référence absolue dans la parfumerie féminine accessible et continue de conquérir de nouvelles générations.\n\nLa composition est un floral aldéhydé classique dans la grande tradition de la parfumerie française. L'ouverture est caractéristique de cette école : aldehydes pétillants, bergamote et néroli qui créent une effusion lumineuse et légèrement poudré. Le cœur floral est riche et généreux : rose turque, iris, jonquille et jasmin dans un bouquet d'une féminité assumée. La base chaleureuse de bois de santal, amber oriental et musc blanc donne à la fragrance sa durée et son élégance tranquille.\n\nWhite Diamonds est le parfum parfait pour offrir : reconnu, universellement apprécié et à un prix qui permet à toutes les femmes d'accéder à un parfum de qualité. C'est aussi un choix judicieux pour qui cherche un parfum de soirée classique et élégant.\n\nDisponible chez Maison Numidia avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Aldéhydes", "Néroli", "Bergamote"],
      "heart": ["Rose turque", "Iris", "Jasmin", "Jonquille"],
      "base": ["Bois de santal", "Ambre oriental", "Musc blanc"]
    },
    "family": "Floral Aldéhydé",
    "occasions": ["Soirée", "Occasions spéciales", "Cadeau"],
    "seasons": ["Automne", "Hiver"],
    "longevity": 4,
    "sillage": 4,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["nina-ricci-coeur-joie", "cacharel-anais-anais", "lalique-amour"]
  },
  {
    "id": "trussardi-donna",
    "slug": "trussardi-donna",
    "h1": "Trussardi Donna Parfum Femme Algérie",
    "name": "Donna",
    "brand": "Trussardi",
    "brandSlug": "trussardi",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "EDP",
    "volume": "100ml",
    "price": 6500,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/trussardi-donna.jpg",
    "shortDescription": "Trussardi Donna est un floral boisé sophistiqué célébrant la femme italienne moderne. Rose, pivoine et vétiver dans une composition élégante signée Trussardi.",
    "description": "Trussardi Donna est le parfum féminin phare de la maison de mode milanaise Trussardi. Cette fragrance lancée en 2011 célèbre la féminité italienne dans sa version la plus contemporaine : assurée, élégante et libre. Le flacon, inspiration directe du sac emblématique Trussardi, est une pièce de design à part entière.\n\nLa composition s'ouvre sur une envolée fruitée de bergamote et de poire légèrement acidulée. Le cœur est un bouquet floral raffiné dominé par la rose centifolia, la pivoine et le muguet dans un accord charnu et féminin. La base apporte la signature boisée-musquée de la maison avec du vétiver, du bois de cèdre et un musc blanc propre et élégant.\n\nDonna est une fragrance qui séduit par son équilibre rare entre fraîcheur et sophistication. Sa progression olfactive est maîtrisée et révèle progressivement sa profondeur, récompensant celles qui prennent le temps de l'apprécier vraiment.\n\nMaison Numidia vous propose ce parfum de la maison Trussardi avec livraison COD dans toutes les 58 wilayas d'Algérie. Idéal pour la femme algérienne qui apprécie le style italien.",
    "notes": {
      "top": ["Bergamote", "Poire", "Galbanum"],
      "heart": ["Rose centifolia", "Pivoine", "Muguet"],
      "base": ["Vétiver", "Cèdre", "Musc blanc"]
    },
    "family": "Floral Boisé",
    "occasions": ["Bureau", "Journée", "Soirée décontractée"],
    "seasons": ["Printemps", "Automne"],
    "longevity": 4,
    "sillage": 3,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["trussardi-riflesso", "valentino-donna", "escada-magnetism"]
  },
  {
    "id": "trussardi-riflesso",
    "slug": "trussardi-riflesso",
    "h1": "Trussardi Riflesso Parfum Homme Algérie",
    "name": "Riflesso pour Homme",
    "brand": "Trussardi",
    "brandSlug": "trussardi",
    "category": "parfums-homme",
    "gender": "homme",
    "concentration": "EDT",
    "volume": "100ml",
    "price": 6200,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/trussardi-riflesso.jpg",
    "shortDescription": "Trussardi Riflesso est un aquatique-boisé moderne inspiré de l'homme milanais. Bergamote, violet, cèdre et musc ambre dans une composition fraîche et raffinée.",
    "description": "Trussardi Riflesso pour Homme est une ode à la modernité masculine selon la vision de la maison Trussardi. \"Riflesso\" signifie \"reflet\" en italien — ce parfum est le reflet de l'homme élégant et contemporain qui connaît les codes du style sans en être esclave.\n\nLa fragrance s'ouvre sur une fraîcheur aromatique de bergamote sicilienne et d'eucalyptus qui captent l'attention avec légèreté. Le cœur se développe autour d'un accord violet-boisé sophistiqué — le violet apportant une note florale légèrement poudrée très tendance, associé au cèdre pour plus de tenue. La base révèle un fond boisé-musqué chaleureux avec du vétiver, de l'ambre et du musc blanc qui confèrent à Riflesso sa durée et son élégance discrète.\n\nRiflesso est le parfum de l'homme actif et cultivé, à l'aise dans toutes les situations. Sa polyvalence et son caractère frais-boisé en font un choix idéal pour le bureau et les journées professionnelles, tout en restant pertinent pour les soirées décontractées.\n\nDisponible chez Maison Numidia avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Bergamote", "Eucalyptus", "Cardamome"],
      "heart": ["Violet", "Cèdre", "Poivre rose"],
      "base": ["Vétiver", "Ambre", "Musc blanc"]
    },
    "family": "Aquatique Boisé",
    "occasions": ["Bureau", "Journée", "Casual"],
    "seasons": ["Printemps", "Été", "Automne"],
    "longevity": 3,
    "sillage": 3,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["trussardi-donna", "hugo-boss-bottled", "armani-code"]
  },
  {
    "id": "karl-lagerfeld-classic",
    "slug": "karl-lagerfeld-classic",
    "h1": "Karl Lagerfeld Classic Parfum Homme Algérie",
    "name": "Classic",
    "brand": "Karl Lagerfeld",
    "brandSlug": "karl-lagerfeld",
    "category": "parfums-homme",
    "gender": "homme",
    "concentration": "EDT",
    "volume": "100ml",
    "price": 5200,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/karl-lagerfeld-classic.jpg",
    "shortDescription": "Karl Lagerfeld Classic est un fougère aromatique intemporel créé en 1984. Lavande, géranium et santal dans un parfum discret et élégant qui a traversé les décennies.",
    "description": "Karl Lagerfeld Classic est l'expression olfactive de la philosophie du Kaiser de la mode : l'élégance absolue par la sobriété. Créé en 1984, il reste à ce jour l'un des parfums masculins les plus appréciés pour sa qualité intemporelle et son rapport qualité-prix remarquable.\n\nLa composition est un fougère aromatique classique dans la grande tradition de la parfumerie masculine. L'ouverture fraîche et aromatique de lavande et de bergamote pose les bases d'un parfum discret et bien construit. Le cœur développe un accord herbacé-fleuri de géranium, romarin et un cœur légèrement boisé. La base apporte warmth et persistance avec du bois de santal, du vétiver et un musc propre qui reste agréable des heures après l'application.\n\nKarl Lagerfeld Classic est fait pour l'homme qui comprend que l'élégance véritable ne cherche pas à attirer l'attention. Sa sobriété est une force, et son intemporalité le rend pertinent depuis quatre décennies — une performance rare dans la parfumerie contemporaine.\n\nMaison Numidia vous propose ce classique avec livraison COD dans toutes les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Lavande", "Bergamote", "Camomille"],
      "heart": ["Géranium", "Romarin", "Néroli"],
      "base": ["Bois de santal", "Vétiver", "Musc"]
    },
    "family": "Fougère Aromatique",
    "occasions": ["Bureau", "Journée", "Casual"],
    "seasons": ["Printemps", "Automne"],
    "longevity": 3,
    "sillage": 2,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["cerruti-1881-homme", "davidoff-cool-water-homme", "azzaro-chrome"]
  },
  {
    "id": "nikos-sculpture-homme",
    "slug": "nikos-sculpture-homme",
    "h1": "Nikos Sculpture Parfum Homme Algérie",
    "name": "Sculpture pour Homme",
    "brand": "Nikos",
    "brandSlug": "nikos",
    "category": "parfums-homme",
    "gender": "homme",
    "concentration": "EDT",
    "volume": "100ml",
    "price": 4500,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/nikos-sculpture-homme.jpg",
    "shortDescription": "Nikos Sculpture pour Homme est un fougère frais et accessible né en 1994. Notes aquatiques, lavande et bois séché pour un parfum quotidien polyvalent et discret.",
    "description": "Nikos Sculpture pour Homme est la création du styliste grec Nikos Apostolopoulos, fondateur de la marque Nikos. Lancé en 1994, ce parfum s'est imposé comme une référence accessible dans la parfumerie masculine, appréciée pour sa fraîcheur propre et son caractère polyvalent.\n\nLa composition est un fougère frais aquatique typique des années 1990, époque où ce style olfactif connaissait son apogée. L'ouverture est une fraîcheur verte et marine immédiate — bergamote, notes marines et un soupçon de citrus — qui donne un caractère dynamique à la fragrance. Le cœur aromatique de lavande et de géranium structure la fragrance avec sobriété. La base légère de bois de cèdre, ambre et musc blanc assure une tenue discrète et agréable.\n\nSculpture pour Homme est le parfum quotidien idéal pour les hommes qui préfèrent les fragrances légères et non envahissantes. Sa modestie de sillage en fait un compagnon respectueux pour le bureau, le transport en commun ou les espaces partagés.\n\nMaison Numidia propose ce parfum authentique avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Bergamote", "Notes marines", "Citrus"],
      "heart": ["Lavande", "Géranium", "Aldéhydes"],
      "base": ["Cèdre", "Ambre", "Musc blanc"]
    },
    "family": "Fougère Aquatique",
    "occasions": ["Bureau", "Journée", "Quotidien"],
    "seasons": ["Printemps", "Été"],
    "longevity": 3,
    "sillage": 2,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["nikos-sculpture-femme", "azzaro-chrome", "davidoff-cool-water-homme"]
  },
  {
    "id": "nikos-sculpture-femme",
    "slug": "nikos-sculpture-femme",
    "h1": "Nikos Sculpture Parfum Femme Algérie",
    "name": "Sculpture pour Femme",
    "brand": "Nikos",
    "brandSlug": "nikos",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "EDP",
    "volume": "100ml",
    "price": 4500,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/nikos-sculpture-femme.jpg",
    "shortDescription": "Nikos Sculpture pour Femme est un floral fruité accessible et lumineux. Framboise, rose et musc pour une signature féminine douce et moderne à prix abordable.",
    "description": "Nikos Sculpture pour Femme est la réponse de la marque grecque aux femmes qui souhaitent un parfum de qualité à prix accessible. Comme son pendant masculin, il s'inscrit dans la tradition des fragrances propres et lumineuses qui traversent les saisons et les modes sans jamais se démoler.\n\nLa composition ouvre sur une fraîcheur fruitée de framboise, de pêche et d'agrumes qui met immédiatement de bonne humeur. Le cœur floral associe rose, jasmin et pivoine dans un bouquet léger et maternel. La base douce de musc blanc, de bois de santal et de vanille légère apporte douceur et persistance dans un accord enveloppant et rassurant.\n\nSculpture pour Femme convient parfaitement aux femmes de tous âges qui cherchent un parfum polyvalent, accessible et plaisir à porter au quotidien. Sa légèreté en fait un excellent choix pour le bureau et les situations où la discrétion est de mise.\n\nDisponible chez Maison Numidia avec livraison COD dans les 58 wilayas d'Algérie. Un parfum qui prouve que la qualité et l'accessibilité ne sont pas incompatibles.",
    "notes": {
      "top": ["Framboise", "Pêche", "Citrus"],
      "heart": ["Rose", "Jasmin", "Pivoine"],
      "base": ["Musc blanc", "Bois de santal", "Vanille légère"]
    },
    "family": "Floral Fruité",
    "occasions": ["Bureau", "Journée", "Quotidien"],
    "seasons": ["Printemps", "Été"],
    "longevity": 3,
    "sillage": 2,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["nikos-sculpture-homme", "chopard-wish", "lalique-amour"]
  },
  {
    "id": "ungaro-feminin",
    "slug": "ungaro-feminin",
    "h1": "Ungaro Feminin Parfum Femme Algérie",
    "name": "Feminin",
    "brand": "Ungaro",
    "brandSlug": "ungaro",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "EDP",
    "volume": "90ml",
    "price": 5900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/ungaro-feminin.jpg",
    "shortDescription": "Ungaro Feminin est un floral oriental sensuel signé de la maison parisienne Emmanuel Ungaro. Rose, santal et ambre dans une composition chaleureuse et féminement affirmée.",
    "description": "Ungaro Feminin est une création de la légendaire maison de couture parisienne Emmanuel Ungaro, connue pour ses robes ultra-féminines et ses tissus luxueux. Ce parfum porte en lui les valeurs esthétiques fondamentales de son créateur : sensualité, opulence et féminité sans complexe.\n\nLa composition est un floral oriental d'une générosité qui ne laisse pas indifférent. L'ouverture est une effusion de bergamote et de litchi qui apporte fraîcheur et attrait. Le cœur floral épanouit une rose de mai généreuse accompagnée de jasmin, de pivoine et une touche d'épices qui donnent du relief à la composition. La base est un accord oriental chaleureux : bois de santal, patchouli doux, ambre et musc vanillé qui confèrent à Feminin sa profondeur et sa persistance remarquables.\n\nFeminin s'adresse aux femmes qui assument pleinement leur féminité et qui aiment les parfums qui laissent une impression durable. Son caractère chaleureux le rend particulièrement adapté aux soirées d'automne et d'hiver en Algérie.\n\nMaison Numidia livre ce parfum authentique avec paiement à la réception dans les 58 wilayas.",
    "notes": {
      "top": ["Bergamote", "Litchi", "Mandarine"],
      "heart": ["Rose de mai", "Jasmin", "Pivoine", "Épices"],
      "base": ["Bois de santal", "Patchouli", "Ambre", "Musc vanillé"]
    },
    "family": "Floral Oriental",
    "occasions": ["Soirée", "Dîner", "Occasions spéciales"],
    "seasons": ["Automne", "Hiver"],
    "longevity": 4,
    "sillage": 4,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["escada-magnetism", "valentino-donna", "guerlain-samsara"]
  },
  {
    "id": "st-dupont-noir",
    "slug": "st-dupont-noir",
    "h1": "ST Dupont Noir Parfum Homme Algérie",
    "name": "Noir pour Homme",
    "brand": "S.T. Dupont",
    "brandSlug": "st-dupont",
    "category": "parfums-homme",
    "gender": "homme",
    "concentration": "EDP",
    "volume": "100ml",
    "price": 7200,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/st-dupont-noir.jpg",
    "shortDescription": "S.T. Dupont Noir est un boisé oriental raffiné qui incarne l'excellence des maisons luxueuses françaises. Fumé, poivré et boisé dans une composition pour l'homme d'exception.",
    "description": "S.T. Dupont Noir pour Homme est une fragrance qui porte avec fierté l'héritage d'une maison fondée en 1872, synonyme d'objets de luxe exceptionnels — briquets, stylos, maroquinerie. Ce parfum transpose en olfaction les valeurs de la maison : précision, noblesse des matières et caractère affirmé.\n\nLa composition est un boisé oriental sophistiqué où chaque note a été choisie avec la même exigence que les matériaux d'un briquet S.T. Dupont. L'ouverture est intense et précise : poivre noir, cardamome et bergamote dans un accord épicé-frais qui attire immédiatement le regard. Le cœur développe un accord boisé-fumé où la noix de muscade, le vétiver et la note de thé fumé créent une signature olfactive mémorable et originale. La base orientale de bois de oud, ambre et tonka est enveloppante et persistante.\n\nNoir est le parfum de l'homme qui n'a pas besoin de se justifier. Sa densité olfactive et son sillage marqué en font un choix idéal pour les soirées d'affaires, les dîners et les occasions où l'on veut marquer les esprits sans ostentation.\n\nDisponible chez Maison Numidia avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Poivre noir", "Cardamome", "Bergamote"],
      "heart": ["Muscade", "Vétiver", "Thé fumé"],
      "base": ["Bois de oud", "Ambre", "Tonka"]
    },
    "family": "Boisé Oriental",
    "occasions": ["Soirée", "Dîner d'affaires", "Événement"],
    "seasons": ["Automne", "Hiver"],
    "longevity": 4,
    "sillage": 4,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["cerruti-1881-homme", "karl-lagerfeld-classic", "mont-blanc-legend"]
  }
];

const allSlugs = new Set([...existingSlugs, ...newProducts.map(p => p.slug)]);
let errors = 0;
for (const p of newProducts) {
  if (existingSlugs.has(p.slug)) { console.error(`DUPLICATE: ${p.slug}`); errors++; }
  for (const r of p.related) {
    if (!allSlugs.has(r)) { console.error(`MISSING related "${r}" in ${p.slug}`); errors++; }
  }
}
if (errors > 0) { console.error(`${errors} erreur(s) — abandon`); process.exit(1); }

data.products.push(...newProducts);
writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf8');
console.log(`✅ ${newProducts.length} produits ajoutés — total: ${data.products.length} produits`);
