import { readFileSync, writeFileSync } from 'fs';
const filePath = 'data/products.json';
const data = JSON.parse(readFileSync(filePath, 'utf8'));
const existingSlugs = new Set(data.products.map(p => p.slug));

const newProducts = [
  {
    "id": "chanel-bleu-de-chanel-parfum",
    "slug": "chanel-bleu-de-chanel-parfum",
    "h1": "Chanel Bleu de Chanel Parfum Homme Algérie",
    "name": "Bleu de Chanel Parfum",
    "brand": "Chanel",
    "brandSlug": "chanel",
    "category": "parfums-homme",
    "gender": "homme",
    "concentration": "Parfum",
    "volume": "100ml",
    "price": 17900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/chanel-bleu-de-chanel-parfum.jpg",
    "shortDescription": "Bleu de Chanel Parfum est la version la plus intense et la plus concentrée de l'iconique Bleu de Chanel. Boisé aromatique d'exception, il incarne la masculinité moderne avec une profondeur et une longévité supérieures.",
    "description": "Chanel Bleu de Chanel Parfum représente l'évolution ultime de l'une des franchises parfumées masculines les plus célèbres au monde. Depuis le lancement du premier Bleu de Chanel en 2010, la maison a progressivement enrichi cette ligne avec des concentrations plus intenses, aboutissant au Parfum — la version la plus luxueuse et la plus mémorable.\n\nLà où l'EDT et l'EDP offraient une fraîcheur lumineuse et aromatique, le Parfum descend plus profondément dans les matières premières d'exception. La tête citrus et aromatique est présente mais plus discrète, laissant rapidement place à un accord boisé d'une richesse remarquable.\n\nLe cœur est dominé par le santal blanc, une matière première d'origine contrôlée travaillée avec un soin particulier. Il est accompagné de cèdre et de notes boisées sèches qui créent une texture enveloppante et masculine. La rose alba apporte une touche florale très subtile, presque imperceptible, mais qui contribue à la sophistication globale de la composition.\n\nLa base est profonde et persistante : ambre, vétiver et labdanum créent un fond chaud et boisé qui reste sur la peau pendant de nombreuses heures. Le Parfum dure nettement plus longtemps que les versions précédentes, justifiant pleinement son stationnement dans la hiérarchie des concentrations.\n\nParfait pour les hommes algériens qui recherchent un parfum raffiné et discret mais mémorable, adapté aussi bien au bureau qu'aux soirées. Disponible chez Maison Numidia, livraison dans les 58 wilayas par Yalidine, paiement à la réception.",
    "notes": {
      "top": ["Citron", "Menthe", "Lavande"],
      "heart": ["Santal blanc", "Cèdre", "Rose alba"],
      "base": ["Ambre", "Vétiver", "Labdanum", "Musc"]
    },
    "family": "Boisé Aromatique",
    "occasions": ["Bureau", "Soirée", "Quotidien"],
    "seasons": ["Automne", "Hiver", "Printemps"],
    "longevity": 5,
    "sillage": 4,
    "inStock": true,
    "featured": true,
    "isOriental": false,
    "related": ["chanel-n5-parfum", "dior-sauvage-parfum", "armani-acqua-di-gio-parfum"]
  },
  {
    "id": "chanel-gabrielle-essence",
    "slug": "chanel-gabrielle-essence",
    "h1": "Chanel Gabrielle Essence Parfum Femme Algérie",
    "name": "Gabrielle Chanel Essence",
    "brand": "Chanel",
    "brandSlug": "chanel",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "EDP",
    "volume": "100ml",
    "price": 16900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/chanel-gabrielle-essence.jpg",
    "shortDescription": "Gabrielle Chanel Essence est une version plus concentrée du Gabrielle, un hommage floral lumineux à Coco Chanel. Jasmin, ylang-ylang et rose s'unissent dans une composition féminine d'une grande élégance.",
    "description": "Chanel Gabrielle Essence est un hommage vibrant à la fondatrice emblématique de la maison, Gabrielle 'Coco' Chanel. Cette version Essence du parfum Gabrielle pousse la concentration florale encore plus loin, révélant la plénitude des fleurs blanches et leur sillage opulent.\n\nGabrielle Chanel était connue pour son amour des fleurs — particulièrement le jasmin, qu'elle aimait porter à même la peau. Ce parfum tente de capturer l'essence même de cette passion florale dans un flacon contemporain et raffiné.\n\nL'ouverture est fraîche et pétillante : des agrumes légers et des notes vertes créent une première impression de légèreté printanière. Rapidement, les quatre fleurs blanches emblématiques font leur entrée : le jasmin grandiflorum de Grasse, la tubéreuse, le ylang-ylang et l'orange blossom. Cet accord floral blanc est d'une générosité et d'une richesse remarquables.\n\nLe cœur floral est le cœur battant du parfum. Chaque fleur apporte sa signature : le jasmin sa sensualité, la tubéreuse sa profondeur crémeuse, le ylang-ylang son caractère exotique, l'orange blossom sa légèreté lumineuse. L'ensemble crée une symphonie florale d'une cohérence parfaite.\n\nLa base est délicate et persistante : musc blanc et bois légers supportent l'accord floral sans l'alourdir. Cette base garantit une longévité appréciable tout en conservant la légèreté caractéristique du parfum.\n\nDisponible chez Maison Numidia, livraison dans les 58 wilayas d'Algérie par Yalidine, paiement à la réception.",
    "notes": {
      "top": ["Citron", "Orange", "Cassis"],
      "heart": ["Jasmin de Grasse", "Tubéreuse", "Ylang-ylang", "Fleur d'oranger"],
      "base": ["Musc blanc", "Bois blanc", "Cèdre"]
    },
    "family": "Floral Blanc",
    "occasions": ["Quotidien", "Soirée", "Rendez-vous"],
    "seasons": ["Printemps", "Été", "Automne"],
    "longevity": 4,
    "sillage": 4,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["chanel-n5-parfum", "chanel-chance-eau-vive", "lancome-la-vie-est-belle-florale"]
  },
  {
    "id": "armani-acqua-di-gio-parfum",
    "slug": "armani-acqua-di-gio-parfum",
    "h1": "Armani Acqua di Giò Parfum Homme Algérie",
    "name": "Acqua di Giò Parfum",
    "brand": "Giorgio Armani",
    "brandSlug": "armani",
    "category": "parfums-homme",
    "gender": "homme",
    "concentration": "Parfum",
    "volume": "75ml",
    "price": 14900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/armani-acqua-di-gio-parfum.jpg",
    "shortDescription": "Acqua di Giò Parfum d'Armani est la concentration ultime de ce classique masculin iconique. Notes marines et boisées avec une profondeur ambrée inédite pour la version la plus intense de ce parfum légendaire.",
    "description": "Giorgio Armani Acqua di Giò Parfum est l'aboutissement d'une saga parfumée qui dure depuis 1996. Depuis le lancement de l'Acqua di Giò original qui a révolutionné la parfumerie masculine en introduisant les accords aquatiques-boisés, Armani n'a cessé d'enrichir et d'approfondir cette création iconique.\n\nLe Parfum, lancé en 2021, représente la version la plus concentrée et la plus intense de cette ligne. Il ne se contente pas d'amplifier le parfum original — il le réinterprète, en explorant des territoires boisés et minéraux plus profonds tout en conservant la signature aquatique emblématique.\n\nL'ouverture conserve cette fraîcheur marine immédiatement reconnaissable qui a fait la réputation d'Acqua di Giò. La note de bergamote et les accords d'eau de mer créent une première impression fraîche et vivifiante. Mais rapidement, le Parfum révèle sa profondeur supplémentaire.\n\nLe cœur est plus complexe que les versions précédentes : le romarin, le patchouli et le cyprès s'associent aux notes marines pour créer un accord boisé-aquatique d'une grande sophistication. Ce cœur est plus sombre, plus mystérieux, plus masculin que l'EDT original.\n\nLa base est la grande révélation de cette version : un accord ambre-boisé-minéral d'une profondeur inhabituelle pour un parfum Acqua di Giò. L'encens, le vétiver et l'ambre gris créent un fond chaud et persistant qui reste sur la peau des heures durant.\n\nDisponible chez Maison Numidia, livraison dans les 58 wilayas d'Algérie par Yalidine, paiement à la réception.",
    "notes": {
      "top": ["Bergamote", "Eau de mer", "Citron vert"],
      "heart": ["Romarin", "Patchouli", "Cyprès"],
      "base": ["Encens", "Vétiver", "Ambre gris", "Musc"]
    },
    "family": "Aquatique Boisé",
    "occasions": ["Bureau", "Quotidien", "Soirée"],
    "seasons": ["Printemps", "Été", "Automne"],
    "longevity": 5,
    "sillage": 4,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["chanel-bleu-de-chanel-parfum", "dior-sauvage-parfum", "givenchy-gentleman-parfum"]
  },
  {
    "id": "givenchy-gentleman-parfum",
    "slug": "givenchy-gentleman-parfum",
    "h1": "Givenchy Gentleman Parfum Homme Algérie",
    "name": "Gentleman Parfum",
    "brand": "Givenchy",
    "brandSlug": "givenchy",
    "category": "parfums-homme",
    "gender": "homme",
    "concentration": "Parfum",
    "volume": "60ml",
    "price": 13900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/givenchy-gentleman-parfum.jpg",
    "shortDescription": "Gentleman Parfum de Givenchy est la version ultime du Gentleman, un oriental boisé intense et raffiné. Iris poudreux, vétiver profond et vanille crémeuse pour un homme au caractère affirmé.",
    "description": "Givenchy Gentleman Parfum est la concentration suprême de la ligne Gentleman, une gamme masculine qui a su se réinventer tout en restant fidèle à ses valeurs fondatrices : élégance, masculinité et sophistication. Cette version Parfum représente l'expression la plus intense et la plus raffinée de ce caractère masculin.\n\nL'histoire du Gentleman chez Givenchy remonte à 1974, mais c'est la reformulation contemporaine qui a véritablement conquis les hommes modernes. Chaque nouvelle version a apporté sa propre vision, et le Parfum est la conclusion logique de cette évolution vers plus de profondeur et de complexité.\n\nL'ouverture est directe et affirmée : les notes poivrées et épicées annoncent d'emblée un parfum de caractère. Le poivre noir et la cardamome créent une tête dynamique qui attire l'attention sans être agressive.\n\nLe cœur révèle l'iris dans toute sa noblesse poudreuse et terreuse. L'iris est une matière première extrêmement précieuse — sa culture et son extraction durent plusieurs années. Ici, il s'associe à l'orris root et au patchouli pour créer un accord floral-terreux d'une grande sophistication.\n\nLa base est la véritable signature de cette version Parfum. Le vétiver fumé, la vanille crémeuse et le musc créent un fond chaud, enveloppant et persistant qui distingue clairement cette concentration des versions précédentes. C'est ici que le Gentleman Parfum justifie pleinement son statut haut de gamme.\n\nDisponible chez Maison Numidia, livraison dans les 58 wilayas d'Algérie par Yalidine, paiement à la réception.",
    "notes": {
      "top": ["Poivre noir", "Cardamome", "Bergamote"],
      "heart": ["Iris", "Orris root", "Patchouli"],
      "base": ["Vétiver", "Vanille", "Musc", "Encens"]
    },
    "family": "Oriental Boisé",
    "occasions": ["Soirée", "Bureau", "Événement"],
    "seasons": ["Automne", "Hiver"],
    "longevity": 5,
    "sillage": 4,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["armani-acqua-di-gio-parfum", "chanel-bleu-de-chanel-parfum", "parfums-de-marly-pegasus"]
  },
  {
    "id": "burberry-hero-parfum",
    "slug": "burberry-hero-parfum",
    "h1": "Burberry Hero Parfum Homme Algérie",
    "name": "Hero Parfum",
    "brand": "Burberry",
    "brandSlug": "burberry",
    "category": "parfums-homme",
    "gender": "homme",
    "concentration": "Parfum",
    "volume": "100ml",
    "price": 12900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/burberry-hero-parfum.jpg",
    "shortDescription": "Burberry Hero Parfum est la version la plus intense de Hero, un boisé cèdre d'une profondeur remarquable. Plus sombre et plus mystérieux que l'EDT, il révèle la dimension animale et boisée du Hero.",
    "description": "Burberry Hero Parfum est l'expression la plus intense et la plus sombre de la gamme Hero lancée par Burberry. Là où l'EDT proposait une fraîcheur boisée accessible et moderne, le Parfum plonge dans des territoires plus profonds et plus sensuels, révélant une dimension véritablement héroïque.\n\nLa maison Burberry, fondée à Basingstoke en 1856, est une institution britannique qui a su traverser les époques tout en restant résolument contemporaine. Sa ligne de parfumerie reflète cette dualité : respect de l'héritage et ouverture vers l'avenir.\n\nL'ouverture du Parfum est plus discrète que celle de l'EDT, les agrumes laissant rapidement place à des accords boisés plus profonds. Les notes de pin et de cèdre créent une atmosphère forestière, presque sauvage, qui évoque immédiatement les grands espaces naturels.\n\nLe cœur est dominé par le cèdre de Virginie, une matière boisée d'une grande qualité qui apporte à la fois sécheresse et chaleur. La bergamote et le genièvre apportent des touches aromatiques qui maintiennent une certaine fraîcheur au sein de cet accord boisé intense.\n\nLa base est animale et profonde. L'ambre, le musc et les notes cuirées créent un fond qui rappelle le cuir et le tabac, des évocations masculines intemporelles. Cette base est longue et persistante, garantissant un sillage remarquable pendant de nombreuses heures.\n\nDisponible chez Maison Numidia, livraison dans les 58 wilayas d'Algérie par Yalidine, paiement à la réception.",
    "notes": {
      "top": ["Bergamote", "Pin", "Citron"],
      "heart": ["Cèdre de Virginie", "Genièvre", "Noix de muscade"],
      "base": ["Ambre", "Musc", "Cuir", "Vétiver"]
    },
    "family": "Boisé Aromatique",
    "occasions": ["Soirée", "Week-end", "Automne-Hiver"],
    "seasons": ["Automne", "Hiver"],
    "longevity": 5,
    "sillage": 4,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["chanel-bleu-de-chanel-parfum", "givenchy-gentleman-parfum", "paco-rabanne-phantom-parfum"]
  },
  {
    "id": "hugo-boss-bottled-parfum",
    "slug": "hugo-boss-bottled-parfum",
    "h1": "Hugo Boss Bottled Parfum Homme Algérie",
    "name": "Boss Bottled Parfum",
    "brand": "Hugo Boss",
    "brandSlug": "hugo-boss",
    "category": "parfums-homme",
    "gender": "homme",
    "concentration": "Parfum",
    "volume": "100ml",
    "price": 9900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/hugo-boss-bottled-parfum.jpg",
    "shortDescription": "Boss Bottled Parfum de Hugo Boss est la version ultime du classique Boss Bottled. Un accord boisé épicé plus intense, avec de la vanille et de l'ambre pour un homme moderne et sûr de lui.",
    "description": "Hugo Boss Bottled Parfum est l'aboutissement d'une saga parfumée qui dure depuis 1998. Depuis le lancement du premier Boss Bottled qui a conquis des millions d'hommes à travers le monde, Hugo Boss n'a cessé d'enrichir cette ligne avec des nouvelles concentrations et interprétations.\n\nLe Boss Bottled original est depuis longtemps une valeur sûre de la parfumerie masculine : accessible, agréable et consensuel, il convient à tous les hommes et toutes les occasions. La version Parfum conserve ces qualités tout en ajoutant une profondeur et une intensité supplémentaires.\n\nL'ouverture est chaude et épicée : la cannelle et les épices douces créent une première impression chaleureuse qui diffère légèrement des versions précédentes, plus fruitées. Le pomme, signature de la ligne depuis l'origine, est toujours présente mais dans un rôle plus discret.\n\nLe cœur est boisé et épicé, dominé par le géranium et les notes épicées. C'est un accord masculin classique mais traité avec une sophistication qui le distingue de nombreux parfums de sa catégorie.\n\nLa base est la véritable différence avec les versions précédentes : vanille crémeuse, ambre et musc chaud créent un fond gourmand-boisé particulièrement persistant et séduisant. Cette base est ce qui fait du Parfum un choix idéal pour les soirées et les occasions importantes.\n\nDisponible chez Maison Numidia, livraison dans les 58 wilayas d'Algérie par Yalidine, paiement à la réception.",
    "notes": {
      "top": ["Pomme", "Cannelle", "Citron"],
      "heart": ["Géranium", "Épices", "Bois de santal"],
      "base": ["Vanille", "Ambre", "Musc", "Vétiver"]
    },
    "family": "Oriental Boisé",
    "occasions": ["Bureau", "Soirée", "Quotidien"],
    "seasons": ["Automne", "Hiver"],
    "longevity": 5,
    "sillage": 4,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["armani-acqua-di-gio-parfum", "givenchy-gentleman-parfum", "paco-rabanne-phantom-parfum"]
  },
  {
    "id": "guerlain-mon-guerlain-intense",
    "slug": "guerlain-mon-guerlain-intense",
    "h1": "Guerlain Mon Guerlain Intense Parfum Femme Algérie",
    "name": "Mon Guerlain Intense",
    "brand": "Guerlain",
    "brandSlug": "guerlain",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "EDP Intense",
    "volume": "100ml",
    "price": 13900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/guerlain-mon-guerlain-intense.jpg",
    "shortDescription": "Mon Guerlain Intense est une version plus gourmande et profonde du Mon Guerlain. Lavande de Provence, bergamote et vanille Tahitienne intensifiées pour une fragrance féminine d'une sensualité affirmée.",
    "description": "Guerlain Mon Guerlain Intense est une interprétation plus profonde et plus enveloppante du Mon Guerlain original, l'un des parfums féminins contemporains les plus appréciés de la maison Guerlain. Cette version Intense pousse les curseurs de la gourmandise et de la sensualité, révélant les matières premières dans leur expression la plus riche.\n\nGuerlain, fondée en 1828, est l'une des maisons de parfumerie les plus emblématiques au monde. Son savoir-faire unique dans le travail des matières naturelles, notamment la vanille Tahitienne et la lavande de Provence, se retrouve pleinement dans Mon Guerlain Intense.\n\nL'ouverture est fraîche et lumineuse : bergamote italienne et lavande de Provence créent une tête aromatique-florale immédiatement séduisante. La lavande, ingrédient signature de la ligne, est ici utilisée dans une qualité supérieure pour garantir son authenticité.\n\nLe cœur est floral et légèrement gourmand. L'iris, la sambac jasmine et le lait d'amande s'associent pour créer un accord doux et féminin qui rappelle la peau chaude. C'est dans ce cœur que l'intensité de cette version s'affirme le plus clairement.\n\nLa base est la révélation de Mon Guerlain Intense : la vanille Tahitienne, travaillée selon les techniques propres à Guerlain, offre une douceur crémeuse et chaude incomparable. Elle est soutenue par le musc blanc et le bois de santal pour créer un fond persistant et enveloppant.\n\nDisponible chez Maison Numidia, livraison dans les 58 wilayas d'Algérie par Yalidine, paiement à la réception.",
    "notes": {
      "top": ["Bergamote", "Lavande de Provence"],
      "heart": ["Iris", "Jasmin sambac", "Lait d'amande"],
      "base": ["Vanille Tahitienne", "Musc blanc", "Bois de santal"]
    },
    "family": "Gourmand Floral",
    "occasions": ["Soirée", "Rendez-vous", "Automne-Hiver"],
    "seasons": ["Automne", "Hiver"],
    "longevity": 5,
    "sillage": 4,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["chanel-gabrielle-essence", "lancome-la-nuit-tresor-nu", "yves-saint-laurent-mon-paris-intensement"]
  },
  {
    "id": "lancome-la-nuit-tresor-nu",
    "slug": "lancome-la-nuit-tresor-nu",
    "h1": "Lancôme La Nuit Trésor Nu Parfum Femme Algérie",
    "name": "La Nuit Trésor Nu",
    "brand": "Lancôme",
    "brandSlug": "lancome",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "EDP",
    "volume": "100ml",
    "price": 12900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/lancome-la-nuit-tresor-nu.jpg",
    "shortDescription": "La Nuit Trésor Nu de Lancôme est une interprétation sensuelle et épurée du Trésor. Rose centifolia, lychee et musc blanc pour un parfum féminin nocturne d'une élégance absolue.",
    "description": "Lancôme La Nuit Trésor Nu est l'évolution la plus contemporaine de la saga Trésor, l'une des lignes parfumées féminines les plus emblématiques de la maison parisienne. Là où le Trésor original (1990) proposait un floral aldéhydé classique et La Nuit Trésor un oriental sensuel, La Nuit Trésor Nu offre une vision plus épurée et moderne de la séduction nocturne.\n\nLe nom 'Nu' évoque la nudité dans son sens le plus poétique : une beauté naturelle, sans artifice, qui laisse transparaître la vraie personnalité. C'est exactement ce que ce parfum tente de capturer — l'essence même de la féminité contemporaine.\n\nL'ouverture est lumineuse et fruitée : le litchi rose et la bergamote créent une première impression fraîche et légèrement sucrée qui invite immédiatement à poursuivre le voyage olfactif. Cette entrée est moderne et accessible, très différente du style plus classique des anciennes versions.\n\nLe cœur est dominé par la rose centifolia de Grasse, l'une des matières premières les plus précieuses de la parfumerie. Ici, elle s'exprime dans toute sa pureté et sa complexité florale, accompagnée d'un accord de musc soyeux qui lui donne une dimension charnelle et sensuelle.\n\nLa base est minimaliste et efficace : musc blanc, bois de santal et ambre gris créent un fond aérien mais persistant, qui reste sur la peau de manière très discrète mais remarquable. Un parfum de peau qui semble venir de l'intérieur.\n\nDisponible chez Maison Numidia, livraison dans les 58 wilayas d'Algérie par Yalidine, paiement à la réception.",
    "notes": {
      "top": ["Litchi", "Bergamote", "Pamplemousse rose"],
      "heart": ["Rose centifolia", "Musc soyeux", "Pivoine"],
      "base": ["Musc blanc", "Bois de santal", "Ambre gris"]
    },
    "family": "Floral Musqué",
    "occasions": ["Soirée", "Rendez-vous", "Nuit"],
    "seasons": ["Printemps", "Été", "Automne"],
    "longevity": 4,
    "sillage": 3,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["guerlain-mon-guerlain-intense", "lancome-idole-le-parfum", "chanel-gabrielle-essence"]
  },
  {
    "id": "ysl-myslf",
    "slug": "ysl-myslf",
    "h1": "Yves Saint Laurent MYSLF Parfum Homme Algérie",
    "name": "MYSLF",
    "brand": "Yves Saint Laurent",
    "brandSlug": "ysl",
    "category": "parfums-homme",
    "gender": "homme",
    "concentration": "EDP",
    "volume": "100ml",
    "price": 13900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/ysl-myslf.jpg",
    "shortDescription": "MYSLF de YSL est le parfum masculin le plus ambitieux de la maison depuis Y. Orange Calabria et fleur d'oranger sur fond de bois de santal pour un EDP hors norme qui célèbre l'authenticité masculine.",
    "description": "Yves Saint Laurent MYSLF est l'une des lancements les plus ambitieux de la maison dans le segment masculin des dernières années. Ce parfum, dont le nom phonétique 'myself' est une déclaration d'identité, célèbre la liberté de s'assumer pleinement, sans compromis.\n\nLancé en 2023, MYSLF s'inscrit dans une tendance contemporaine qui valorise l'authenticité et la singularité masculines, loin des codes conventionnels. YSL, maison créée par le couturier visionnaire Yves Saint Laurent en 1961, a toujours été à l'avant-garde de cette libération des genres et des normes.\n\nL'ouverture est solaire et méditerranéenne : l'orange de Calabre, récoltée dans la région italienne qui produit les agrumes les plus parfumés au monde, crée une tête lumineuse et vitaminée. Cette orange est fraîche, juteuse, presque tangible dans sa réalité olfactive.\n\nLe cœur est dominé par la fleur d'oranger, une matière première délicate et envoûtante qui apporte une dimension florale légèrement médicale et mielleuse. Le géranium ajoute une note herbacée qui maintient le caractère masculin de la composition.\n\nLa base est la grande force de MYSLF : le bois de santal australien, d'une crémeuse et d'une douceur incomparables, crée un fond enveloppant et sensuel. Le musc ambré renforce cette impression de chaleur et de proximité. Un parfum qui colle littéralement à la peau et y reste des heures.\n\nDisponible chez Maison Numidia, livraison dans les 58 wilayas d'Algérie par Yalidine, paiement à la réception.",
    "notes": {
      "top": ["Orange de Calabre", "Bergamote", "Citron"],
      "heart": ["Fleur d'oranger", "Géranium", "Jasmin"],
      "base": ["Bois de santal australien", "Musc ambré", "Cèdre"]
    },
    "family": "Boisé Floral Aromatique",
    "occasions": ["Bureau", "Quotidien", "Rendez-vous"],
    "seasons": ["Printemps", "Été", "Automne"],
    "longevity": 4,
    "sillage": 4,
    "inStock": true,
    "featured": true,
    "isOriental": false,
    "related": ["chanel-bleu-de-chanel-parfum", "armani-acqua-di-gio-parfum", "dior-sauvage-parfum"]
  },
  {
    "id": "paco-rabanne-phantom-le-parfum",
    "slug": "paco-rabanne-phantom-le-parfum",
    "h1": "Paco Rabanne Phantom Le Parfum Homme Algérie",
    "name": "Phantom Le Parfum",
    "brand": "Paco Rabanne",
    "brandSlug": "paco-rabanne",
    "category": "parfums-homme",
    "gender": "homme",
    "concentration": "Parfum",
    "volume": "100ml",
    "price": 12900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/paco-rabanne-phantom-le-parfum.jpg",
    "shortDescription": "Phantom Le Parfum de Paco Rabanne pousse le robot légendaire encore plus loin. Version ultra-concentrée et boisée du Phantom EDT, avec de la lavande robotique et un fond de bois de oud intenses.",
    "description": "Paco Rabanne Phantom Le Parfum représente l'évolution la plus intense et la plus audacieuse du Phantom, ce parfum masculin iconique présenté dans son flacon en forme de robot qui a conquis le monde à sa sortie. Cette version Parfum amplifie chaque élément de la composition originale, révélant une profondeur inattendue.\n\nLa maison Paco Rabanne, fondée en 1966 par le créateur basco-espagnol Francisco Rabaneda, est connue pour ses créations avant-gardistes et ses parfums unisexes comme 1 Million et Invictus. Le Phantom Le Parfum s'inscrit dans cette tradition d'audace et d'innovation.\n\nL'ouverture est plus sombre que celle de l'EDT : la lavande aromatique se mêle à des notes légèrement métalliques et froides qui évoquent le robot emblématique du flacon. Cette ouverture est distinctive et immédiatement reconnaissable.\n\nLe cœur est dominé par un accord boisé-ambrosal qui crée une signature olfactive unique. Le bois de patchouli et l'ambroxan s'associent pour créer cette texture distinctive que les amateurs de parfums reconnaissent immédiatement. L'accord est moderne, presque futuriste, en parfaite harmonie avec l'identité visuelle du flacon.\n\nLa base est profonde et encensée. Le bois de oud, l'encens et l'ambre gris créent un fond oriental et boisé d'une persistance exceptionnelle. Cette base orientale est la grande nouveauté par rapport au Phantom EDT et justifie pleinement l'appellation Parfum.\n\nDisponible chez Maison Numidia, livraison dans les 58 wilayas d'Algérie par Yalidine, paiement à la réception.",
    "notes": {
      "top": ["Lavande", "Citron vert", "Notes métalliques"],
      "heart": ["Patchouli", "Ambroxan", "Vétiver"],
      "base": ["Bois de oud", "Encens", "Ambre gris", "Musc"]
    },
    "family": "Boisé Aromatique",
    "occasions": ["Soirée", "Nuit", "Événement"],
    "seasons": ["Automne", "Hiver"],
    "longevity": 5,
    "sillage": 5,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["paco-rabanne-phantom-parfum", "hugo-boss-bottled-parfum", "burberry-hero-parfum"]
  },
  {
    "id": "juliette-has-a-gun-not-a-perfume",
    "slug": "juliette-has-a-gun-not-a-perfume",
    "h1": "Juliette Has A Gun Not A Perfume Algérie",
    "name": "Not A Perfume",
    "brand": "Juliette Has A Gun",
    "brandSlug": "juliette-has-a-gun",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "EDP",
    "volume": "100ml",
    "price": 14900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/juliette-has-a-gun-not-a-perfume.jpg",
    "shortDescription": "Not A Perfume de Juliette Has A Gun est un minimaliste radical : une molécule unique, l'Ambroxan, sans aucun autre ingrédient. Un parfum de peau d'une pureté absolue qui s'adapte à chaque personne.",
    "description": "Juliette Has A Gun Not A Perfume est l'un des parfums les plus fascinants et les plus philosophiquement cohérents de la parfumerie contemporaine. Sa prémisse est radicale : se contenter d'une seule molécule de synthèse, l'Ambroxan, sans aucune autre note additionnelle.\n\nL'Ambroxan est une molécule synthétique créée à partir de l'ambre gris — cette sécrétion naturelle du cachalot autrefois utilisée dans la parfumerie. Elle est reconnue pour sa qualité exceptionnelle : elle est à la fois musc, ambre et quelque chose d'indéfinissable, une sorte d'écho de la peau humaine.\n\nCe qui rend Not A Perfume unique, c'est sa capacité à réagir différemment sur chaque personne. Selon la chimie cutanée de l'individu, le parfum peut être discret et doux ou plus affirmé et profond. Il devient réellement \"votre parfum\", une extension de votre propre odeur naturelle plutôt qu'un masque appliqué dessus.\n\nLa maison Juliette Has A Gun, fondée en 2005 par Romano Ricci, petit-fils de Nina Ricci, a toujours valorisé l'audace et la subversion. Ce parfum, avec son nom provocateur 'Pas un parfum', incarne parfaitement cet esprit.\n\nNot A Perfume est devenu un phénomène culturel dans le monde du parfum niche, cité dans d'innombrables magazines et blogs olfactifs comme le parfum le plus minimaliste et le plus intellectuellement honnête jamais créé.\n\nDisponible chez Maison Numidia, livraison dans les 58 wilayas d'Algérie par Yalidine, paiement à la réception.",
    "notes": {
      "top": ["Ambroxan"],
      "heart": ["Ambroxan"],
      "base": ["Ambroxan"]
    },
    "family": "Musqué Ambré",
    "occasions": ["Quotidien", "Bureau", "Peau nue"],
    "seasons": ["Toutes saisons"],
    "longevity": 4,
    "sillage": 3,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["byredo-gypsy-water", "ex-nihilo-fleur-narcotique", "diptyque-philosykos"]
  },
  {
    "id": "tom-ford-oud-wood-intense",
    "slug": "tom-ford-oud-wood-intense",
    "h1": "Tom Ford Oud Wood Intense Parfum Unisexe Algérie",
    "name": "Oud Wood Intense",
    "brand": "Tom Ford",
    "brandSlug": "tom-ford",
    "category": "parfums-orientaux",
    "gender": "unisexe",
    "concentration": "EDP",
    "volume": "75ml",
    "price": 22900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/tom-ford-oud-wood-intense.jpg",
    "shortDescription": "Oud Wood Intense de Tom Ford est une version amplifiée du légendaire Oud Wood. Plus sombre et plus enveloppant, il pousse le bois de oud dans ses retranchements les plus exquis.",
    "description": "Tom Ford Oud Wood Intense est la version amplifiée et enrichie du légendaire Oud Wood, parfum qui a largement contribué à démocratiser le bois de oud dans la parfumerie occidentale lors de son lancement en 2007. Cette version Intense ne se contente pas d'augmenter la concentration — elle réinterprète l'accord dans une direction plus sombre et plus enveloppante.\n\nLa Private Blend de Tom Ford, fondée en 2006, représente le segment le plus exclusif de la maison. Ces parfums sont conçus pour des amateurs exigeants qui recherchent des matières premières d'exception et des compositions qui sortent des sentiers battus.\n\nL'ouverture de l'Intense est plus directement boisée que celle de l'original. Les notes fumées et épicées s'imposent immédiatement, créant une entrée en matière sombre et mystérieuse. Le cardamome et le poivre rose ajoutent une dimension épicée qui enrichit l'accord.\n\nLe cœur est dominé par le bois de oud dans ses facettes les plus riches et les plus complexes. Ici, le oud est traité comme une matière noble et précieuse, non pas comme un accord de fond mais comme un ingrédient central qui structure toute la composition. Il est accompagné de bois de santal crémeux et de vétiver fumé.\n\nLa base est profonde, persistante et enveloppante. L'ambre boisé, l'encens et le musc créent un fond oriental d'une longueur impressionnante. Oud Wood Intense est un parfum qui demande à s'apprivoiser — son intensité peut surprendre lors des premiers essais, mais il révèle progressivement une beauté sombre et addictive.\n\nDisponible chez Maison Numidia, livraison dans les 58 wilayas d'Algérie par Yalidine, paiement à la réception.",
    "notes": {
      "top": ["Bois de oud", "Cardamome", "Poivre rose"],
      "heart": ["Bois de santal", "Vétiver fumé", "Encens"],
      "base": ["Ambre boisé", "Musc", "Labdanum", "Vétiver"]
    },
    "family": "Oriental Boisé Oudé",
    "occasions": ["Soirée", "Hiver", "Événement"],
    "seasons": ["Automne", "Hiver"],
    "longevity": 5,
    "sillage": 4,
    "inStock": true,
    "featured": false,
    "isOriental": true,
    "related": ["initio-oud-for-greatness", "penhaligons-halfeti", "amouage-beloved-homme"]
  }
];

const allSlugs = new Set([...existingSlugs, ...newProducts.map(p => p.slug)]);
let errors = 0;
for (const p of newProducts) {
  if (existingSlugs.has(p.slug)) { console.error(`DUPLICATE: ${p.slug}`); errors++; }
  for (const r of p.related) {
    if (!allSlugs.has(r)) { console.error(`MISSING related "${r}" in ${p.slug}`); errors++; }
  }
}
if (errors > 0) { console.error(`${errors} erreur(s) — abandon`); process.exit(1); }
data.products.push(...newProducts);
writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf8');
console.log(`✅ ${newProducts.length} produits ajoutés — total: ${data.products.length} produits`);
