import { readFileSync, writeFileSync } from 'fs';

const filePath = 'data/products.json';
const data = JSON.parse(readFileSync(filePath, 'utf8'));
const existingSlugs = new Set(data.products.map(p => p.slug));

const newProducts = [
  {
    "id": "kate-spade-live-colorfully",
    "slug": "kate-spade-live-colorfully",
    "h1": "Kate Spade Live Colorfully Parfum Femme Algérie",
    "name": "Live Colorfully",
    "brand": "Kate Spade",
    "brandSlug": "kate-spade",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "EDP",
    "volume": "100ml",
    "price": 6200,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/kate-spade-live-colorfully.jpg",
    "shortDescription": "Kate Spade Live Colorfully est un floral fruité joyeux et solaire. Mandarine, jasmin et musc blanc dans un parfum pétillant signé de la maison new-yorkaise Kate Spade.",
    "description": "Kate Spade Live Colorfully est une ode à la joie de vivre et à l'audace chromatique de la maison new-yorkaise. Créée pour la femme qui ose les couleurs et refuse la grisaille, cette fragrance est un concentré d'optimisme dans un flacon aussi élégant que coloré.\n\nLa composition s'ouvre sur une effusion fruitée solaire de mandarine, framboise et miel d'agave — un accord sucré-fruité qui rappelle les marchés de fruits estivaux. Le cœur floral associe jasmin, fleur d'oranger et pivoine dans un bouquet joyeux et lumineux. La base de musc blanc, bois de cèdre et ambre apporte la tenue et la douceur nécessaires pour que ce parfum reste agréable toute la journée.\n\nLive Colorfully est le parfum des femmes qui vivent avec intensité et qui voient le monde en couleurs. Sa légèreté et sa fraîcheur fruitée-florale en font un excellent choix pour le bureau et les sorties du week-end en Algérie.\n\nMaison Numidia propose ce parfum Kate Spade authentique avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Mandarine", "Framboise", "Miel d'agave"],
      "heart": ["Jasmin", "Fleur d'oranger", "Pivoine"],
      "base": ["Musc blanc", "Cèdre", "Ambre"]
    },
    "family": "Floral Fruité",
    "occasions": ["Bureau", "Journée", "Week-end"],
    "seasons": ["Printemps", "Été"],
    "longevity": 3,
    "sillage": 3,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["kate-spade-in-full-bloom", "coach-floral", "chloe-love-story"]
  },
  {
    "id": "kate-spade-in-full-bloom",
    "slug": "kate-spade-in-full-bloom",
    "h1": "Kate Spade In Full Bloom Parfum Femme Algérie",
    "name": "In Full Bloom",
    "brand": "Kate Spade",
    "brandSlug": "kate-spade",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "EDP",
    "volume": "100ml",
    "price": 6200,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/kate-spade-in-full-bloom.jpg",
    "shortDescription": "Kate Spade In Full Bloom est un floral pétale lumineux et féminin. Cerisier, pivoine et jasmin dans une composition printanière d'une délicatesse rare.",
    "description": "Kate Spade In Full Bloom est une fragrance qui célèbre le printemps et la féminité dans toute leur splendeur. Son flacon iconique en forme de tulipe est une oeuvre de design qui capture l'essence même du style Kate Spade : élégant, original et plein de fantaisie.\n\nLa composition est un floral lumineux d'une délicatesse désarmante. L'ouverture est fraîche et légèrement fruitée — fleur de cerisier, pétales de rose et une touche de cassis — qui évoque un jardin en fleurs. Le cœur déploie un bouquet floral généreux dominé par la pivoine, le jasmin star et l'iris. La base légère de musc blanc, ambre doux et bois de cèdre préserve la fraîcheur de la composition tout en lui apportant une durée satisfaisante.\n\nIn Full Bloom convient à la femme qui aime les parfums floraux authentiques et raffinés, loin des compositions sucrées artificelles. Sa légèreté printanière en fait un compagnon idéal pour les beaux jours et les occasions où l'on veut sentir naturellement bon.\n\nDisponible chez Maison Numidia avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Fleur de cerisier", "Cassis", "Rose"],
      "heart": ["Pivoine", "Jasmin star", "Iris"],
      "base": ["Musc blanc", "Ambre doux", "Cèdre"]
    },
    "family": "Floral",
    "occasions": ["Bureau", "Journée", "Printemps"],
    "seasons": ["Printemps", "Été"],
    "longevity": 3,
    "sillage": 2,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["kate-spade-live-colorfully", "nina-ricci-coeur-joie", "guerlain-mon-guerlain-sparkling-bouquet"]
  },
  {
    "id": "anna-sui-dolly-girl",
    "slug": "anna-sui-dolly-girl",
    "h1": "Anna Sui Dolly Girl Parfum Femme Algérie",
    "name": "Dolly Girl",
    "brand": "Anna Sui",
    "brandSlug": "anna-sui",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "EDT",
    "volume": "75ml",
    "price": 5200,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/anna-sui-dolly-girl.jpg",
    "shortDescription": "Anna Sui Dolly Girl est un floral fruité espiègle et romantique. Poire, rose et musc dans un parfum doux et féminin qui capture l'univers fantaisiste de la créatrice américaine.",
    "description": "Anna Sui Dolly Girl est une fragrance qui plonge dans l'univers fantaisiste et romanesque de la styliste américaine d'origine chinoise. La maison Anna Sui est connue pour ses collections aux inspirations pop et bohèmes, et ses parfums reflètent fidèlement cette identité unique mêlant féminité, fantaisie et touches de douceur vintage.\n\nDolly Girl s'ouvre sur un accord fruité charmant de poire juteuse et de framboise, avec une pointe de bergamote qui apporte de la vivacité. Le cœur révèle une rose fraîche et lumineuse accompagnée d'iris et de fleur de coton dans un accord délicatement floral et poudré. La base douce de musc blanc et bois de santal enveloppe la peau d'une douceur rassurante.\n\nDolly Girl est la fragrance des femmes qui assument leur côté rêveur et romanesque. Son caractère léger et fruité-floral en fait un parfum agréable au quotidien, sans jamais être envahissant.\n\nDisponible chez Maison Numidia avec livraison COD dans toutes les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Poire", "Framboise", "Bergamote"],
      "heart": ["Rose", "Iris", "Fleur de coton"],
      "base": ["Musc blanc", "Bois de santal", "Cèdre"]
    },
    "family": "Floral Fruité",
    "occasions": ["Journée", "Casual", "Week-end"],
    "seasons": ["Printemps", "Été"],
    "longevity": 3,
    "sillage": 2,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["marc-jacobs-daisy", "jennifer-lopez-glow", "coach-floral"]
  },
  {
    "id": "dkny-golden-delicious",
    "slug": "dkny-golden-delicious",
    "h1": "DKNY Golden Delicious Parfum Femme Algérie",
    "name": "Golden Delicious",
    "brand": "DKNY",
    "brandSlug": "dkny",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "EDP",
    "volume": "100ml",
    "price": 6900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/dkny-golden-delicious.jpg",
    "shortDescription": "DKNY Golden Delicious est une version plus luxueuse et florale du be Delicious original. Pétale de magnolia, jasmin et musc blanc dans un parfum solaire et raffiné.",
    "description": "DKNY Golden Delicious est né de l'idée de réinventer le succès du be Delicious original — cette pomme verte emblématique — dans une version plus florale, plus chaude et plus luxueuse. Lancé pour célébrer la vie new-yorkaise dans ce qu'elle a de plus glamour et ensoleillé, Golden Delicious est une fragrance florale-fruitée d'une belle sophistication.\n\nLa composition s'ouvre sur un accord pomme dorée riche et gourmand, accompagné d'une orange blanche juteuse. Le cœur est un bouquet floral lumineux : magnolia, jasmin et rose sauvage dans un accord d'une générosité solaire. La base de musc blanc, santal et ambre apporte chaleur et persistance dans un finish élégant et moderne.\n\nGolden Delicious est la proposition idéale pour les femmes qui aiment le be Delicious original mais souhaitent quelque chose de plus riche et plus persistant. Sa transition fluide entre la fraîcheur fruitée et la profondeur florale en fait un parfum polyvalent pour toutes saisons.\n\nMaison Numidia propose ce parfum DKNY authentique avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Pomme dorée", "Orange blanche", "Poire"],
      "heart": ["Magnolia", "Jasmin", "Rose sauvage"],
      "base": ["Musc blanc", "Bois de santal", "Ambre"]
    },
    "family": "Floral Fruité",
    "occasions": ["Bureau", "Journée", "Sorties"],
    "seasons": ["Printemps", "Été", "Automne"],
    "longevity": 3,
    "sillage": 3,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["dkny-be-delicious-femme", "marc-jacobs-daisy", "kate-spade-live-colorfully"]
  },
  {
    "id": "michael-kors-sexy-amber",
    "slug": "michael-kors-sexy-amber",
    "h1": "Michael Kors Sexy Amber Parfum Femme Algérie",
    "name": "Sexy Amber",
    "brand": "Michael Kors",
    "brandSlug": "michael-kors",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "EDP",
    "volume": "100ml",
    "price": 7900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/michael-kors-sexy-amber.jpg",
    "shortDescription": "Michael Kors Sexy Amber est un floral ambré sensuel et moderne. Mandarine, gardénia et ambre chaud dans une composition enveloppante et séduisante pour la femme de caractère.",
    "description": "Michael Kors Sexy Amber est une fragrance qui capture parfaitement l'esprit de la maison Michael Kors : glamour américain, sensualité moderne et élégance sans effort. Cette EDP est une invitation à la séduction assumée, portée par des matières nobles et une composition savamment équilibrée.\n\nLa composition s'ouvre sur un accord fruité chaud de mandarine et de kumquat, lumineux et immédiatement attrayant. Le cœur déploie un bouquet floral sensuel : gardénia crémeux, jasmin généreux et muguet délicat dans un accord floral-ambré qui est la véritable signature de cette fragrance. La base est enveloppante et chaude — ambre dorée, bois de santal, musc et une touche de vanille — donnant à Sexy Amber son caractère sensuel et persistant.\n\nCe parfum est idéal pour les femmes qui veulent un parfum qui projette confiance et féminité sans être agressif. Sa versatilité le rend pertinent aussi bien pour le bureau que pour les soirées d'affaires.\n\nDisponible chez Maison Numidia avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Mandarine", "Kumquat", "Bergamote"],
      "heart": ["Gardénia", "Jasmin", "Muguet"],
      "base": ["Ambre dorée", "Bois de santal", "Musc", "Vanille"]
    },
    "family": "Floral Ambré",
    "occasions": ["Bureau", "Soirée", "Dîner"],
    "seasons": ["Automne", "Hiver"],
    "longevity": 4,
    "sillage": 3,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["michael-kors-gold", "michael-kors-gorgeous", "ysl-black-opium"]
  },
  {
    "id": "michael-kors-gold",
    "slug": "michael-kors-gold",
    "h1": "Michael Kors Gold Parfum Femme Algérie",
    "name": "Gold",
    "brand": "Michael Kors",
    "brandSlug": "michael-kors",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "EDP",
    "volume": "100ml",
    "price": 8200,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/michael-kors-gold.jpg",
    "shortDescription": "Michael Kors Gold est un floral oriental luxueux et lumineux. Tiare, jasmin et santal dans une composition somptueuse et glamour pour la femme qui s'assume.",
    "description": "Michael Kors Gold est l'expression ultime du glamour californien selon Michael Kors. Ce parfum luxueux est conçu pour la femme qui n'a pas peur de briller — qui assume son élégance avec autant de naturel que de sophistication.\n\nLa fragrance s'ouvre sur un accord floral tropical immédiat : fleur de tiare, jasmin sambac et fleur d'oranger dans une composition florale d'une générosité rare qui évoque les plages de luxe et les palm trees californiens. Le cœur développe un accord boisé-ambré sophistiqué : bois de santal, ambre et patchouli léger qui apportent profondeur et chaleur. La base dorée de vanille crémeuse, musc blanc et cèdre donne à ce parfum sa signature luxueuse et persistante.\n\nMichael Kors Gold est le parfum des grandes occasions : soirées, galas, mariages et événements importants où l'on veut être à la hauteur de ses ambitions. Sa longévité et son sillage en font un investissement olfactif qui se justifie pleinement.\n\nMaison Numidia propose ce parfum Michael Kors authentique avec livraison COD dans toutes les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Fleur de tiare", "Jasmin sambac", "Fleur d'oranger"],
      "heart": ["Bois de santal", "Ambre", "Patchouli"],
      "base": ["Vanille crémeuse", "Musc blanc", "Cèdre"]
    },
    "family": "Floral Oriental",
    "occasions": ["Soirée", "Occasions spéciales", "Glamour"],
    "seasons": ["Automne", "Hiver"],
    "longevity": 5,
    "sillage": 4,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["michael-kors-sexy-amber", "michael-kors-gorgeous", "bvlgari-goldea"]
  },
  {
    "id": "jimmy-choo-man-blue",
    "slug": "jimmy-choo-man-blue",
    "h1": "Jimmy Choo Man Blue Parfum Homme Algérie",
    "name": "Man Blue",
    "brand": "Jimmy Choo",
    "brandSlug": "jimmy-choo",
    "category": "parfums-homme",
    "gender": "homme",
    "concentration": "EDT",
    "volume": "100ml",
    "price": 7200,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/jimmy-choo-man-blue.jpg",
    "shortDescription": "Jimmy Choo Man Blue est un aquatique boisé frais et dynamique. Mandarine, cardamome et vétiver pour un homme actif et contemporain qui aime les parfums clairs et propres.",
    "description": "Jimmy Choo Man Blue est la déclinaison aquatique de la ligne Man de la maison londonienne Jimmy Choo. Inspiré de la mer, du ciel bleu et des espaces ouverts, ce parfum incarne l'énergie de l'homme moderne qui aime les grands espaces sans pour autant renoncer à la sophistication urbaine.\n\nLa composition s'ouvre sur une envolée d'agrumes et de cardamome verte qui donne immédiatement un caractère frais et piquant. Le cœur développe un accord aquatique-boisé : vétiver marin, cèdre bleu et gingembre dans une alliance qui évoque les vents marins et les côtes méditerranéennes. La base légère de musc blanc, ambre et iris donne à ce parfum sa tenue discrète et son élégance moderne.\n\nMan Blue est le parfum idéal pour les journées actives et les temps chauds. Sa fraîcheur persistante et son caractère non envahissant en font un excellent choix pour le bureau, le sport et les sorties décontractées.\n\nDisponible chez Maison Numidia avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Mandarine", "Citron vert", "Cardamome verte"],
      "heart": ["Vétiver marin", "Cèdre bleu", "Gingembre"],
      "base": ["Musc blanc", "Ambre", "Iris"]
    },
    "family": "Aquatique Boisé",
    "occasions": ["Bureau", "Sport", "Journée"],
    "seasons": ["Printemps", "Été"],
    "longevity": 3,
    "sillage": 3,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["jimmy-choo-man", "versace-dylan-turquoise", "invictus-aqua-paco-rabanne"]
  },
  {
    "id": "jimmy-choo-blossom",
    "slug": "jimmy-choo-blossom",
    "h1": "Jimmy Choo Blossom Parfum Femme Algérie",
    "name": "Blossom",
    "brand": "Jimmy Choo",
    "brandSlug": "jimmy-choo",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "EDT",
    "volume": "100ml",
    "price": 7200,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/jimmy-choo-blossom.jpg",
    "shortDescription": "Jimmy Choo Blossom est un floral fruité lumineux et élégant. Fraise, pivoine et gardénia dans une composition fraîche et féminine idéale pour le printemps.",
    "description": "Jimmy Choo Blossom est une fragrance féminine qui capture l'essence de la féminité dans ce qu'elle a de plus lumineux et de plus joyeux. Inspiré par un jardin en fleurs au lever du soleil, ce parfum est une explosion de fraîcheur et d'élégance florale qui porte la signature glamour de la maison londonienne.\n\nLa composition s'ouvre sur un accord fruité généreux de fraise des bois, de citron rose et de bergamote qui apporte une vivacité immédiate. Le cœur floral est le joyau de Blossom : pivoine fraîche, gardénia crémeux et magnolia dans un bouquet d'une beauté délicate. La base légère de bois de cèdre, musc blanc et ambre préserve la légèreté de la composition tout en lui donnant une tenue agréable.\n\nBlossom est le parfum printanier par excellence, idéal pour les femmes qui aiment les fragrances florales légères et bien construites. Son sillage discret en fait un choix pertinent pour le bureau et les situations où l'on souhaite sentir bon sans imposer sa présence.\n\nMaison Numidia propose ce parfum Jimmy Choo authentique avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Fraise des bois", "Citron rose", "Bergamote"],
      "heart": ["Pivoine", "Gardénia", "Magnolia"],
      "base": ["Cèdre", "Musc blanc", "Ambre"]
    },
    "family": "Floral Fruité",
    "occasions": ["Bureau", "Journée", "Printemps"],
    "seasons": ["Printemps", "Été"],
    "longevity": 3,
    "sillage": 3,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["jimmy-choo-femme", "jimmy-choo-floral", "marc-jacobs-daisy"]
  },
  {
    "id": "mariah-carey-forever",
    "slug": "mariah-carey-forever",
    "h1": "Mariah Carey Forever Parfum Femme Algérie",
    "name": "Forever",
    "brand": "Mariah Carey",
    "brandSlug": "mariah-carey",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "EDP",
    "volume": "100ml",
    "price": 3500,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/mariah-carey-forever.jpg",
    "shortDescription": "Mariah Carey Forever est un floral fruité romantique et envoûtant. Framboise, jasmin et musc dans une composition douce et moderne signée de la grande diva mondiale.",
    "description": "Mariah Carey Forever est la fragrance romantique de la grande diva américaine, star aux cinq octaves et aux ventes de disques record. Ce parfum capture l'essence du style musical de Mariah Carey : émotions intenses, féminité assumée et romantisme intemporel.\n\nLa composition s'ouvre sur une envolée fruitée de framboise et de litchi, pétillante et immédiatement séduisante. Le cœur floral déploie un accord de jasmin, de muguet et de magnolia dans une générosité florale qui rappelle les grandes ballades romantiques de l'artiste. La base douce de musc blanc, ambre et vanille légère crée un sillage enveloppant et chaleureux qui persiste agréablement.\n\nForever est le parfum de la femme romantique qui croit aux grandes émotions et aux moments magiques. Sa douceur et son accessibilité en font un excellent cadeau, aussi bien pour une première fragrance que pour enrichir une collection.\n\nMaison Numidia propose ce parfum authentique avec livraison COD dans toutes les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Framboise", "Litchi", "Poire"],
      "heart": ["Jasmin", "Muguet", "Magnolia"],
      "base": ["Musc blanc", "Ambre", "Vanille légère"]
    },
    "family": "Floral Fruité",
    "occasions": ["Journée", "Casual", "Week-end"],
    "seasons": ["Printemps", "Été"],
    "longevity": 3,
    "sillage": 2,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["britney-spears-fantasy", "beyonce-heat", "jennifer-lopez-glow"]
  },
  {
    "id": "viktor-rolf-bon-bon",
    "slug": "viktor-rolf-bon-bon",
    "h1": "Viktor Rolf Bon Bon Parfum Femme Algérie",
    "name": "Bon Bon",
    "brand": "Viktor & Rolf",
    "brandSlug": "viktor-rolf",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "EDP",
    "volume": "100ml",
    "price": 9200,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/viktor-rolf-bon-bon.jpg",
    "shortDescription": "Viktor & Rolf Bon Bon est un gourmand floral luxueux et enveloppant. Caramel, pêche et bois de santal dans un parfum irrésistiblement doux pour la femme qui s'offre des plaisirs.",
    "description": "Viktor & Rolf Bon Bon est une déclaration d'amour au plaisir sans complexe. La maison hollandaise Viktor & Rolf, connue pour ses créations mode conceptuelles et audacieuses, a transposé sa philosophie dans un parfum gourmand floral qui refuse toute retenue.\n\nLe flacon de Bon Bon est déjà une déclaration : un sac à main en résine rose bonbon avec une chaine dorée, transportable comme un accessoire précieux. Ce flacon est devenu l'un des objets de parfumerie les plus collectionnés et photographiés de la dernière décennie.\n\nLa composition est un chef-d'oeuvre de parfumerie gourmande. L'ouverture est une explosion fruitée de pêche, mandarine et mandarine de Sicile dans un accord juteux et pétillant. Le cœur révèle la touche signature de la maison : caramel doux, bois de santal et un accord pivoine-jasmin qui fond littéralement sur la peau. La base est généreuse et persistante — vanille soyeuse, bois de cèdre et musc — un accord qui accompagne comme un nuage agréable des heures durant.\n\nBon Bon est la fragrance de celles qui ne se privent pas. Disponible chez Maison Numidia avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Pêche", "Mandarine", "Framboise"],
      "heart": ["Caramel", "Pivoine", "Jasmin"],
      "base": ["Bois de santal", "Vanille", "Musc"]
    },
    "family": "Gourmand Floral",
    "occasions": ["Soirée", "Week-end", "Sorties"],
    "seasons": ["Automne", "Hiver"],
    "longevity": 5,
    "sillage": 4,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["viktor-rolf-flowerbomb", "britney-spears-fantasy", "ysl-black-opium"]
  },
  {
    "id": "ysl-libre-le-parfum",
    "slug": "ysl-libre-le-parfum",
    "h1": "YSL Libre Le Parfum Femme Algérie",
    "name": "Libre Le Parfum",
    "brand": "Yves Saint Laurent",
    "brandSlug": "ysl",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "Parfum",
    "volume": "90ml",
    "price": 14900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/ysl-libre-le-parfum.jpg",
    "shortDescription": "YSL Libre Le Parfum est la version la plus intense de la fragrance iconique. Lavande marocaine, fleur d'oranger et vanille Bourbon dans sa forme absolue, pour la femme libre et indomptable.",
    "description": "YSL Libre Le Parfum est le sommet de la pyramide Libre — la version la plus concentrée et la plus intense de cette fragrance iconique lancée en 2019. Là où l'EDP interprète la liberté avec légèreté, le Parfum la revendique avec force et conviction dans une formulation qui pousse chaque note à son maximum.\n\nLa lavande marocaine, signature universellement reconnue de Libre, est ici présente dans toute sa générosité aromatique. Elle s'ouvre puissante et immédiate, enveloppant les sens d'une fraîcheur herbeuse et légèrement mentholée. Le cœur déploie un accord fleur d'oranger-mandarine d'une intensité solaire qui apporte chaleur et luminosité au parfum. La base vanille Bourbon — note phare de toute la ligne Libre — est ici plus profonde, plus crémeuse et plus persistante que dans toutes les déclinaisons précédentes.\n\nLibre Le Parfum est pour les femmes qui veulent la version ultime de leur fragrance. Sa longévité peut atteindre douze heures ou plus, et son sillage s'installe dans une pièce comme une présence affirmée et inoubliable.\n\nDisponible chez Maison Numidia avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Lavande marocaine", "Mandarine", "Bergamote"],
      "heart": ["Fleur d'oranger", "Jasmin", "Lavande absolue"],
      "base": ["Vanille Bourbon", "Cèdre", "Musc ambré"]
    },
    "family": "Floral Aromatique",
    "occasions": ["Soirée", "Occasions spéciales", "Hiver"],
    "seasons": ["Automne", "Hiver"],
    "longevity": 5,
    "sillage": 5,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["ysl-libre-intense", "ysl-black-opium", "dior-miss-dior-parfum"]
  },
  {
    "id": "marc-jacobs-daisy-wild",
    "slug": "marc-jacobs-daisy-wild",
    "h1": "Marc Jacobs Daisy Wild Parfum Femme Algérie",
    "name": "Daisy Wild",
    "brand": "Marc Jacobs",
    "brandSlug": "marc-jacobs",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "EDP",
    "volume": "100ml",
    "price": 8900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/marc-jacobs-daisy-wild.jpg",
    "shortDescription": "Marc Jacobs Daisy Wild est la dernière né de la famille Daisy, lancée en 2024. Figuier, jasmin sauvage et bois de santal dans une composition florale boisée naturelle et libre.",
    "description": "Marc Jacobs Daisy Wild est le chapitre le plus récent de la saga Daisy — une famille de parfums qui a su se renouveler depuis son lancement en 2007 tout en maintenant l'esprit naturel et joyeux qui la caractérise. Lancé en 2024, Daisy Wild prend une direction plus boisée et plus naturelle, comme si la petite marguerite avait quitté les jardins pour rejoindre la forêt.\n\nLa composition s'ouvre sur une fraîcheur herbacée et végétale de feuilles de figuier et de mousse verte qui évoque immédiatement un sous-bois après la pluie. Le cœur est un bouquet floral sauvage : jasmin blanc en plein air, pivoine légère et une petite fleur indéfinissable qui évoque les fleurs des champs. La base est chaleureuse et naturelle — bois de santal, patchouli léger et musc ambré — qui ancre Daisy Wild dans une profondeur boisée inédite pour la famille.\n\nDaisy Wild est pour les femmes qui aiment la nature et qui recherchent un parfum qui sent vrai, frais et naturellement beau. Disponible chez Maison Numidia avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Figuier", "Feuilles vertes", "Bergamote"],
      "heart": ["Jasmin blanc", "Pivoine", "Fleurs sauvages"],
      "base": ["Bois de santal", "Patchouli", "Musc ambré"]
    },
    "family": "Floral Boisé",
    "occasions": ["Bureau", "Journée", "Nature"],
    "seasons": ["Printemps", "Été", "Automne"],
    "longevity": 4,
    "sillage": 3,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["marc-jacobs-daisy", "marc-jacobs-daisy-eau-so-fresh", "anna-sui-dolly-girl"]
  }
];

const allSlugs = new Set([...existingSlugs, ...newProducts.map(p => p.slug)]);
let errors = 0;
for (const p of newProducts) {
  if (existingSlugs.has(p.slug)) { console.error(`DUPLICATE: ${p.slug}`); errors++; }
  for (const r of p.related) {
    if (!allSlugs.has(r)) { console.error(`MISSING related "${r}" in ${p.slug}`); errors++; }
  }
}
if (errors > 0) { console.error(`${errors} erreur(s) — abandon`); process.exit(1); }

data.products.push(...newProducts);
writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf8');
console.log(`✅ ${newProducts.length} produits ajoutés — total: ${data.products.length} produits`);
