import { readFileSync, writeFileSync } from 'fs';

const filePath = 'data/products.json';
const data = JSON.parse(readFileSync(filePath, 'utf8'));
const existingSlugs = new Set(data.products.map(p => p.slug));

const newProducts = [
  {
    "id": "chanel-chance-eau-vive",
    "slug": "chanel-chance-eau-vive",
    "h1": "Chanel Chance Eau Vive Parfum Femme Algérie",
    "name": "Chance Eau Vive",
    "brand": "Chanel",
    "brandSlug": "chanel",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "EDT",
    "volume": "100ml",
    "price": 12900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/chanel-chance-eau-vive.jpg",
    "shortDescription": "Chanel Chance Eau Vive est la version la plus pétillante de la famille Chance. Grapefruit, jasmin et vétiver dans une composition fraîche et lumineuse pour la femme d'aujourd'hui.",
    "description": "Chanel Chance Eau Vive est la déclinaison la plus fraîche et la plus pétillante de la famille Chance, lancée par Chanel pour capturer l'énergie et la vivacité de la femme moderne. Là où Chance joue sur le chypré fleuri et Eau Fraîche sur la fraîcheur verte, Eau Vive assume un caractère citrus-fleuri lumineux et immédiatement attrayant.\n\nLa composition s'ouvre sur une explosion de grapefruit sicilien — note phare et signature d'Eau Vive — accompagnée d'une mandarine italienne et d'un citrus blanc vif. Le cœur déploie un jasmin délicat et une touche d'iris dans un accord fleuri qui tempère la vivacité des agrumes. La base légère de vétiver blanc et musc assure une tenue discrète qui préserve la légèreté de l'ensemble.\n\nEau Vive est le Chance des journées actives et ensoleillées. Sa fraîcheur immédiate et son énergie pétillante en font le compagnon idéal des journées chaudes algériennes et des situations où l'on cherche un parfum vivifiant et plaisant.\n\nMaison Numidia propose ce parfum Chanel authentique avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Grapefruit sicilien", "Mandarine italienne", "Citrus blanc"],
      "heart": ["Jasmin", "Iris", "Alcool florale"],
      "base": ["Vétiver blanc", "Musc", "Ambre léger"]
    },
    "family": "Floral Citrus",
    "occasions": ["Bureau", "Journée", "Été"],
    "seasons": ["Printemps", "Été"],
    "longevity": 3,
    "sillage": 3,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["chanel-chance", "chanel-chance-eau-tendre", "chanel-chance-eau-fraiche"]
  },
  {
    "id": "chanel-coco-mademoiselle-intense",
    "slug": "chanel-coco-mademoiselle-intense",
    "h1": "Chanel Coco Mademoiselle Intense Parfum Femme Algérie",
    "name": "Coco Mademoiselle Intense",
    "brand": "Chanel",
    "brandSlug": "chanel",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "EDP Intense",
    "volume": "100ml",
    "price": 15500,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/chanel-coco-mademoiselle-intense.jpg",
    "shortDescription": "Chanel Coco Mademoiselle Intense est la version la plus dense et la plus sensuelle du classique Chanel. Rose, vétiver et patchouli dans une intensité chypré absolue pour femme de caractère.",
    "description": "Chanel Coco Mademoiselle Intense est l'expression absolue du Coco Mademoiselle — ce classique contemporain de Chanel qui a conquis des générations de femmes depuis 2001. Là où le Coco Mademoiselle original joue sur la légèreté et l'accessibilité, l'Intense assume une profondeur et une densité qui le transforment en parfum de soirée et d'occasions exceptionnelles.\n\nLa formulation Intense amplifie chaque note du classique. L'accord de tête orange-bergamote est plus généreux et plus persistant. Le cœur de rose centifolia-jasmin est traité avec une générosité supplémentaire, révélant des aspects plus chauds et plus sensuels de ces fleurs précieuses. Mais c'est au niveau du fond que Intense se distingue vraiment : le vétiver haïtien, plus intense, et le patchouli, plus présent, créent un accord chypré d'une profondeur et d'une complexité qui peuvent se maintenir pendant plus de douze heures.\n\nCoco Mademoiselle Intense est pour les femmes qui ne veulent pas passer inaperçues. Son sillage enveloppant et sa longévité remarquable en font un investissement olfactif de premier choix pour les occasions importantes.\n\nDisponible chez Maison Numidia avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Orange", "Bergamote", "Mandarine"],
      "heart": ["Rose centifolia", "Jasmin de Grasse", "Ylang-ylang"],
      "base": ["Vétiver haïtien intense", "Patchouli", "Musc blanc"]
    },
    "family": "Floral Chypré",
    "occasions": ["Soirée", "Occasions spéciales", "Hiver"],
    "seasons": ["Automne", "Hiver"],
    "longevity": 5,
    "sillage": 5,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["coco-mademoiselle-chanel", "chanel-coco", "allure-femme-chanel"]
  },
  {
    "id": "chanel-n5-parfum",
    "slug": "chanel-n5-parfum",
    "h1": "Chanel N5 Parfum Extrait Femme Algérie",
    "name": "N°5 Parfum",
    "brand": "Chanel",
    "brandSlug": "chanel",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "Parfum",
    "volume": "35ml",
    "price": 17500,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/chanel-n5-parfum.jpg",
    "shortDescription": "Le N°5 Parfum de Chanel est l'extrait de parfum le plus concentré de l'icône absolue. Rose Grasse et jasmin de Grasse dans leur expression maximale pour l'expérience olfactive ultime.",
    "description": "Le Chanel N°5 Parfum est l'expression la plus concentrée et la plus précieuse du parfum le plus célèbre au monde. Créé en 1921 par Ernest Beaux pour Coco Chanel, le N°5 a révolutionné la parfumerie et reste un siècle plus tard une référence absolue qui transcende les modes et les générations.\n\nLe Parfum — ou Extrait de Parfum — est la forme la plus concentrée du N°5, avec une teneur en matières odorantes qui peut atteindre 20 à 30%. Cette concentration permet à la fragrance de se révéler progressivement sur la peau pendant des heures, voire des jours, dévoilant des facettes de la composition que les versions moins concentrées ne peuvent révéler.\n\nLa signature du N°5 Parfum est un accord floral aldéhydé d'une complexité et d'une beauté intemporelles. Les aldéhydes donnent à l'ouverture sa luminosité caractéristique et légèrement poudré. Le cœur est un bouquet floral somptueux de rose de Grasse et jasmin de Grasse — deux fleurs rares dont la qualité est directement liée aux fermes partenaires de Chanel en Provence. La base de bois de santal, vétiver et musc est d'une profondeur et d'une persistance absolues.\n\nMaison Numidia propose cet extrait de parfum Chanel authentique avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Aldéhydes", "Bergamote", "Ylang-ylang"],
      "heart": ["Rose de Grasse", "Jasmin de Grasse", "Iris"],
      "base": ["Bois de santal", "Vétiver", "Musc de civette", "Ambre"]
    },
    "family": "Floral Aldéhydé",
    "occasions": ["Soirée", "Occasions spéciales", "Luxe absolu"],
    "seasons": ["Automne", "Hiver", "Printemps"],
    "longevity": 5,
    "sillage": 4,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["chanel-no5", "chanel-n5-eau-premiere", "allure-femme-chanel"]
  },
  {
    "id": "dior-sauvage-parfum",
    "slug": "dior-sauvage-parfum",
    "h1": "Dior Sauvage Parfum Homme Algérie",
    "name": "Sauvage Parfum",
    "brand": "Dior",
    "brandSlug": "dior",
    "category": "parfums-homme",
    "gender": "homme",
    "concentration": "Parfum",
    "volume": "100ml",
    "price": 17500,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/dior-sauvage-parfum.jpg",
    "shortDescription": "Dior Sauvage Parfum est la concentration maximale de l'iconique Sauvage. Bergamote, lavande et santal dans leur expression la plus intense et la plus persistante.",
    "description": "Dior Sauvage Parfum représente le sommet de la pyramide Sauvage — la concentration la plus élevée et la plus noble de l'un des parfums masculins les plus vendus au monde. Là où l'EDT est léger et frais, l'EDP plus profond, et l'Elixir ultra-concentré et sec, le Parfum propose une interprétation unique qui amplifie les notes boisées et lavandées dans leur forme la plus aboutie.\n\nLa composition du Parfum redéfinit Sauvage avec une ouverture poivrée et bergamotée encore plus intense, accompagnée d'une lavande plus profonde et plus aromatique que dans toutes les versions précédentes. Le cœur développe un accord boisé épicé de géranium, poivre de Sichuan et vétiver dans une richesse équilibrée. La base est un nid de bois de santal, ambre et cèdre d'une persistance qui peut atteindre quatorze heures ou plus.\n\nSauvage Parfum est pour l'homme qui connaît et aime Sauvage, et qui veut en découvrir la facette la plus profonde et la plus mémorable. Un chef-d'oeuvre de concentration.\n\nMaison Numidia propose ce parfum Dior authentique avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Bergamote", "Poivre de Sichuan", "Cardamome"],
      "heart": ["Lavande profonde", "Géranium", "Vétiver"],
      "base": ["Bois de santal", "Ambre", "Cèdre", "Encens"]
    },
    "family": "Boisé Aromatique",
    "occasions": ["Soirée", "Occasions spéciales", "Hiver"],
    "seasons": ["Automne", "Hiver"],
    "longevity": 5,
    "sillage": 5,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["dior-sauvage", "dior-sauvage-elixir", "bleu-de-chanel-parfum"]
  },
  {
    "id": "givenchy-irresistible-eau-fraiche",
    "slug": "givenchy-irresistible-eau-fraiche",
    "h1": "Givenchy Irresistible Eau Fraîche Parfum Femme Algérie",
    "name": "Irresistible Eau Fraîche",
    "brand": "Givenchy",
    "brandSlug": "givenchy",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "EDT",
    "volume": "80ml",
    "price": 9500,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/givenchy-irresistible-eau-fraiche.jpg",
    "shortDescription": "Givenchy Irresistible Eau Fraîche est la version la plus légère et la plus vivifiante de l'Irresistible. Rose fraîche, vétiver et musc blanc dans une composition aérienne et lumineuse.",
    "description": "Givenchy Irresistible Eau Fraîche est la déclinaison la plus fraîche et la plus légère de l'Irresistible — le grand succès féminin de Givenchy lancé en 2021. Cette version Eau Fraîche amplifie la légèreté et la vivacité de l'original en lui donnant un caractère encore plus aérien et frais, idéal pour les journées chaudes et les situations où l'on veut un parfum discret et naturel.\n\nLa composition s'ouvre sur une fraîcheur de rose eau et de cèdre lumineux qui captent l'attention sans jamais s'imposer. Le cœur est la rose de Damas dans sa version la plus fraîche et la plus naturelle, accompagnée d'une touche de pivoine. La base légère de vétiver blanc et de musc transparent assure une persistance satisfaisante tout en préservant la légèreté caractéristique d'une eau fraîche.\n\nIrresistible Eau Fraîche convient parfaitement aux journées actives et aux situations professionnelles. Sa légèreté en fait un parfum que l'on peut porter sans retenue dans n'importe quel contexte.\n\nDisponible chez Maison Numidia avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Rose eau", "Cèdre lumineux", "Bergamote"],
      "heart": ["Rose de Damas fraîche", "Pivoine", "Muguet"],
      "base": ["Vétiver blanc", "Musc transparent", "Ambre léger"]
    },
    "family": "Floral",
    "occasions": ["Bureau", "Journée", "Été"],
    "seasons": ["Printemps", "Été"],
    "longevity": 2,
    "sillage": 2,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["givenchy-irresistible", "givenchy-l-interdit", "givenchy-live-irresistible"]
  },
  {
    "id": "paco-rabanne-phantom-parfum",
    "slug": "paco-rabanne-phantom-parfum",
    "h1": "Paco Rabanne Phantom Parfum Homme Algérie",
    "name": "Phantom Parfum",
    "brand": "Paco Rabanne",
    "brandSlug": "paco-rabanne",
    "category": "parfums-homme",
    "gender": "homme",
    "concentration": "Parfum",
    "volume": "100ml",
    "price": 11500,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/paco-rabanne-phantom-parfum.jpg",
    "shortDescription": "Paco Rabanne Phantom Parfum est la version la plus concentrée du robot iconique. Lavande, vétiver et vanille dans une intensité robotique absolue pour l'homme du futur.",
    "description": "Paco Rabanne Phantom Parfum est la version la plus concentrée et la plus intense du Phantom — ce parfum au flacon robot qui a marqué la parfumerie masculine depuis son lancement en 2021. Là où le Phantom EDT propose fraîcheur et légèreté, le Parfum assume une densité et une présence qui en font un parfum de soirée et d'occasions importantes.\n\nLa concentration Parfum amplifie chaque note du Phantom original. La lavande française est ici plus riche, plus aromatique et plus profonde. Le cœdre de Virginie apporte une dimension boisée plus prononcée. La vanille de Madagascar est plus généreuse et plus créameuse. L'ensemble crée un accord lavande-boisé-vanillé d'une intensité et d'une persistance remarquables.\n\nPhantom Parfum est pour l'homme qui connaît le Phantom et qui souhaite en découvrir la version définitive — plus longue, plus présente, plus mémorable. Son sillage enveloppant et sa longévité peuvent atteindre quatorze heures sur les peaux chaudes.\n\nMaison Numidia propose ce parfum Paco Rabanne authentique avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Lavande française profonde", "Citron", "Bergamote"],
      "heart": ["Vétiver", "Cèdre de Virginie", "Gingembre"],
      "base": ["Vanille de Madagascar intense", "Musc ambré", "Tonka"]
    },
    "family": "Boisé Aromatique",
    "occasions": ["Soirée", "Occasions importantes", "Hiver"],
    "seasons": ["Automne", "Hiver"],
    "longevity": 5,
    "sillage": 5,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["phantom-paco-rabanne", "paco-rabanne-invictus-parfum", "invictus-paco-rabanne"]
  },
  {
    "id": "armani-code-parfum",
    "slug": "armani-code-parfum",
    "h1": "Armani Code Parfum Homme Algérie",
    "name": "Code Parfum",
    "brand": "Giorgio Armani",
    "brandSlug": "armani",
    "category": "parfums-homme",
    "gender": "homme",
    "concentration": "Parfum",
    "volume": "75ml",
    "price": 13500,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/armani-code-parfum.jpg",
    "shortDescription": "Armani Code Parfum est la version la plus concentrée et la plus séduisante du Code. Bergamote noire, lavande et tonka dans un accord oriental boisé de la plus haute intensité.",
    "description": "Armani Code Parfum est le sommet de la collection Code — la fragrance masculine iconique de Giorgio Armani qui séduit depuis 2004. Cette version Parfum prend le DNA caractéristique du Code — bergamote, guaïac, accord séduisant — et le pousse à son expression la plus intense et la plus raffinée.\n\nLa composition Parfum amplifie la bergamote sicilienne en la rendant plus sombre, plus profonde et plus boisée. Le cœur développe un accord lavande-guaïac qui est la signature olfactive reconnaissable du Code, ici présentée dans sa forme la plus noble. La base de fève tonka, ambre et bois précieux est plus généreuse et plus persistante, créant un accord chaud et séduisant qui peut accompagner une soirée entière.\n\nCode Parfum est fait pour l'homme qui sait ce qu'il veut et qui ne cherche pas à passer inaperçu. Sa densité olfactive en fait un parfum de caractère que l'on mémorise immédiatement.\n\nDisponible chez Maison Numidia avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Bergamote sicilienne noire", "Mandarine", "Bergamote glacée"],
      "heart": ["Lavande", "Guaïac", "Bois de santal"],
      "base": ["Fève tonka", "Ambre", "Musc boisé"]
    },
    "family": "Oriental Boisé",
    "occasions": ["Soirée", "Dîner d'affaires", "Hiver"],
    "seasons": ["Automne", "Hiver"],
    "longevity": 5,
    "sillage": 5,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["armani-code", "armani-code-profumo", "armani-code-absolu"]
  },
  {
    "id": "tom-ford-lost-cherry",
    "slug": "tom-ford-lost-cherry",
    "h1": "Tom Ford Lost Cherry Parfum Algérie",
    "name": "Lost Cherry",
    "brand": "Tom Ford",
    "brandSlug": "tom-ford",
    "category": "parfums-femme",
    "gender": "unisexe",
    "concentration": "EDP",
    "volume": "50ml",
    "price": 17900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/tom-ford-lost-cherry.jpg",
    "shortDescription": "Tom Ford Lost Cherry est un oriental gourmand audacieux et sensuel. Cerise noire, amande amère et bois de santal dans une composition addictive de la Private Blend Tom Ford.",
    "description": "Tom Ford Lost Cherry est l'une des créations les plus séduisantes et les plus discutées de la Private Blend de Tom Ford. Lancé en 2019, ce parfum unisexe a rapidement acquis un statut culte grâce à sa composition audacieuse — une cerise noire somptueuse, légèrement enivrante, posée sur un fond de liqueur d'amaretto et de bois sombres.\n\nLa fragrance s'ouvre sur un accord cerise noire intense — juteux, légèrement alcoolisé, comme une cerise à l'eau-de-vie — accompagné d'une amande amère et d'un soupçon de rose sauvage. Le cœur développe un accord cherry liqueur d'une sensualité troublante : cerise macérée dans du kirsch, accompagnée de bois de thé et de cannelle. La base est sombre et enveloppante — bois de santal, oud léger, benjoin et musc sombre — dans un accord oriental profond et persistant.\n\nLost Cherry est pour ceux qui cherchent un parfum original, mémorable et légèrement transgressif. Sa popularité en fait l'une des fragrances les plus demandées de la Private Blend.\n\nMaison Numidia propose ce parfum Tom Ford authentique avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Cerise noire", "Amande amère", "Rose sauvage"],
      "heart": ["Cherry liqueur", "Bois de thé", "Cannelle"],
      "base": ["Bois de santal", "Oud léger", "Benjoin", "Musc sombre"]
    },
    "family": "Oriental Gourmand",
    "occasions": ["Soirée", "Hiver", "Occasions spéciales"],
    "seasons": ["Automne", "Hiver"],
    "longevity": 5,
    "sillage": 4,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["tom-ford-black-orchid", "tom-ford-oud-wood", "baccarat-rouge-540"]
  },
  {
    "id": "jean-paul-gaultier-scandal-absolu",
    "slug": "jean-paul-gaultier-scandal-absolu",
    "h1": "Jean Paul Gaultier Scandal Absolu Parfum Femme Algérie",
    "name": "Scandal Absolu",
    "brand": "Jean Paul Gaultier",
    "brandSlug": "jean-paul-gaultier",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "Parfum",
    "volume": "80ml",
    "price": 12900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/jean-paul-gaultier-scandal-absolu.jpg",
    "shortDescription": "Jean Paul Gaultier Scandal Absolu est la version la plus intense du Scandal. Miel, vétiver et fleur d'oranger dans un parfum concentré et addictif pour la femme scandaleuse.",
    "description": "Jean Paul Gaultier Scandal Absolu est l'expression maximale du Scandal — ce parfum féminin qui a fait scandale depuis son lancement en 2017. Absolu est la version Parfum — la plus concentrée — qui amplifie chaque aspect du Scandal original dans une formulation plus riche, plus intense et plus persistante.\n\nL'ouverture Absolu est immédiate et saisissante : un accord miel-fleur d'oranger généreux et chaud qui enveloppe les sens dès les premières secondes. Le cœur développe un accord fleur d'oranger absolue exceptionnellement généreux — cette fleur précieuse est ici utilisée dans sa forme absolue, plus riche et plus concentrée que dans le Scandal original. Le miel et le vétiver ancrent la composition dans une profondeur orientale-chyprée remarquable. La base est un accord ambré-musqué de longue durée.\n\nScandal Absolu est fait pour les femmes qui considèrent le Scandal comme leur parfum signature et qui veulent en découvrir la dimension ultime — plus présente, plus intense, plus mémorable.\n\nDisponible chez Maison Numidia avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Miel", "Fleur d'oranger", "Bergamote"],
      "heart": ["Fleur d'oranger absolue", "Vétiver intense", "Jasmin"],
      "base": ["Ambre", "Musc chaud", "Patchouli"]
    },
    "family": "Oriental Floral",
    "occasions": ["Soirée", "Occasions spéciales", "Hiver"],
    "seasons": ["Automne", "Hiver"],
    "longevity": 5,
    "sillage": 5,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["scandal-jean-paul-gaultier", "jean-paul-gaultier-classique", "ysl-black-opium"]
  },
  {
    "id": "guerlain-l-homme-ideal-extreme",
    "slug": "guerlain-l-homme-ideal-extreme",
    "h1": "Guerlain L Homme Ideal Extrême Parfum Homme Algérie",
    "name": "L'Homme Idéal Extrême",
    "brand": "Guerlain",
    "brandSlug": "guerlain",
    "category": "parfums-homme",
    "gender": "homme",
    "concentration": "EDP",
    "volume": "100ml",
    "price": 11500,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/guerlain-l-homme-ideal-extreme.jpg",
    "shortDescription": "Guerlain L'Homme Idéal Extrême est la version la plus intense de la fragrance masculine iconique. Citrus, bergamote et tonka dans une intensité orientale-boisée absolue.",
    "description": "Guerlain L'Homme Idéal Extrême est l'interprétation la plus profonde et la plus ambitieuse de L'Homme Idéal — la fragrance masculine qui a redéfini le style de Guerlain pour les hommes contemporains. Là où L'Homme Idéal original joue sur la légèreté et la fraîcheur, Extrême assume une intensité et une présence qui en font un parfum pour les occasions où l'on veut se démarquer.\n\nLa formulation Extrême reprend les grandes lignes de L'Homme Idéal — citrus, amande, bois — et les amplifie dans chaque dimension. La bergamote est plus intense, la mandarine plus généreuse. Le cœur développe un accord amande-bois-tonka plus riche et plus profond que dans l'original. La base de fève tonka, de bois précieux et de musc ambré est enveloppante et d'une persistance remarquable.\n\nL'Homme Idéal Extrême est pour l'homme qui connaît et aime l'original, et qui cherche une version plus affirmée pour ses soirées importantes. Sa composition soignée et sa signature Guerlain en font un choix de connaisseur.\n\nMaison Numidia propose ce parfum Guerlain authentique avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Bergamote intense", "Mandarine", "Citrus doux"],
      "heart": ["Amande tonka", "Lavande", "Cèdre"],
      "base": ["Fève tonka", "Bois précieux", "Musc ambré"]
    },
    "family": "Oriental Boisé",
    "occasions": ["Soirée", "Bureau", "Hiver"],
    "seasons": ["Automne", "Hiver"],
    "longevity": 5,
    "sillage": 4,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["l-homme-ideal-guerlain", "guerlain-habit-rouge", "mont-blanc-legend-edp"]
  },
  {
    "id": "issey-miyake-l-eau-d-issey-ambre",
    "slug": "issey-miyake-l-eau-d-issey-ambre",
    "h1": "Issey Miyake L Eau d Issey Ambre Parfum Femme Algérie",
    "name": "L'Eau d'Issey Ambre",
    "brand": "Issey Miyake",
    "brandSlug": "issey-miyake",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "EDP",
    "volume": "90ml",
    "price": 9900,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/issey-miyake-l-eau-d-issey-ambre.jpg",
    "shortDescription": "Issey Miyake L'Eau d'Issey Ambre est la version chaude et enveloppante de la fragrance iconique. Lotus blanc, vétiver et ambre dans un accord aquatique ambré d'une douceur inattendue.",
    "description": "Issey Miyake L'Eau d'Issey Ambre est une réinterprétation chaleureuse de l'iconique L'Eau d'Issey féminin. Là où l'original est d'une légèreté aquatique cristalline, Ambre prend le même ADN — fleurs blanches, eau — et y ajoute une couche de chaleur et de profondeur qui le rend plus apte aux saisons fraîches.\n\nLa composition s'ouvre sur une fraîcheur lumineuse de néroli et de yuzu qui maintient la légèreté caractéristique d'Issey Miyake. Le cœur déploie un lotus blanc et un jasmin plus généreux que dans l'original, accompagnés d'une touche florale créameuse. La base est là où Ambre diverge de l'original : un accord vétiver-ambre gris chaud et enveloppant qui donne à cette version toute sa singularité et son caractère automnal.\n\nL'Eau d'Issey Ambre convient aux fans de l'original qui cherchent une alternative plus chaude pour les mois froids, ou aux nouveaux venus qui apprécient les fragrances florales-ambrées légères.\n\nDisponible chez Maison Numidia avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Néroli", "Yuzu", "Bergamote"],
      "heart": ["Lotus blanc", "Jasmin", "Pivoine"],
      "base": ["Vétiver", "Ambre gris", "Musc chaud"]
    },
    "family": "Floral Ambré",
    "occasions": ["Bureau", "Journée", "Automne"],
    "seasons": ["Automne", "Hiver"],
    "longevity": 4,
    "sillage": 3,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["issey-miyake-l-eau-d-issey", "issey-miyake-nuit-d-issey", "issey-miyake-a-drop-d-issey"]
  },
  {
    "id": "armaf-club-de-nuit-women",
    "slug": "armaf-club-de-nuit-women",
    "h1": "Armaf Club de Nuit Women Parfum Femme Algérie",
    "name": "Club de Nuit Women",
    "brand": "Armaf",
    "brandSlug": "armaf",
    "category": "parfums-femme",
    "gender": "femme",
    "concentration": "EDP",
    "volume": "105ml",
    "price": 5200,
    "originalPrice": null,
    "badge": null,
    "image": "/images/products/armaf-club-de-nuit-women.jpg",
    "shortDescription": "Armaf Club de Nuit Women est un floral fruité séduisant pour la femme moderne. Bergamote, rose et musc dans une composition accessible inspirée des grandes fragrances féminines.",
    "description": "Armaf Club de Nuit Women est la déclinaison féminine de la célèbre ligne Club de Nuit d'Armaf. Comme ses homologues masculins, elle propose une fragrance de qualité à prix accessible, inspirée des grandes fragrances féminines de luxe, pour permettre au plus grand nombre d'accéder à un parfum plaisant et bien construit.\n\nLa composition s'ouvre sur un accord fruité lumineux de bergamote, mandarine et framboise qui apportent fraîcheur et vivacité. Le cœur est un bouquet floral généreux de rose, de jasmin et d'iris dans un accord féminin classique et séduisant. La base douce de musc blanc, bois de santal et patchouli léger assure une tenue satisfaisante et un sillage agréable.\n\nClub de Nuit Women est le choix de la femme algérienne qui veut un parfum féminin et bien construit sans investir dans les grandes marques de luxe. Sa qualité de fabrication et sa formulation soignée en font un excellent rapport qualité-prix.\n\nMaison Numidia propose ce parfum Armaf authentique avec livraison COD dans les 58 wilayas d'Algérie.",
    "notes": {
      "top": ["Bergamote", "Mandarine", "Framboise"],
      "heart": ["Rose", "Jasmin", "Iris"],
      "base": ["Musc blanc", "Bois de santal", "Patchouli"]
    },
    "family": "Floral Fruité",
    "occasions": ["Bureau", "Journée", "Casual"],
    "seasons": ["Printemps", "Été", "Automne"],
    "longevity": 4,
    "sillage": 3,
    "inStock": true,
    "featured": false,
    "isOriental": false,
    "related": ["armaf-club-de-nuit-intense-man", "armaf-club-de-nuit-intense-femme", "britney-spears-fantasy"]
  }
];

const allSlugs = new Set([...existingSlugs, ...newProducts.map(p => p.slug)]);
let errors = 0;
for (const p of newProducts) {
  if (existingSlugs.has(p.slug)) { console.error(`DUPLICATE: ${p.slug}`); errors++; }
  for (const r of p.related) {
    if (!allSlugs.has(r)) { console.error(`MISSING related "${r}" in ${p.slug}`); errors++; }
  }
}
if (errors > 0) { console.error(`${errors} erreur(s) — abandon`); process.exit(1); }

data.products.push(...newProducts);
writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf8');
console.log(`✅ ${newProducts.length} produits ajoutés — total: ${data.products.length} produits`);
